package org.apache.poi.ddf;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import androidx.core.os.EnvironmentCompat;
import com.google.zxing.pdf417.PDF417Common;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.apache.poi.util.Units;
import org.opencv.videoio.Videoio;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'PROTECTION__LOCKAGAINSTGROUPING' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:485)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByRegister(EnumVisitor.java:422)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:351)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:284)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:153)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:102)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes4.dex */
public final class EscherPropertyTypes {
    private static final /* synthetic */ EscherPropertyTypes[] $VALUES;
    public static final EscherPropertyTypes BLIP__BLIPFILENAME;
    public static final EscherPropertyTypes BLIP__BLIPFLAGS;
    public static final EscherPropertyTypes BLIP__BLIPTODISPLAY;
    public static final EscherPropertyTypes BLIP__BRIGHTNESSSETTING;
    public static final EscherPropertyTypes BLIP__CONTRASTSETTING;
    public static final EscherPropertyTypes BLIP__CROPFROMBOTTOM;
    public static final EscherPropertyTypes BLIP__CROPFROMLEFT;
    public static final EscherPropertyTypes BLIP__CROPFROMRIGHT;
    public static final EscherPropertyTypes BLIP__CROPFROMTOP;
    public static final EscherPropertyTypes BLIP__DOUBLEMOD;
    public static final EscherPropertyTypes BLIP__GAMMA;
    public static final EscherPropertyTypes BLIP__NOHITTESTPICTURE;
    public static final EscherPropertyTypes BLIP__PICTUREACTIVE;
    public static final EscherPropertyTypes BLIP__PICTUREBILEVEL;
    public static final EscherPropertyTypes BLIP__PICTUREFILLMOD;
    public static final EscherPropertyTypes BLIP__PICTUREGRAY;
    public static final EscherPropertyTypes BLIP__PICTUREID;
    public static final EscherPropertyTypes BLIP__PICTURELINE;
    public static final EscherPropertyTypes BLIP__PRINTBLIP;
    public static final EscherPropertyTypes BLIP__PRINTBLIPFILENAME;
    public static final EscherPropertyTypes BLIP__PRINTFLAGS;
    public static final EscherPropertyTypes BLIP__TRANSPARENTCOLOR;
    public static final EscherPropertyTypes CALLOUT__CALLOUTACCENTBAR;
    public static final EscherPropertyTypes CALLOUT__CALLOUTANGLE;
    public static final EscherPropertyTypes CALLOUT__CALLOUTDROPSPECIFIED;
    public static final EscherPropertyTypes CALLOUT__CALLOUTDROPTYPE;
    public static final EscherPropertyTypes CALLOUT__CALLOUTLENGTHSPECIFIED;
    public static final EscherPropertyTypes CALLOUT__CALLOUTMINUSX;
    public static final EscherPropertyTypes CALLOUT__CALLOUTMINUSY;
    public static final EscherPropertyTypes CALLOUT__CALLOUTTEXTBORDER;
    public static final EscherPropertyTypes CALLOUT__CALLOUTTYPE;
    public static final EscherPropertyTypes CALLOUT__DROPAUTO;
    public static final EscherPropertyTypes CALLOUT__ISCALLOUT;
    public static final EscherPropertyTypes CALLOUT__LENGTHSPECIFIED;
    public static final EscherPropertyTypes CALLOUT__XYCALLOUTGAP;
    public static final EscherPropertyTypes FILL__ANGLE;
    public static final EscherPropertyTypes FILL__BACKOPACITY;
    public static final EscherPropertyTypes FILL__BLIPFILENAME;
    public static final EscherPropertyTypes FILL__BLIPFLAGS;
    public static final EscherPropertyTypes FILL__CRMOD;
    public static final EscherPropertyTypes FILL__DZTYPE;
    public static final EscherPropertyTypes FILL__FILLBACKCOLOR;
    public static final EscherPropertyTypes FILL__FILLCOLOR;
    public static final EscherPropertyTypes FILL__FILLED;
    public static final EscherPropertyTypes FILL__FILLOPACITY;
    public static final EscherPropertyTypes FILL__FILLTYPE;
    public static final EscherPropertyTypes FILL__FOCUS;
    public static final EscherPropertyTypes FILL__HEIGHT;
    public static final EscherPropertyTypes FILL__HITTESTFILL;
    public static final EscherPropertyTypes FILL__NOFILLHITTEST;
    public static final EscherPropertyTypes FILL__ORIGINX;
    public static final EscherPropertyTypes FILL__ORIGINY;
    public static final EscherPropertyTypes FILL__PATTERNTEXTURE;
    public static final EscherPropertyTypes FILL__RECTBOTTOM;
    public static final EscherPropertyTypes FILL__RECTLEFT;
    public static final EscherPropertyTypes FILL__RECTRIGHT;
    public static final EscherPropertyTypes FILL__RECTTOP;
    public static final EscherPropertyTypes FILL__SHADECOLORS;
    public static final EscherPropertyTypes FILL__SHADEPRESET;
    public static final EscherPropertyTypes FILL__SHADETYPE;
    public static final EscherPropertyTypes FILL__SHAPE;
    public static final EscherPropertyTypes FILL__SHAPEORIGINX;
    public static final EscherPropertyTypes FILL__SHAPEORIGINY;
    public static final EscherPropertyTypes FILL__TOBOTTOM;
    public static final EscherPropertyTypes FILL__TOLEFT;
    public static final EscherPropertyTypes FILL__TORIGHT;
    public static final EscherPropertyTypes FILL__TOTOP;
    public static final EscherPropertyTypes FILL__USERECT;
    public static final EscherPropertyTypes FILL__WIDTH;
    public static final EscherPropertyTypes GEOMETRY__3DOK;
    public static final EscherPropertyTypes GEOMETRY__ADJUST10VALUE;
    public static final EscherPropertyTypes GEOMETRY__ADJUST2VALUE;
    public static final EscherPropertyTypes GEOMETRY__ADJUST3VALUE;
    public static final EscherPropertyTypes GEOMETRY__ADJUST4VALUE;
    public static final EscherPropertyTypes GEOMETRY__ADJUST5VALUE;
    public static final EscherPropertyTypes GEOMETRY__ADJUST6VALUE;
    public static final EscherPropertyTypes GEOMETRY__ADJUST7VALUE;
    public static final EscherPropertyTypes GEOMETRY__ADJUST8VALUE;
    public static final EscherPropertyTypes GEOMETRY__ADJUST9VALUE;
    public static final EscherPropertyTypes GEOMETRY__ADJUSTVALUE;
    public static final EscherPropertyTypes GEOMETRY__BOTTOM;
    public static final EscherPropertyTypes GEOMETRY__CXK;
    public static final EscherPropertyTypes GEOMETRY__FILLOK;
    public static final EscherPropertyTypes GEOMETRY__FILLSHADESHAPEOK;
    public static final EscherPropertyTypes GEOMETRY__GEOTEXTOK;
    public static final EscherPropertyTypes GEOMETRY__LEFT;
    public static final EscherPropertyTypes GEOMETRY__LINEOK;
    public static final EscherPropertyTypes GEOMETRY__PADJUSTHANDLES;
    public static final EscherPropertyTypes GEOMETRY__PCONNECTIONSITES;
    public static final EscherPropertyTypes GEOMETRY__PCONNECTIONSITESDIR;
    public static final EscherPropertyTypes GEOMETRY__PFRAGMENTS;
    public static final EscherPropertyTypes GEOMETRY__PGUIDES;
    public static final EscherPropertyTypes GEOMETRY__PINSCRIBE;
    public static final EscherPropertyTypes GEOMETRY__RIGHT;
    public static final EscherPropertyTypes GEOMETRY__SEGMENTINFO;
    public static final EscherPropertyTypes GEOMETRY__SHADOWOK;
    public static final EscherPropertyTypes GEOMETRY__SHAPEPATH;
    public static final EscherPropertyTypes GEOMETRY__TOP;
    public static final EscherPropertyTypes GEOMETRY__VERTICES;
    public static final EscherPropertyTypes GEOMETRY__XLIMO;
    public static final EscherPropertyTypes GEOMETRY__YLIMO;
    public static final EscherPropertyTypes GEOTEXT__ALIGNMENTONCURVE;
    public static final EscherPropertyTypes GEOTEXT__BOLDFONT;
    public static final EscherPropertyTypes GEOTEXT__CHARBOUNDINGBOX;
    public static final EscherPropertyTypes GEOTEXT__DEFAULTPOINTSIZE;
    public static final EscherPropertyTypes GEOTEXT__FONTFAMILYNAME;
    public static final EscherPropertyTypes GEOTEXT__HASTEXTEFFECT;
    public static final EscherPropertyTypes GEOTEXT__ITALICFONT;
    public static final EscherPropertyTypes GEOTEXT__KERNCHARACTERS;
    public static final EscherPropertyTypes GEOTEXT__NOMEASUREALONGPATH;
    public static final EscherPropertyTypes GEOTEXT__REVERSEROWORDER;
    public static final EscherPropertyTypes GEOTEXT__ROTATECHARACTERS;
    public static final EscherPropertyTypes GEOTEXT__RTFTEXT;
    public static final EscherPropertyTypes GEOTEXT__SCALETEXTONPATH;
    public static final EscherPropertyTypes GEOTEXT__SHADOWFONT;
    public static final EscherPropertyTypes GEOTEXT__SMALLCAPSFONT;
    public static final EscherPropertyTypes GEOTEXT__STRETCHCHARHEIGHT;
    public static final EscherPropertyTypes GEOTEXT__STRETCHTOFITSHAPE;
    public static final EscherPropertyTypes GEOTEXT__STRIKETHROUGHFONT;
    public static final EscherPropertyTypes GEOTEXT__TEXTSPACING;
    public static final EscherPropertyTypes GEOTEXT__TIGHTORTRACK;
    public static final EscherPropertyTypes GEOTEXT__UNDERLINEFONT;
    public static final EscherPropertyTypes GEOTEXT__UNICODE;
    public static final EscherPropertyTypes GROUPSHAPE__1DADJUSTMENT;
    public static final EscherPropertyTypes GROUPSHAPE__BEHINDDOCUMENT;
    public static final EscherPropertyTypes GROUPSHAPE__BORDERBOTTOMCOLOR;
    public static final EscherPropertyTypes GROUPSHAPE__BORDERLEFTCOLOR;
    public static final EscherPropertyTypes GROUPSHAPE__BORDERRIGHTCOLOR;
    public static final EscherPropertyTypes GROUPSHAPE__BORDERTOPCOLOR;
    public static final EscherPropertyTypes GROUPSHAPE__DESCRIPTION;
    public static final EscherPropertyTypes GROUPSHAPE__EDITEDWRAP;
    public static final EscherPropertyTypes GROUPSHAPE__FLAGS;
    public static final EscherPropertyTypes GROUPSHAPE__HIDDEN;
    public static final EscherPropertyTypes GROUPSHAPE__HR_ALIGN;
    public static final EscherPropertyTypes GROUPSHAPE__HR_HEIGHT;
    public static final EscherPropertyTypes GROUPSHAPE__HR_PCT;
    public static final EscherPropertyTypes GROUPSHAPE__HR_WIDTH;
    public static final EscherPropertyTypes GROUPSHAPE__HYPERLINK;
    public static final EscherPropertyTypes GROUPSHAPE__ISBUTTON;
    public static final EscherPropertyTypes GROUPSHAPE__METROBLOB;
    public static final EscherPropertyTypes GROUPSHAPE__ONDBLCLICKNOTIFY;
    public static final EscherPropertyTypes GROUPSHAPE__POSH;
    public static final EscherPropertyTypes GROUPSHAPE__POSRELH;
    public static final EscherPropertyTypes GROUPSHAPE__POSRELV;
    public static final EscherPropertyTypes GROUPSHAPE__POSV;
    public static final EscherPropertyTypes GROUPSHAPE__REGROUPID;
    public static final EscherPropertyTypes GROUPSHAPE__SCRIPT;
    public static final EscherPropertyTypes GROUPSHAPE__SCRIPTEXT;
    public static final EscherPropertyTypes GROUPSHAPE__SCRIPTLANG;
    public static final EscherPropertyTypes GROUPSHAPE__SHAPENAME;
    public static final EscherPropertyTypes GROUPSHAPE__TABLEPROPERTIES;
    public static final EscherPropertyTypes GROUPSHAPE__TABLEROWPROPERTIES;
    public static final EscherPropertyTypes GROUPSHAPE__TOOLTIP;
    public static final EscherPropertyTypes GROUPSHAPE__UNUSED906;
    public static final EscherPropertyTypes GROUPSHAPE__WEBBOT;
    public static final EscherPropertyTypes GROUPSHAPE__WRAPDISTBOTTOM;
    public static final EscherPropertyTypes GROUPSHAPE__WRAPDISTLEFT;
    public static final EscherPropertyTypes GROUPSHAPE__WRAPDISTRIGHT;
    public static final EscherPropertyTypes GROUPSHAPE__WRAPDISTTOP;
    public static final EscherPropertyTypes GROUPSHAPE__WRAPPOLYGONVERTICES;
    public static final EscherPropertyTypes GROUPSHAPE__ZORDER;
    public static final EscherPropertyTypes LINESTYLE__ANYLINE;
    public static final EscherPropertyTypes LINESTYLE__ARROWHEADSOK;
    public static final EscherPropertyTypes LINESTYLE__BACKCOLOR;
    public static final EscherPropertyTypes LINESTYLE__COLOR;
    public static final EscherPropertyTypes LINESTYLE__CRMOD;
    public static final EscherPropertyTypes LINESTYLE__FILLBLIP;
    public static final EscherPropertyTypes LINESTYLE__FILLBLIPFLAGS;
    public static final EscherPropertyTypes LINESTYLE__FILLBLIPNAME;
    public static final EscherPropertyTypes LINESTYLE__FILLDZTYPE;
    public static final EscherPropertyTypes LINESTYLE__FILLHEIGHT;
    public static final EscherPropertyTypes LINESTYLE__FILLWIDTH;
    public static final EscherPropertyTypes LINESTYLE__HITLINETEST;
    public static final EscherPropertyTypes LINESTYLE__LINEDASHING;
    public static final EscherPropertyTypes LINESTYLE__LINEDASHSTYLE;
    public static final EscherPropertyTypes LINESTYLE__LINEENDARROWHEAD;
    public static final EscherPropertyTypes LINESTYLE__LINEENDARROWLENGTH;
    public static final EscherPropertyTypes LINESTYLE__LINEENDARROWWIDTH;
    public static final EscherPropertyTypes LINESTYLE__LINEENDCAPSTYLE;
    public static final EscherPropertyTypes LINESTYLE__LINEFILLSHAPE;
    public static final EscherPropertyTypes LINESTYLE__LINEJOINSTYLE;
    public static final EscherPropertyTypes LINESTYLE__LINEMITERLIMIT;
    public static final EscherPropertyTypes LINESTYLE__LINESTARTARROWHEAD;
    public static final EscherPropertyTypes LINESTYLE__LINESTARTARROWLENGTH;
    public static final EscherPropertyTypes LINESTYLE__LINESTARTARROWWIDTH;
    public static final EscherPropertyTypes LINESTYLE__LINESTYLE;
    public static final EscherPropertyTypes LINESTYLE__LINETYPE;
    public static final EscherPropertyTypes LINESTYLE__LINEWIDTH;
    public static final EscherPropertyTypes LINESTYLE__NOLINEDRAWDASH;
    public static final EscherPropertyTypes LINESTYLE__NOLINEDRAWDASH_BOTTOM;
    public static final EscherPropertyTypes LINESTYLE__NOLINEDRAWDASH_LEFT;
    public static final EscherPropertyTypes LINESTYLE__NOLINEDRAWDASH_RIGHT;
    public static final EscherPropertyTypes LINESTYLE__NOLINEDRAWDASH_TOP;
    public static final EscherPropertyTypes LINESTYLE__OPACITY;
    private static final Map<Short, EscherPropertyTypes> LOOKUP;
    public static final EscherPropertyTypes PERSPECTIVE__OFFSETX;
    public static final EscherPropertyTypes PERSPECTIVE__OFFSETY;
    public static final EscherPropertyTypes PERSPECTIVE__ORIGINX;
    public static final EscherPropertyTypes PERSPECTIVE__ORIGINY;
    public static final EscherPropertyTypes PERSPECTIVE__PERSPECTIVEON;
    public static final EscherPropertyTypes PERSPECTIVE__PERSPECTIVEX;
    public static final EscherPropertyTypes PERSPECTIVE__PERSPECTIVEY;
    public static final EscherPropertyTypes PERSPECTIVE__SCALEXTOX;
    public static final EscherPropertyTypes PERSPECTIVE__SCALEXTOY;
    public static final EscherPropertyTypes PERSPECTIVE__SCALEYTOX;
    public static final EscherPropertyTypes PERSPECTIVE__SCALEYTOY;
    public static final EscherPropertyTypes PERSPECTIVE__TYPE;
    public static final EscherPropertyTypes PERSPECTIVE__WEIGHT;
    public static final EscherPropertyTypes PROTECTION__LOCKADJUSTHANDLES;
    public static final EscherPropertyTypes PROTECTION__LOCKAGAINSTGROUPING;
    public static final EscherPropertyTypes PROTECTION__LOCKAGAINSTSELECT;
    public static final EscherPropertyTypes PROTECTION__LOCKASPECTRATIO;
    public static final EscherPropertyTypes PROTECTION__LOCKCROPPING;
    public static final EscherPropertyTypes PROTECTION__LOCKPOSITION;
    public static final EscherPropertyTypes PROTECTION__LOCKROTATION;
    public static final EscherPropertyTypes PROTECTION__LOCKTEXT;
    public static final EscherPropertyTypes PROTECTION__LOCKVERTICES;
    public static final EscherPropertyTypes RESERVED646;
    public static final EscherPropertyTypes RESERVED650;
    public static final EscherPropertyTypes RESERVED652;
    public static final EscherPropertyTypes RESERVED653;
    public static final EscherPropertyTypes SHADOWSTYLE__COLOR;
    public static final EscherPropertyTypes SHADOWSTYLE__CRMOD;
    public static final EscherPropertyTypes SHADOWSTYLE__HIGHLIGHT;
    public static final EscherPropertyTypes SHADOWSTYLE__OFFSETX;
    public static final EscherPropertyTypes SHADOWSTYLE__OFFSETY;
    public static final EscherPropertyTypes SHADOWSTYLE__OPACITY;
    public static final EscherPropertyTypes SHADOWSTYLE__ORIGINX;
    public static final EscherPropertyTypes SHADOWSTYLE__ORIGINY;
    public static final EscherPropertyTypes SHADOWSTYLE__PERSPECTIVEX;
    public static final EscherPropertyTypes SHADOWSTYLE__PERSPECTIVEY;
    public static final EscherPropertyTypes SHADOWSTYLE__SCALEXTOX;
    public static final EscherPropertyTypes SHADOWSTYLE__SCALEXTOY;
    public static final EscherPropertyTypes SHADOWSTYLE__SCALEYTOX;
    public static final EscherPropertyTypes SHADOWSTYLE__SCALEYTOY;
    public static final EscherPropertyTypes SHADOWSTYLE__SECONDOFFSETX;
    public static final EscherPropertyTypes SHADOWSTYLE__SECONDOFFSETY;
    public static final EscherPropertyTypes SHADOWSTYLE__SHADOW;
    public static final EscherPropertyTypes SHADOWSTYLE__SHADOWOBSURED;
    public static final EscherPropertyTypes SHADOWSTYLE__TYPE;
    public static final EscherPropertyTypes SHADOWSTYLE__WEIGHT;
    public static final EscherPropertyTypes SHAPE__BACKGROUNDSHAPE;
    public static final EscherPropertyTypes SHAPE__BLACKANDWHITESETTINGS;
    public static final EscherPropertyTypes SHAPE__CONNECTORSTYLE;
    public static final EscherPropertyTypes SHAPE__DELETEATTACHEDOBJECT;
    public static final EscherPropertyTypes SHAPE__LOCKSHAPETYPE;
    public static final EscherPropertyTypes SHAPE__MASTER;
    public static final EscherPropertyTypes SHAPE__OLEICON;
    public static final EscherPropertyTypes SHAPE__PREFERRELATIVERESIZE;
    public static final EscherPropertyTypes SHAPE__WMODEBW;
    public static final EscherPropertyTypes SHAPE__WMODEPUREBW;
    public static final EscherPropertyTypes TEXT__ANCHORTEXT;
    public static final EscherPropertyTypes TEXT__BIDIR;
    public static final EscherPropertyTypes TEXT__FONTROTATION;
    public static final EscherPropertyTypes TEXT__IDOFNEXTSHAPE;
    public static final EscherPropertyTypes TEXT__ROTATETEXTWITHSHAPE;
    public static final EscherPropertyTypes TEXT__SCALETEXT;
    public static final EscherPropertyTypes TEXT__SINGLECLICKSELECTS;
    public static final EscherPropertyTypes TEXT__SIZESHAPETOFITTEXT;
    public static final EscherPropertyTypes TEXT__SIZE_TEXT_TO_FIT_SHAPE;
    public static final EscherPropertyTypes TEXT__TEXTBOTTOM;
    public static final EscherPropertyTypes TEXT__TEXTFLOW;
    public static final EscherPropertyTypes TEXT__TEXTID;
    public static final EscherPropertyTypes TEXT__TEXTLEFT;
    public static final EscherPropertyTypes TEXT__TEXTRIGHT;
    public static final EscherPropertyTypes TEXT__TEXTTOP;
    public static final EscherPropertyTypes TEXT__USEHOSTMARGINS;
    public static final EscherPropertyTypes TEXT__WRAPTEXT;
    public static final EscherPropertyTypes THREEDSTYLE__AMBIENTINTENSITY;
    public static final EscherPropertyTypes THREEDSTYLE__CONSTRAINROTATION;
    public static final EscherPropertyTypes THREEDSTYLE__FILLHARSH;
    public static final EscherPropertyTypes THREEDSTYLE__FILLINTENSITY;
    public static final EscherPropertyTypes THREEDSTYLE__FILLX;
    public static final EscherPropertyTypes THREEDSTYLE__FILLY;
    public static final EscherPropertyTypes THREEDSTYLE__FILLZ;
    public static final EscherPropertyTypes THREEDSTYLE__KEYHARSH;
    public static final EscherPropertyTypes THREEDSTYLE__KEYINTENSITY;
    public static final EscherPropertyTypes THREEDSTYLE__KEYX;
    public static final EscherPropertyTypes THREEDSTYLE__KEYY;
    public static final EscherPropertyTypes THREEDSTYLE__KEYZ;
    public static final EscherPropertyTypes THREEDSTYLE__ORIGINX;
    public static final EscherPropertyTypes THREEDSTYLE__ORIGINY;
    public static final EscherPropertyTypes THREEDSTYLE__PARALLEL;
    public static final EscherPropertyTypes THREEDSTYLE__RENDERMODE;
    public static final EscherPropertyTypes THREEDSTYLE__ROTATIONANGLE;
    public static final EscherPropertyTypes THREEDSTYLE__ROTATIONAXISX;
    public static final EscherPropertyTypes THREEDSTYLE__ROTATIONAXISY;
    public static final EscherPropertyTypes THREEDSTYLE__ROTATIONAXISZ;
    public static final EscherPropertyTypes THREEDSTYLE__ROTATIONCENTERAUTO;
    public static final EscherPropertyTypes THREEDSTYLE__ROTATIONCENTERX;
    public static final EscherPropertyTypes THREEDSTYLE__ROTATIONCENTERY;
    public static final EscherPropertyTypes THREEDSTYLE__ROTATIONCENTERZ;
    public static final EscherPropertyTypes THREEDSTYLE__SKEWAMOUNT;
    public static final EscherPropertyTypes THREEDSTYLE__SKEWANGLE;
    public static final EscherPropertyTypes THREEDSTYLE__TOLERANCE;
    public static final EscherPropertyTypes THREEDSTYLE__XROTATIONANGLE;
    public static final EscherPropertyTypes THREEDSTYLE__XVIEWPOINT;
    public static final EscherPropertyTypes THREEDSTYLE__YROTATIONANGLE;
    public static final EscherPropertyTypes THREEDSTYLE__YVIEWPOINT;
    public static final EscherPropertyTypes THREEDSTYLE__ZVIEWPOINT;
    public static final EscherPropertyTypes THREED__3DEFFECT;
    public static final EscherPropertyTypes THREED__BOOLEAN_PROPERTIES;
    public static final EscherPropertyTypes THREED__CRMOD;
    public static final EscherPropertyTypes THREED__DIFFUSEAMOUNT;
    public static final EscherPropertyTypes THREED__EDGETHICKNESS;
    public static final EscherPropertyTypes THREED__EXTRUDEBACKWARD;
    public static final EscherPropertyTypes THREED__EXTRUDEFORWARD;
    public static final EscherPropertyTypes THREED__EXTRUDEPLANE;
    public static final EscherPropertyTypes THREED__EXTRUSIONCOLOR;
    public static final EscherPropertyTypes THREED__EXTRUSIONCOLOREXT;
    public static final EscherPropertyTypes THREED__EXTRUSIONCOLOREXTMOD;
    public static final EscherPropertyTypes THREED__LIGHTFACE;
    public static final EscherPropertyTypes THREED__METALLIC;
    public static final EscherPropertyTypes THREED__SHININESS;
    public static final EscherPropertyTypes THREED__SPECULARAMOUNT;
    public static final EscherPropertyTypes THREED__USEEXTRUSIONCOLOR;
    public static final EscherPropertyTypes TRANSFORM__ROTATION;
    public static final EscherPropertyTypes UNKNOWN;
    public final EscherPropertyTypesHolder holder;
    public final String propName;
    public final short propNumber;

    static {
        EscherPropertyTypes escherPropertyTypes = new EscherPropertyTypes("TRANSFORM__ROTATION", 0, 4, "transform.rotation");
        TRANSFORM__ROTATION = escherPropertyTypes;
        EscherPropertyTypes escherPropertyTypes2 = new EscherPropertyTypes("PROTECTION__LOCKROTATION", 1, 119, "protection.lockrotation");
        PROTECTION__LOCKROTATION = escherPropertyTypes2;
        EscherPropertyTypes escherPropertyTypes3 = new EscherPropertyTypes("PROTECTION__LOCKASPECTRATIO", 2, 120, "protection.lockaspectratio");
        PROTECTION__LOCKASPECTRATIO = escherPropertyTypes3;
        EscherPropertyTypes escherPropertyTypes4 = new EscherPropertyTypes("PROTECTION__LOCKPOSITION", 3, 121, "protection.lockposition");
        PROTECTION__LOCKPOSITION = escherPropertyTypes4;
        EscherPropertyTypes escherPropertyTypes5 = new EscherPropertyTypes("PROTECTION__LOCKAGAINSTSELECT", 4, 122, "protection.lockagainstselect");
        PROTECTION__LOCKAGAINSTSELECT = escherPropertyTypes5;
        EscherPropertyTypes escherPropertyTypes6 = new EscherPropertyTypes("PROTECTION__LOCKCROPPING", 5, 123, "protection.lockcropping");
        PROTECTION__LOCKCROPPING = escherPropertyTypes6;
        EscherPropertyTypes escherPropertyTypes7 = new EscherPropertyTypes("PROTECTION__LOCKVERTICES", 6, 124, "protection.lockvertices");
        PROTECTION__LOCKVERTICES = escherPropertyTypes7;
        EscherPropertyTypes escherPropertyTypes8 = new EscherPropertyTypes("PROTECTION__LOCKTEXT", 7, 125, "protection.locktext");
        PROTECTION__LOCKTEXT = escherPropertyTypes8;
        EscherPropertyTypes escherPropertyTypes9 = new EscherPropertyTypes("PROTECTION__LOCKADJUSTHANDLES", 8, 126, "protection.lockadjusthandles");
        PROTECTION__LOCKADJUSTHANDLES = escherPropertyTypes9;
        EscherPropertyTypesHolder escherPropertyTypesHolder = EscherPropertyTypesHolder.BOOLEAN;
        EscherPropertyTypes escherPropertyTypes10 = new EscherPropertyTypes("PROTECTION__LOCKAGAINSTGROUPING", 9, 127, "protection.lockagainstgrouping", escherPropertyTypesHolder);
        PROTECTION__LOCKAGAINSTGROUPING = escherPropertyTypes10;
        EscherPropertyTypes escherPropertyTypes11 = new EscherPropertyTypes("TEXT__TEXTID", 10, 128, "text.textid");
        TEXT__TEXTID = escherPropertyTypes11;
        EscherPropertyTypes escherPropertyTypes12 = new EscherPropertyTypes("TEXT__TEXTLEFT", 11, 129, "text.textleft");
        TEXT__TEXTLEFT = escherPropertyTypes12;
        EscherPropertyTypes escherPropertyTypes13 = new EscherPropertyTypes("TEXT__TEXTTOP", 12, 130, "text.texttop");
        TEXT__TEXTTOP = escherPropertyTypes13;
        EscherPropertyTypes escherPropertyTypes14 = new EscherPropertyTypes("TEXT__TEXTRIGHT", 13, 131, "text.textright");
        TEXT__TEXTRIGHT = escherPropertyTypes14;
        EscherPropertyTypes escherPropertyTypes15 = new EscherPropertyTypes("TEXT__TEXTBOTTOM", 14, 132, "text.textbottom");
        TEXT__TEXTBOTTOM = escherPropertyTypes15;
        EscherPropertyTypes escherPropertyTypes16 = new EscherPropertyTypes("TEXT__WRAPTEXT", 15, 133, "text.wraptext");
        TEXT__WRAPTEXT = escherPropertyTypes16;
        EscherPropertyTypes escherPropertyTypes17 = new EscherPropertyTypes("TEXT__SCALETEXT", 16, 134, "text.scaletext");
        TEXT__SCALETEXT = escherPropertyTypes17;
        EscherPropertyTypes escherPropertyTypes18 = new EscherPropertyTypes("TEXT__ANCHORTEXT", 17, 135, "text.anchortext");
        TEXT__ANCHORTEXT = escherPropertyTypes18;
        EscherPropertyTypes escherPropertyTypes19 = new EscherPropertyTypes("TEXT__TEXTFLOW", 18, 136, "text.textflow");
        TEXT__TEXTFLOW = escherPropertyTypes19;
        EscherPropertyTypes escherPropertyTypes20 = new EscherPropertyTypes("TEXT__FONTROTATION", 19, 137, "text.fontrotation");
        TEXT__FONTROTATION = escherPropertyTypes20;
        EscherPropertyTypes escherPropertyTypes21 = new EscherPropertyTypes("TEXT__IDOFNEXTSHAPE", 20, 138, "text.idofnextshape");
        TEXT__IDOFNEXTSHAPE = escherPropertyTypes21;
        EscherPropertyTypes escherPropertyTypes22 = new EscherPropertyTypes("TEXT__BIDIR", 21, 139, "text.bidir");
        TEXT__BIDIR = escherPropertyTypes22;
        EscherPropertyTypes escherPropertyTypes23 = new EscherPropertyTypes("TEXT__SINGLECLICKSELECTS", 22, 187, "text.singleclickselects");
        TEXT__SINGLECLICKSELECTS = escherPropertyTypes23;
        EscherPropertyTypes escherPropertyTypes24 = new EscherPropertyTypes("TEXT__USEHOSTMARGINS", 23, 188, "text.usehostmargins");
        TEXT__USEHOSTMARGINS = escherPropertyTypes24;
        EscherPropertyTypes escherPropertyTypes25 = new EscherPropertyTypes("TEXT__ROTATETEXTWITHSHAPE", 24, 189, "text.rotatetextwithshape");
        TEXT__ROTATETEXTWITHSHAPE = escherPropertyTypes25;
        EscherPropertyTypes escherPropertyTypes26 = new EscherPropertyTypes("TEXT__SIZESHAPETOFITTEXT", 25, 190, "text.sizeshapetofittext");
        TEXT__SIZESHAPETOFITTEXT = escherPropertyTypes26;
        EscherPropertyTypes escherPropertyTypes27 = new EscherPropertyTypes("TEXT__SIZE_TEXT_TO_FIT_SHAPE", 26, 191, "text.sizetexttofitshape", escherPropertyTypesHolder);
        TEXT__SIZE_TEXT_TO_FIT_SHAPE = escherPropertyTypes27;
        EscherPropertyTypes escherPropertyTypes28 = new EscherPropertyTypes("GEOTEXT__UNICODE", 27, 192, "geotext.unicode");
        GEOTEXT__UNICODE = escherPropertyTypes28;
        EscherPropertyTypes escherPropertyTypes29 = new EscherPropertyTypes("GEOTEXT__RTFTEXT", 28, 193, "geotext.rtftext");
        GEOTEXT__RTFTEXT = escherPropertyTypes29;
        EscherPropertyTypes escherPropertyTypes30 = new EscherPropertyTypes("GEOTEXT__ALIGNMENTONCURVE", 29, 194, "geotext.alignmentoncurve");
        GEOTEXT__ALIGNMENTONCURVE = escherPropertyTypes30;
        EscherPropertyTypes escherPropertyTypes31 = new EscherPropertyTypes("GEOTEXT__DEFAULTPOINTSIZE", 30, 195, "geotext.defaultpointsize");
        GEOTEXT__DEFAULTPOINTSIZE = escherPropertyTypes31;
        EscherPropertyTypes escherPropertyTypes32 = new EscherPropertyTypes("GEOTEXT__TEXTSPACING", 31, 196, "geotext.textspacing");
        GEOTEXT__TEXTSPACING = escherPropertyTypes32;
        EscherPropertyTypes escherPropertyTypes33 = new EscherPropertyTypes("GEOTEXT__FONTFAMILYNAME", 32, 197, "geotext.fontfamilyname");
        GEOTEXT__FONTFAMILYNAME = escherPropertyTypes33;
        EscherPropertyTypes escherPropertyTypes34 = new EscherPropertyTypes("GEOTEXT__REVERSEROWORDER", 33, 240, "geotext.reverseroworder");
        GEOTEXT__REVERSEROWORDER = escherPropertyTypes34;
        EscherPropertyTypes escherPropertyTypes35 = new EscherPropertyTypes("GEOTEXT__HASTEXTEFFECT", 34, 241, "geotext.hastexteffect");
        GEOTEXT__HASTEXTEFFECT = escherPropertyTypes35;
        EscherPropertyTypes escherPropertyTypes36 = new EscherPropertyTypes("GEOTEXT__ROTATECHARACTERS", 35, 242, "geotext.rotatecharacters");
        GEOTEXT__ROTATECHARACTERS = escherPropertyTypes36;
        EscherPropertyTypes escherPropertyTypes37 = new EscherPropertyTypes("GEOTEXT__KERNCHARACTERS", 36, 243, "geotext.kerncharacters");
        GEOTEXT__KERNCHARACTERS = escherPropertyTypes37;
        EscherPropertyTypes escherPropertyTypes38 = new EscherPropertyTypes("GEOTEXT__TIGHTORTRACK", 37, 244, "geotext.tightortrack");
        GEOTEXT__TIGHTORTRACK = escherPropertyTypes38;
        EscherPropertyTypes escherPropertyTypes39 = new EscherPropertyTypes("GEOTEXT__STRETCHTOFITSHAPE", 38, 245, "geotext.stretchtofitshape");
        GEOTEXT__STRETCHTOFITSHAPE = escherPropertyTypes39;
        EscherPropertyTypes escherPropertyTypes40 = new EscherPropertyTypes("GEOTEXT__CHARBOUNDINGBOX", 39, 246, "geotext.charboundingbox");
        GEOTEXT__CHARBOUNDINGBOX = escherPropertyTypes40;
        EscherPropertyTypes escherPropertyTypes41 = new EscherPropertyTypes("GEOTEXT__SCALETEXTONPATH", 40, 247, "geotext.scaletextonpath");
        GEOTEXT__SCALETEXTONPATH = escherPropertyTypes41;
        EscherPropertyTypes escherPropertyTypes42 = new EscherPropertyTypes("GEOTEXT__STRETCHCHARHEIGHT", 41, 248, "geotext.stretchcharheight");
        GEOTEXT__STRETCHCHARHEIGHT = escherPropertyTypes42;
        EscherPropertyTypes escherPropertyTypes43 = new EscherPropertyTypes("GEOTEXT__NOMEASUREALONGPATH", 42, 249, "geotext.nomeasurealongpath");
        GEOTEXT__NOMEASUREALONGPATH = escherPropertyTypes43;
        EscherPropertyTypes escherPropertyTypes44 = new EscherPropertyTypes("GEOTEXT__BOLDFONT", 43, 250, "geotext.boldfont");
        GEOTEXT__BOLDFONT = escherPropertyTypes44;
        EscherPropertyTypes escherPropertyTypes45 = new EscherPropertyTypes("GEOTEXT__ITALICFONT", 44, 251, "geotext.italicfont");
        GEOTEXT__ITALICFONT = escherPropertyTypes45;
        EscherPropertyTypes escherPropertyTypes46 = new EscherPropertyTypes("GEOTEXT__UNDERLINEFONT", 45, 252, "geotext.underlinefont");
        GEOTEXT__UNDERLINEFONT = escherPropertyTypes46;
        EscherPropertyTypes escherPropertyTypes47 = new EscherPropertyTypes("GEOTEXT__SHADOWFONT", 46, 253, "geotext.shadowfont");
        GEOTEXT__SHADOWFONT = escherPropertyTypes47;
        EscherPropertyTypes escherPropertyTypes48 = new EscherPropertyTypes("GEOTEXT__SMALLCAPSFONT", 47, 254, "geotext.smallcapsfont");
        GEOTEXT__SMALLCAPSFONT = escherPropertyTypes48;
        EscherPropertyTypes escherPropertyTypes49 = new EscherPropertyTypes("GEOTEXT__STRIKETHROUGHFONT", 48, 255, "geotext.strikethroughfont");
        GEOTEXT__STRIKETHROUGHFONT = escherPropertyTypes49;
        EscherPropertyTypes escherPropertyTypes50 = new EscherPropertyTypes("BLIP__CROPFROMTOP", 49, 256, "blip.cropfromtop");
        BLIP__CROPFROMTOP = escherPropertyTypes50;
        EscherPropertyTypes escherPropertyTypes51 = new EscherPropertyTypes("BLIP__CROPFROMBOTTOM", 50, 257, "blip.cropfrombottom");
        BLIP__CROPFROMBOTTOM = escherPropertyTypes51;
        EscherPropertyTypes escherPropertyTypes52 = new EscherPropertyTypes("BLIP__CROPFROMLEFT", 51, 258, "blip.cropfromleft");
        BLIP__CROPFROMLEFT = escherPropertyTypes52;
        EscherPropertyTypes escherPropertyTypes53 = new EscherPropertyTypes("BLIP__CROPFROMRIGHT", 52, 259, "blip.cropfromright");
        BLIP__CROPFROMRIGHT = escherPropertyTypes53;
        EscherPropertyTypes escherPropertyTypes54 = new EscherPropertyTypes("BLIP__BLIPTODISPLAY", 53, 260, "blip.bliptodisplay");
        BLIP__BLIPTODISPLAY = escherPropertyTypes54;
        EscherPropertyTypes escherPropertyTypes55 = new EscherPropertyTypes("BLIP__BLIPFILENAME", 54, 261, "blip.blipfilename");
        BLIP__BLIPFILENAME = escherPropertyTypes55;
        EscherPropertyTypes escherPropertyTypes56 = new EscherPropertyTypes("BLIP__BLIPFLAGS", 55, 262, "blip.blipflags");
        BLIP__BLIPFLAGS = escherPropertyTypes56;
        EscherPropertyTypes escherPropertyTypes57 = new EscherPropertyTypes("BLIP__TRANSPARENTCOLOR", 56, 263, "blip.transparentcolor");
        BLIP__TRANSPARENTCOLOR = escherPropertyTypes57;
        EscherPropertyTypes escherPropertyTypes58 = new EscherPropertyTypes("BLIP__CONTRASTSETTING", 57, 264, "blip.contrastsetting");
        BLIP__CONTRASTSETTING = escherPropertyTypes58;
        EscherPropertyTypes escherPropertyTypes59 = new EscherPropertyTypes("BLIP__BRIGHTNESSSETTING", 58, 265, "blip.brightnesssetting");
        BLIP__BRIGHTNESSSETTING = escherPropertyTypes59;
        EscherPropertyTypes escherPropertyTypes60 = new EscherPropertyTypes("BLIP__GAMMA", 59, 266, "blip.gamma");
        BLIP__GAMMA = escherPropertyTypes60;
        EscherPropertyTypes escherPropertyTypes61 = new EscherPropertyTypes("BLIP__PICTUREID", 60, 267, "blip.pictureid");
        BLIP__PICTUREID = escherPropertyTypes61;
        EscherPropertyTypes escherPropertyTypes62 = new EscherPropertyTypes("BLIP__DOUBLEMOD", 61, 268, "blip.doublemod");
        BLIP__DOUBLEMOD = escherPropertyTypes62;
        EscherPropertyTypes escherPropertyTypes63 = new EscherPropertyTypes("BLIP__PICTUREFILLMOD", 62, 269, "blip.picturefillmod");
        BLIP__PICTUREFILLMOD = escherPropertyTypes63;
        EscherPropertyTypes escherPropertyTypes64 = new EscherPropertyTypes("BLIP__PICTURELINE", 63, 270, "blip.pictureline");
        BLIP__PICTURELINE = escherPropertyTypes64;
        EscherPropertyTypes escherPropertyTypes65 = new EscherPropertyTypes("BLIP__PRINTBLIP", 64, 271, "blip.printblip");
        BLIP__PRINTBLIP = escherPropertyTypes65;
        EscherPropertyTypes escherPropertyTypes66 = new EscherPropertyTypes("BLIP__PRINTBLIPFILENAME", 65, 272, "blip.printblipfilename");
        BLIP__PRINTBLIPFILENAME = escherPropertyTypes66;
        EscherPropertyTypes escherPropertyTypes67 = new EscherPropertyTypes("BLIP__PRINTFLAGS", 66, 273, "blip.printflags");
        BLIP__PRINTFLAGS = escherPropertyTypes67;
        EscherPropertyTypes escherPropertyTypes68 = new EscherPropertyTypes("BLIP__NOHITTESTPICTURE", 67, 316, "blip.nohittestpicture");
        BLIP__NOHITTESTPICTURE = escherPropertyTypes68;
        EscherPropertyTypes escherPropertyTypes69 = new EscherPropertyTypes("BLIP__PICTUREGRAY", 68, 317, "blip.picturegray");
        BLIP__PICTUREGRAY = escherPropertyTypes69;
        EscherPropertyTypes escherPropertyTypes70 = new EscherPropertyTypes("BLIP__PICTUREBILEVEL", 69, 318, "blip.picturebilevel");
        BLIP__PICTUREBILEVEL = escherPropertyTypes70;
        EscherPropertyTypes escherPropertyTypes71 = new EscherPropertyTypes("BLIP__PICTUREACTIVE", 70, 319, "blip.pictureactive");
        BLIP__PICTUREACTIVE = escherPropertyTypes71;
        EscherPropertyTypes escherPropertyTypes72 = new EscherPropertyTypes("GEOMETRY__LEFT", 71, 320, "geometry.left");
        GEOMETRY__LEFT = escherPropertyTypes72;
        EscherPropertyTypes escherPropertyTypes73 = new EscherPropertyTypes("GEOMETRY__TOP", 72, 321, "geometry.top");
        GEOMETRY__TOP = escherPropertyTypes73;
        EscherPropertyTypes escherPropertyTypes74 = new EscherPropertyTypes("GEOMETRY__RIGHT", 73, 322, "geometry.right");
        GEOMETRY__RIGHT = escherPropertyTypes74;
        EscherPropertyTypes escherPropertyTypes75 = new EscherPropertyTypes("GEOMETRY__BOTTOM", 74, 323, "geometry.bottom");
        GEOMETRY__BOTTOM = escherPropertyTypes75;
        EscherPropertyTypes escherPropertyTypes76 = new EscherPropertyTypes("GEOMETRY__SHAPEPATH", 75, 324, "geometry.shapepath", EscherPropertyTypesHolder.SHAPE_PATH);
        GEOMETRY__SHAPEPATH = escherPropertyTypes76;
        EscherPropertyTypesHolder escherPropertyTypesHolder2 = EscherPropertyTypesHolder.ARRAY;
        EscherPropertyTypes escherPropertyTypes77 = new EscherPropertyTypes("GEOMETRY__VERTICES", 76, 325, "geometry.vertices", escherPropertyTypesHolder2);
        GEOMETRY__VERTICES = escherPropertyTypes77;
        EscherPropertyTypes escherPropertyTypes78 = new EscherPropertyTypes("GEOMETRY__SEGMENTINFO", 77, 326, "geometry.segmentinfo", escherPropertyTypesHolder2);
        GEOMETRY__SEGMENTINFO = escherPropertyTypes78;
        EscherPropertyTypes escherPropertyTypes79 = new EscherPropertyTypes("GEOMETRY__ADJUSTVALUE", 78, 327, "geometry.adjustvalue");
        GEOMETRY__ADJUSTVALUE = escherPropertyTypes79;
        EscherPropertyTypes escherPropertyTypes80 = new EscherPropertyTypes("GEOMETRY__ADJUST2VALUE", 79, 328, "geometry.adjust2value");
        GEOMETRY__ADJUST2VALUE = escherPropertyTypes80;
        EscherPropertyTypes escherPropertyTypes81 = new EscherPropertyTypes("GEOMETRY__ADJUST3VALUE", 80, 329, "geometry.adjust3value");
        GEOMETRY__ADJUST3VALUE = escherPropertyTypes81;
        EscherPropertyTypes escherPropertyTypes82 = new EscherPropertyTypes("GEOMETRY__ADJUST4VALUE", 81, 330, "geometry.adjust4value");
        GEOMETRY__ADJUST4VALUE = escherPropertyTypes82;
        EscherPropertyTypes escherPropertyTypes83 = new EscherPropertyTypes("GEOMETRY__ADJUST5VALUE", 82, 331, "geometry.adjust5value");
        GEOMETRY__ADJUST5VALUE = escherPropertyTypes83;
        EscherPropertyTypes escherPropertyTypes84 = new EscherPropertyTypes("GEOMETRY__ADJUST6VALUE", 83, 332, "geometry.adjust6value");
        GEOMETRY__ADJUST6VALUE = escherPropertyTypes84;
        EscherPropertyTypes escherPropertyTypes85 = new EscherPropertyTypes("GEOMETRY__ADJUST7VALUE", 84, 333, "geometry.adjust7value");
        GEOMETRY__ADJUST7VALUE = escherPropertyTypes85;
        EscherPropertyTypes escherPropertyTypes86 = new EscherPropertyTypes("GEOMETRY__ADJUST8VALUE", 85, 334, "geometry.adjust8value");
        GEOMETRY__ADJUST8VALUE = escherPropertyTypes86;
        EscherPropertyTypes escherPropertyTypes87 = new EscherPropertyTypes("GEOMETRY__ADJUST9VALUE", 86, 335, "geometry.adjust9value");
        GEOMETRY__ADJUST9VALUE = escherPropertyTypes87;
        EscherPropertyTypes escherPropertyTypes88 = new EscherPropertyTypes("GEOMETRY__ADJUST10VALUE", 87, 336, "geometry.adjust10value");
        GEOMETRY__ADJUST10VALUE = escherPropertyTypes88;
        EscherPropertyTypes escherPropertyTypes89 = new EscherPropertyTypes("GEOMETRY__PCONNECTIONSITES", 88, 337, "geometry.pConnectionSites");
        GEOMETRY__PCONNECTIONSITES = escherPropertyTypes89;
        EscherPropertyTypes escherPropertyTypes90 = new EscherPropertyTypes("GEOMETRY__PCONNECTIONSITESDIR", 89, 338, "geometry.pConnectionSitesDir");
        GEOMETRY__PCONNECTIONSITESDIR = escherPropertyTypes90;
        EscherPropertyTypes escherPropertyTypes91 = new EscherPropertyTypes("GEOMETRY__XLIMO", 90, 339, "geometry.xLimo");
        GEOMETRY__XLIMO = escherPropertyTypes91;
        EscherPropertyTypes escherPropertyTypes92 = new EscherPropertyTypes("GEOMETRY__YLIMO", 91, 340, "geometry.yLimo");
        GEOMETRY__YLIMO = escherPropertyTypes92;
        EscherPropertyTypes escherPropertyTypes93 = new EscherPropertyTypes("GEOMETRY__PADJUSTHANDLES", 92, 341, "geometry.pAdjustHandles");
        GEOMETRY__PADJUSTHANDLES = escherPropertyTypes93;
        EscherPropertyTypes escherPropertyTypes94 = new EscherPropertyTypes("GEOMETRY__PGUIDES", 93, 342, "geometry.pGuides");
        GEOMETRY__PGUIDES = escherPropertyTypes94;
        EscherPropertyTypes escherPropertyTypes95 = new EscherPropertyTypes("GEOMETRY__PINSCRIBE", 94, 343, "geometry.pInscribe");
        GEOMETRY__PINSCRIBE = escherPropertyTypes95;
        EscherPropertyTypes escherPropertyTypes96 = new EscherPropertyTypes("GEOMETRY__CXK", 95, 344, "geometry.cxk");
        GEOMETRY__CXK = escherPropertyTypes96;
        EscherPropertyTypes escherPropertyTypes97 = new EscherPropertyTypes("GEOMETRY__PFRAGMENTS", 96, 345, "geometry.pFragments");
        GEOMETRY__PFRAGMENTS = escherPropertyTypes97;
        EscherPropertyTypes escherPropertyTypes98 = new EscherPropertyTypes("GEOMETRY__SHADOWOK", 97, 378, "geometry.shadowOK");
        GEOMETRY__SHADOWOK = escherPropertyTypes98;
        EscherPropertyTypes escherPropertyTypes99 = new EscherPropertyTypes("GEOMETRY__3DOK", 98, 379, "geometry.3dok");
        GEOMETRY__3DOK = escherPropertyTypes99;
        EscherPropertyTypes escherPropertyTypes100 = new EscherPropertyTypes("GEOMETRY__LINEOK", 99, 380, "geometry.lineok");
        GEOMETRY__LINEOK = escherPropertyTypes100;
        EscherPropertyTypes escherPropertyTypes101 = new EscherPropertyTypes("GEOMETRY__GEOTEXTOK", 100, 381, "geometry.geotextok");
        GEOMETRY__GEOTEXTOK = escherPropertyTypes101;
        EscherPropertyTypes escherPropertyTypes102 = new EscherPropertyTypes("GEOMETRY__FILLSHADESHAPEOK", 101, 382, "geometry.fillshadeshapeok");
        GEOMETRY__FILLSHADESHAPEOK = escherPropertyTypes102;
        EscherPropertyTypes escherPropertyTypes103 = new EscherPropertyTypes("GEOMETRY__FILLOK", 102, 383, "geometry.fillok", escherPropertyTypesHolder);
        GEOMETRY__FILLOK = escherPropertyTypes103;
        EscherPropertyTypes escherPropertyTypes104 = new EscherPropertyTypes("FILL__FILLTYPE", 103, 384, "fill.filltype");
        FILL__FILLTYPE = escherPropertyTypes104;
        EscherPropertyTypesHolder escherPropertyTypesHolder3 = EscherPropertyTypesHolder.RGB;
        EscherPropertyTypes escherPropertyTypes105 = new EscherPropertyTypes("FILL__FILLCOLOR", 104, 385, "fill.fillcolor", escherPropertyTypesHolder3);
        FILL__FILLCOLOR = escherPropertyTypes105;
        EscherPropertyTypes escherPropertyTypes106 = new EscherPropertyTypes("FILL__FILLOPACITY", 105, 386, "fill.fillopacity");
        FILL__FILLOPACITY = escherPropertyTypes106;
        EscherPropertyTypes escherPropertyTypes107 = new EscherPropertyTypes("FILL__FILLBACKCOLOR", 106, 387, "fill.fillbackcolor", escherPropertyTypesHolder3);
        FILL__FILLBACKCOLOR = escherPropertyTypes107;
        EscherPropertyTypes escherPropertyTypes108 = new EscherPropertyTypes("FILL__BACKOPACITY", 107, 388, "fill.backopacity");
        FILL__BACKOPACITY = escherPropertyTypes108;
        EscherPropertyTypes escherPropertyTypes109 = new EscherPropertyTypes("FILL__CRMOD", 108, 389, "fill.crmod");
        FILL__CRMOD = escherPropertyTypes109;
        EscherPropertyTypes escherPropertyTypes110 = new EscherPropertyTypes("FILL__PATTERNTEXTURE", 109, 390, "fill.patterntexture");
        FILL__PATTERNTEXTURE = escherPropertyTypes110;
        EscherPropertyTypes escherPropertyTypes111 = new EscherPropertyTypes("FILL__BLIPFILENAME", 110, 391, "fill.blipfilename");
        FILL__BLIPFILENAME = escherPropertyTypes111;
        EscherPropertyTypes escherPropertyTypes112 = new EscherPropertyTypes("FILL__BLIPFLAGS", 111, 392, "fill.blipflags");
        FILL__BLIPFLAGS = escherPropertyTypes112;
        EscherPropertyTypes escherPropertyTypes113 = new EscherPropertyTypes("FILL__WIDTH", 112, 393, "fill.width");
        FILL__WIDTH = escherPropertyTypes113;
        EscherPropertyTypes escherPropertyTypes114 = new EscherPropertyTypes("FILL__HEIGHT", 113, 394, "fill.height");
        FILL__HEIGHT = escherPropertyTypes114;
        EscherPropertyTypes escherPropertyTypes115 = new EscherPropertyTypes("FILL__ANGLE", 114, 395, "fill.angle");
        FILL__ANGLE = escherPropertyTypes115;
        EscherPropertyTypes escherPropertyTypes116 = new EscherPropertyTypes("FILL__FOCUS", 115, 396, "fill.focus");
        FILL__FOCUS = escherPropertyTypes116;
        EscherPropertyTypes escherPropertyTypes117 = new EscherPropertyTypes("FILL__TOLEFT", 116, 397, "fill.toleft");
        FILL__TOLEFT = escherPropertyTypes117;
        EscherPropertyTypes escherPropertyTypes118 = new EscherPropertyTypes("FILL__TOTOP", 117, 398, "fill.totop");
        FILL__TOTOP = escherPropertyTypes118;
        EscherPropertyTypes escherPropertyTypes119 = new EscherPropertyTypes("FILL__TORIGHT", 118, 399, "fill.toright");
        FILL__TORIGHT = escherPropertyTypes119;
        EscherPropertyTypes escherPropertyTypes120 = new EscherPropertyTypes("FILL__TOBOTTOM", 119, 400, "fill.tobottom");
        FILL__TOBOTTOM = escherPropertyTypes120;
        EscherPropertyTypes escherPropertyTypes121 = new EscherPropertyTypes("FILL__RECTLEFT", 120, 401, "fill.rectleft");
        FILL__RECTLEFT = escherPropertyTypes121;
        EscherPropertyTypes escherPropertyTypes122 = new EscherPropertyTypes("FILL__RECTTOP", 121, 402, "fill.recttop");
        FILL__RECTTOP = escherPropertyTypes122;
        EscherPropertyTypes escherPropertyTypes123 = new EscherPropertyTypes("FILL__RECTRIGHT", 122, 403, "fill.rectright");
        FILL__RECTRIGHT = escherPropertyTypes123;
        EscherPropertyTypes escherPropertyTypes124 = new EscherPropertyTypes("FILL__RECTBOTTOM", 123, Videoio.CAP_PROP_XI_TRG_SOURCE, "fill.rectbottom");
        FILL__RECTBOTTOM = escherPropertyTypes124;
        EscherPropertyTypes escherPropertyTypes125 = new EscherPropertyTypes("FILL__DZTYPE", 124, Videoio.CAP_PROP_XI_TRG_SOFTWARE, "fill.dztype");
        FILL__DZTYPE = escherPropertyTypes125;
        EscherPropertyTypes escherPropertyTypes126 = new EscherPropertyTypes("FILL__SHADEPRESET", 125, Videoio.CAP_PROP_XI_GPI_SELECTOR, "fill.shadepreset");
        FILL__SHADEPRESET = escherPropertyTypes126;
        EscherPropertyTypes escherPropertyTypes127 = new EscherPropertyTypes("FILL__SHADECOLORS", 126, Videoio.CAP_PROP_XI_GPI_MODE, "fill.shadecolors", escherPropertyTypesHolder2);
        FILL__SHADECOLORS = escherPropertyTypes127;
        EscherPropertyTypes escherPropertyTypes128 = new EscherPropertyTypes("FILL__ORIGINX", 127, Videoio.CAP_PROP_XI_GPI_LEVEL, "fill.originx");
        FILL__ORIGINX = escherPropertyTypes128;
        EscherPropertyTypes escherPropertyTypes129 = new EscherPropertyTypes("FILL__ORIGINY", 128, Videoio.CAP_PROP_XI_GPO_SELECTOR, "fill.originy");
        FILL__ORIGINY = escherPropertyTypes129;
        EscherPropertyTypes escherPropertyTypes130 = new EscherPropertyTypes("FILL__SHAPEORIGINX", 129, Videoio.CAP_PROP_XI_GPO_MODE, "fill.shapeoriginx");
        FILL__SHAPEORIGINX = escherPropertyTypes130;
        EscherPropertyTypes escherPropertyTypes131 = new EscherPropertyTypes("FILL__SHAPEORIGINY", 130, Videoio.CAP_PROP_XI_LED_SELECTOR, "fill.shapeoriginy");
        FILL__SHAPEORIGINY = escherPropertyTypes131;
        EscherPropertyTypes escherPropertyTypes132 = new EscherPropertyTypes("FILL__SHADETYPE", 131, Videoio.CAP_PROP_XI_LED_MODE, "fill.shadetype");
        FILL__SHADETYPE = escherPropertyTypes132;
        EscherPropertyTypes escherPropertyTypes133 = new EscherPropertyTypes("FILL__FILLED", 132, 443, "fill.filled");
        FILL__FILLED = escherPropertyTypes133;
        EscherPropertyTypes escherPropertyTypes134 = new EscherPropertyTypes("FILL__HITTESTFILL", 133, 444, "fill.hittestfill");
        FILL__HITTESTFILL = escherPropertyTypes134;
        EscherPropertyTypes escherPropertyTypes135 = new EscherPropertyTypes("FILL__SHAPE", 134, Videoio.CAP_PROP_XI_BPC, "fill.shape");
        FILL__SHAPE = escherPropertyTypes135;
        EscherPropertyTypes escherPropertyTypes136 = new EscherPropertyTypes("FILL__USERECT", 135, 446, "fill.userect");
        FILL__USERECT = escherPropertyTypes136;
        EscherPropertyTypes escherPropertyTypes137 = new EscherPropertyTypes("FILL__NOFILLHITTEST", 136, 447, "fill.nofillhittest", escherPropertyTypesHolder);
        FILL__NOFILLHITTEST = escherPropertyTypes137;
        EscherPropertyTypes escherPropertyTypes138 = new EscherPropertyTypes("LINESTYLE__COLOR", 137, Videoio.CAP_PROP_XI_WB_KR, "linestyle.color", escherPropertyTypesHolder3);
        LINESTYLE__COLOR = escherPropertyTypes138;
        EscherPropertyTypes escherPropertyTypes139 = new EscherPropertyTypes("LINESTYLE__OPACITY", 138, Videoio.CAP_PROP_XI_WB_KG, "linestyle.opacity");
        LINESTYLE__OPACITY = escherPropertyTypes139;
        EscherPropertyTypes escherPropertyTypes140 = new EscherPropertyTypes("LINESTYLE__BACKCOLOR", 139, Videoio.CAP_PROP_XI_WB_KB, "linestyle.backcolor", escherPropertyTypesHolder3);
        LINESTYLE__BACKCOLOR = escherPropertyTypes140;
        EscherPropertyTypes escherPropertyTypes141 = new EscherPropertyTypes("LINESTYLE__CRMOD", 140, Videoio.CAP_PROP_XI_WIDTH, "linestyle.crmod");
        LINESTYLE__CRMOD = escherPropertyTypes141;
        EscherPropertyTypes escherPropertyTypes142 = new EscherPropertyTypes("LINESTYLE__LINETYPE", 141, Videoio.CAP_PROP_XI_HEIGHT, "linestyle.linetype");
        LINESTYLE__LINETYPE = escherPropertyTypes142;
        EscherPropertyTypes escherPropertyTypes143 = new EscherPropertyTypes("LINESTYLE__FILLBLIP", 142, 453, "linestyle.fillblip");
        LINESTYLE__FILLBLIP = escherPropertyTypes143;
        EscherPropertyTypes escherPropertyTypes144 = new EscherPropertyTypes("LINESTYLE__FILLBLIPNAME", 143, 454, "linestyle.fillblipname");
        LINESTYLE__FILLBLIPNAME = escherPropertyTypes144;
        EscherPropertyTypes escherPropertyTypes145 = new EscherPropertyTypes("LINESTYLE__FILLBLIPFLAGS", 144, 455, "linestyle.fillblipflags");
        LINESTYLE__FILLBLIPFLAGS = escherPropertyTypes145;
        EscherPropertyTypes escherPropertyTypes146 = new EscherPropertyTypes("LINESTYLE__FILLWIDTH", 145, 456, "linestyle.fillwidth");
        LINESTYLE__FILLWIDTH = escherPropertyTypes146;
        EscherPropertyTypes escherPropertyTypes147 = new EscherPropertyTypes("LINESTYLE__FILLHEIGHT", 146, 457, "linestyle.fillheight");
        LINESTYLE__FILLHEIGHT = escherPropertyTypes147;
        EscherPropertyTypes escherPropertyTypes148 = new EscherPropertyTypes("LINESTYLE__FILLDZTYPE", 147, 458, "linestyle.filldztype");
        LINESTYLE__FILLDZTYPE = escherPropertyTypes148;
        EscherPropertyTypes escherPropertyTypes149 = new EscherPropertyTypes("LINESTYLE__LINEWIDTH", 148, Videoio.CAP_PROP_XI_LIMIT_BANDWIDTH, "linestyle.linewidth");
        LINESTYLE__LINEWIDTH = escherPropertyTypes149;
        EscherPropertyTypes escherPropertyTypes150 = new EscherPropertyTypes("LINESTYLE__LINEMITERLIMIT", 149, Videoio.CAP_PROP_XI_SENSOR_DATA_BIT_DEPTH, "linestyle.linemiterlimit");
        LINESTYLE__LINEMITERLIMIT = escherPropertyTypes150;
        EscherPropertyTypes escherPropertyTypes151 = new EscherPropertyTypes("LINESTYLE__LINESTYLE", 150, Videoio.CAP_PROP_XI_OUTPUT_DATA_BIT_DEPTH, "linestyle.linestyle");
        LINESTYLE__LINESTYLE = escherPropertyTypes151;
        EscherPropertyTypes escherPropertyTypes152 = new EscherPropertyTypes("LINESTYLE__LINEDASHING", 151, Videoio.CAP_PROP_XI_IMAGE_DATA_BIT_DEPTH, "linestyle.linedashing");
        LINESTYLE__LINEDASHING = escherPropertyTypes152;
        EscherPropertyTypes escherPropertyTypes153 = new EscherPropertyTypes("LINESTYLE__LINEDASHSTYLE", 152, Videoio.CAP_PROP_XI_OUTPUT_DATA_PACKING, "linestyle.linedashstyle", escherPropertyTypesHolder2);
        LINESTYLE__LINEDASHSTYLE = escherPropertyTypes153;
        EscherPropertyTypes escherPropertyTypes154 = new EscherPropertyTypes("LINESTYLE__LINESTARTARROWHEAD", 153, Videoio.CAP_PROP_XI_OUTPUT_DATA_PACKING_TYPE, "linestyle.linestartarrowhead");
        LINESTYLE__LINESTARTARROWHEAD = escherPropertyTypes154;
        EscherPropertyTypes escherPropertyTypes155 = new EscherPropertyTypes("LINESTYLE__LINEENDARROWHEAD", 154, Videoio.CAP_PROP_XI_IS_COOLED, "linestyle.lineendarrowhead");
        LINESTYLE__LINEENDARROWHEAD = escherPropertyTypes155;
        EscherPropertyTypes escherPropertyTypes156 = new EscherPropertyTypes("LINESTYLE__LINESTARTARROWWIDTH", 155, Videoio.CAP_PROP_XI_COOLING, "linestyle.linestartarrowwidth");
        LINESTYLE__LINESTARTARROWWIDTH = escherPropertyTypes156;
        EscherPropertyTypes escherPropertyTypes157 = new EscherPropertyTypes("LINESTYLE__LINESTARTARROWLENGTH", 156, Videoio.CAP_PROP_XI_TARGET_TEMP, "linestyle.linestartarrowlength");
        LINESTYLE__LINESTARTARROWLENGTH = escherPropertyTypes157;
        EscherPropertyTypes escherPropertyTypes158 = new EscherPropertyTypes("LINESTYLE__LINEENDARROWWIDTH", 157, Videoio.CAP_PROP_XI_CHIP_TEMP, "linestyle.lineendarrowwidth");
        LINESTYLE__LINEENDARROWWIDTH = escherPropertyTypes158;
        EscherPropertyTypes escherPropertyTypes159 = new EscherPropertyTypes("LINESTYLE__LINEENDARROWLENGTH", 158, Videoio.CAP_PROP_XI_HOUS_TEMP, "linestyle.lineendarrowlength");
        LINESTYLE__LINEENDARROWLENGTH = escherPropertyTypes159;
        EscherPropertyTypes escherPropertyTypes160 = new EscherPropertyTypes("LINESTYLE__LINEJOINSTYLE", 159, Videoio.CAP_PROP_XI_CMS, "linestyle.linejoinstyle");
        LINESTYLE__LINEJOINSTYLE = escherPropertyTypes160;
        EscherPropertyTypes escherPropertyTypes161 = new EscherPropertyTypes("LINESTYLE__LINEENDCAPSTYLE", 160, Videoio.CAP_PROP_XI_APPLY_CMS, "linestyle.lineendcapstyle");
        LINESTYLE__LINEENDCAPSTYLE = escherPropertyTypes161;
        EscherPropertyTypes escherPropertyTypes162 = new EscherPropertyTypes("LINESTYLE__ARROWHEADSOK", 161, 507, "linestyle.arrowheadsok");
        LINESTYLE__ARROWHEADSOK = escherPropertyTypes162;
        EscherPropertyTypes escherPropertyTypes163 = new EscherPropertyTypes("LINESTYLE__ANYLINE", 162, 508, "linestyle.anyline");
        LINESTYLE__ANYLINE = escherPropertyTypes163;
        EscherPropertyTypes escherPropertyTypes164 = new EscherPropertyTypes("LINESTYLE__HITLINETEST", 163, 509, "linestyle.hitlinetest");
        LINESTYLE__HITLINETEST = escherPropertyTypes164;
        EscherPropertyTypes escherPropertyTypes165 = new EscherPropertyTypes("LINESTYLE__LINEFILLSHAPE", 164, 510, "linestyle.linefillshape");
        LINESTYLE__LINEFILLSHAPE = escherPropertyTypes165;
        EscherPropertyTypes escherPropertyTypes166 = new EscherPropertyTypes("LINESTYLE__NOLINEDRAWDASH", 165, 511, "linestyle.nolinedrawdash", escherPropertyTypesHolder);
        LINESTYLE__NOLINEDRAWDASH = escherPropertyTypes166;
        EscherPropertyTypes escherPropertyTypes167 = new EscherPropertyTypes("LINESTYLE__NOLINEDRAWDASH_LEFT", 166, 1407, "linestyle.nolinedrawdash.left", escherPropertyTypesHolder);
        LINESTYLE__NOLINEDRAWDASH_LEFT = escherPropertyTypes167;
        EscherPropertyTypes escherPropertyTypes168 = new EscherPropertyTypes("LINESTYLE__NOLINEDRAWDASH_TOP", 167, 1471, "linestyle.nolinedrawdash.top", escherPropertyTypesHolder);
        LINESTYLE__NOLINEDRAWDASH_TOP = escherPropertyTypes168;
        EscherPropertyTypes escherPropertyTypes169 = new EscherPropertyTypes("LINESTYLE__NOLINEDRAWDASH_BOTTOM", 168, 1599, "linestyle.nolinedrawdash.bottom", escherPropertyTypesHolder);
        LINESTYLE__NOLINEDRAWDASH_BOTTOM = escherPropertyTypes169;
        EscherPropertyTypes escherPropertyTypes170 = new EscherPropertyTypes("LINESTYLE__NOLINEDRAWDASH_RIGHT", 169, 1535, "linestyle.nolinedrawdash.right", escherPropertyTypesHolder);
        LINESTYLE__NOLINEDRAWDASH_RIGHT = escherPropertyTypes170;
        EscherPropertyTypes escherPropertyTypes171 = new EscherPropertyTypes("SHADOWSTYLE__TYPE", 170, 512, "shadowstyle.type");
        SHADOWSTYLE__TYPE = escherPropertyTypes171;
        EscherPropertyTypes escherPropertyTypes172 = new EscherPropertyTypes("SHADOWSTYLE__COLOR", 171, 513, "shadowstyle.color", escherPropertyTypesHolder3);
        SHADOWSTYLE__COLOR = escherPropertyTypes172;
        EscherPropertyTypes escherPropertyTypes173 = new EscherPropertyTypes("SHADOWSTYLE__HIGHLIGHT", 172, 514, "shadowstyle.highlight");
        SHADOWSTYLE__HIGHLIGHT = escherPropertyTypes173;
        EscherPropertyTypes escherPropertyTypes174 = new EscherPropertyTypes("SHADOWSTYLE__CRMOD", 173, Videoio.CAP_PROP_XI_LENS_FOCUS_DISTANCE, "shadowstyle.crmod");
        SHADOWSTYLE__CRMOD = escherPropertyTypes174;
        EscherPropertyTypes escherPropertyTypes175 = new EscherPropertyTypes("SHADOWSTYLE__OPACITY", 174, Videoio.CAP_PROP_XI_LENS_FOCAL_LENGTH, "shadowstyle.opacity");
        SHADOWSTYLE__OPACITY = escherPropertyTypes175;
        EscherPropertyTypes escherPropertyTypes176 = new EscherPropertyTypes("SHADOWSTYLE__OFFSETX", 175, Videoio.CAP_PROP_XI_LENS_FEATURE_SELECTOR, "shadowstyle.offsetx");
        SHADOWSTYLE__OFFSETX = escherPropertyTypes176;
        EscherPropertyTypes escherPropertyTypes177 = new EscherPropertyTypes("SHADOWSTYLE__OFFSETY", 176, Videoio.CAP_PROP_XI_LENS_FEATURE, "shadowstyle.offsety");
        SHADOWSTYLE__OFFSETY = escherPropertyTypes177;
        EscherPropertyTypes escherPropertyTypes178 = new EscherPropertyTypes("SHADOWSTYLE__SECONDOFFSETX", 177, 519, "shadowstyle.secondoffsetx");
        SHADOWSTYLE__SECONDOFFSETX = escherPropertyTypes178;
        EscherPropertyTypes escherPropertyTypes179 = new EscherPropertyTypes("SHADOWSTYLE__SECONDOFFSETY", 178, 520, "shadowstyle.secondoffsety");
        SHADOWSTYLE__SECONDOFFSETY = escherPropertyTypes179;
        EscherPropertyTypes escherPropertyTypes180 = new EscherPropertyTypes("SHADOWSTYLE__SCALEXTOX", 179, Videoio.CAP_PROP_XI_DEVICE_MODEL_ID, "shadowstyle.scalextox");
        SHADOWSTYLE__SCALEXTOX = escherPropertyTypes180;
        EscherPropertyTypes escherPropertyTypes181 = new EscherPropertyTypes("SHADOWSTYLE__SCALEYTOX", 180, Videoio.CAP_PROP_XI_DEVICE_SN, "shadowstyle.scaleytox");
        SHADOWSTYLE__SCALEYTOX = escherPropertyTypes181;
        EscherPropertyTypes escherPropertyTypes182 = new EscherPropertyTypes("SHADOWSTYLE__SCALEXTOY", 181, 523, "shadowstyle.scalextoy");
        SHADOWSTYLE__SCALEXTOY = escherPropertyTypes182;
        EscherPropertyTypes escherPropertyTypes183 = new EscherPropertyTypes("SHADOWSTYLE__SCALEYTOY", 182, 524, "shadowstyle.scaleytoy");
        SHADOWSTYLE__SCALEYTOY = escherPropertyTypes183;
        EscherPropertyTypes escherPropertyTypes184 = new EscherPropertyTypes("SHADOWSTYLE__PERSPECTIVEX", 183, 525, "shadowstyle.perspectivex");
        SHADOWSTYLE__PERSPECTIVEX = escherPropertyTypes184;
        EscherPropertyTypes escherPropertyTypes185 = new EscherPropertyTypes("SHADOWSTYLE__PERSPECTIVEY", 184, 526, "shadowstyle.perspectivey");
        SHADOWSTYLE__PERSPECTIVEY = escherPropertyTypes185;
        EscherPropertyTypes escherPropertyTypes186 = new EscherPropertyTypes("SHADOWSTYLE__WEIGHT", 185, 527, "shadowstyle.weight");
        SHADOWSTYLE__WEIGHT = escherPropertyTypes186;
        EscherPropertyTypes escherPropertyTypes187 = new EscherPropertyTypes("SHADOWSTYLE__ORIGINX", 186, 528, "shadowstyle.originx");
        SHADOWSTYLE__ORIGINX = escherPropertyTypes187;
        EscherPropertyTypes escherPropertyTypes188 = new EscherPropertyTypes("SHADOWSTYLE__ORIGINY", 187, Videoio.CAP_PROP_XI_IMAGE_DATA_FORMAT_RGB32_ALPHA, "shadowstyle.originy");
        SHADOWSTYLE__ORIGINY = escherPropertyTypes188;
        EscherPropertyTypes escherPropertyTypes189 = new EscherPropertyTypes("SHADOWSTYLE__SHADOW", 188, 574, "shadowstyle.shadow");
        SHADOWSTYLE__SHADOW = escherPropertyTypes189;
        EscherPropertyTypes escherPropertyTypes190 = new EscherPropertyTypes("SHADOWSTYLE__SHADOWOBSURED", 189, 575, "shadowstyle.shadowobscured");
        SHADOWSTYLE__SHADOWOBSURED = escherPropertyTypes190;
        EscherPropertyTypes escherPropertyTypes191 = new EscherPropertyTypes("PERSPECTIVE__TYPE", 190, Units.MASTER_DPI, "perspective.type");
        PERSPECTIVE__TYPE = escherPropertyTypes191;
        EscherPropertyTypes escherPropertyTypes192 = new EscherPropertyTypes("PERSPECTIVE__OFFSETX", 191, 577, "perspective.offsetx");
        PERSPECTIVE__OFFSETX = escherPropertyTypes192;
        EscherPropertyTypes escherPropertyTypes193 = new EscherPropertyTypes("PERSPECTIVE__OFFSETY", 192, 578, "perspective.offsety");
        PERSPECTIVE__OFFSETY = escherPropertyTypes193;
        EscherPropertyTypes escherPropertyTypes194 = new EscherPropertyTypes("PERSPECTIVE__SCALEXTOX", 193, 579, "perspective.scalextox");
        PERSPECTIVE__SCALEXTOX = escherPropertyTypes194;
        EscherPropertyTypes escherPropertyTypes195 = new EscherPropertyTypes("PERSPECTIVE__SCALEYTOX", 194, Videoio.CAP_PROP_XI_FFS_FILE_SIZE, "perspective.scaleytox");
        PERSPECTIVE__SCALEYTOX = escherPropertyTypes195;
        EscherPropertyTypes escherPropertyTypes196 = new EscherPropertyTypes("PERSPECTIVE__SCALEXTOY", 195, Videoio.CAP_PROP_XI_FREE_FFS_SIZE, "perspective.scalextoy");
        PERSPECTIVE__SCALEXTOY = escherPropertyTypes196;
        EscherPropertyTypes escherPropertyTypes197 = new EscherPropertyTypes("PERSPECTIVE__SCALEYTOY", 196, Videoio.CAP_PROP_XI_USED_FFS_SIZE, "perspective.scaleytoy");
        PERSPECTIVE__SCALEYTOY = escherPropertyTypes197;
        EscherPropertyTypes escherPropertyTypes198 = new EscherPropertyTypes("PERSPECTIVE__PERSPECTIVEX", 197, Videoio.CAP_PROP_XI_FFS_ACCESS_KEY, "perspective.perspectivex");
        PERSPECTIVE__PERSPECTIVEX = escherPropertyTypes198;
        EscherPropertyTypes escherPropertyTypes199 = new EscherPropertyTypes("PERSPECTIVE__PERSPECTIVEY", 198, 584, "perspective.perspectivey");
        PERSPECTIVE__PERSPECTIVEY = escherPropertyTypes199;
        EscherPropertyTypes escherPropertyTypes200 = new EscherPropertyTypes("PERSPECTIVE__WEIGHT", 199, Videoio.CAP_PROP_XI_SENSOR_FEATURE_SELECTOR, "perspective.weight");
        PERSPECTIVE__WEIGHT = escherPropertyTypes200;
        EscherPropertyTypes escherPropertyTypes201 = new EscherPropertyTypes("PERSPECTIVE__ORIGINX", 200, Videoio.CAP_PROP_XI_SENSOR_FEATURE_VALUE, "perspective.originx");
        PERSPECTIVE__ORIGINX = escherPropertyTypes201;
        EscherPropertyTypes escherPropertyTypes202 = new EscherPropertyTypes("PERSPECTIVE__ORIGINY", 201, Videoio.CAP_PROP_XI_TEST_PATTERN_GENERATOR_SELECTOR, "perspective.originy");
        PERSPECTIVE__ORIGINY = escherPropertyTypes202;
        EscherPropertyTypes escherPropertyTypes203 = new EscherPropertyTypes("PERSPECTIVE__PERSPECTIVEON", 202, 639, "perspective.perspectiveon");
        PERSPECTIVE__PERSPECTIVEON = escherPropertyTypes203;
        EscherPropertyTypes escherPropertyTypes204 = new EscherPropertyTypes("THREED__SPECULARAMOUNT", 203, 640, "3d.specularamount");
        THREED__SPECULARAMOUNT = escherPropertyTypes204;
        EscherPropertyTypes escherPropertyTypes205 = new EscherPropertyTypes("THREED__DIFFUSEAMOUNT", 204, 641, "3d.diffuseamount");
        THREED__DIFFUSEAMOUNT = escherPropertyTypes205;
        EscherPropertyTypes escherPropertyTypes206 = new EscherPropertyTypes("THREED__SHININESS", 205, 642, "3d.shininess");
        THREED__SHININESS = escherPropertyTypes206;
        EscherPropertyTypes escherPropertyTypes207 = new EscherPropertyTypes("THREED__EDGETHICKNESS", 206, 643, "3d.edgethickness");
        THREED__EDGETHICKNESS = escherPropertyTypes207;
        EscherPropertyTypes escherPropertyTypes208 = new EscherPropertyTypes("THREED__EXTRUDEFORWARD", 207, 644, "3d.extrudeforward");
        THREED__EXTRUDEFORWARD = escherPropertyTypes208;
        EscherPropertyTypes escherPropertyTypes209 = new EscherPropertyTypes("THREED__EXTRUDEBACKWARD", 208, 645, "3d.extrudebackward");
        THREED__EXTRUDEBACKWARD = escherPropertyTypes209;
        EscherPropertyTypes escherPropertyTypes210 = new EscherPropertyTypes("RESERVED646", 209, 646, "reserved646");
        RESERVED646 = escherPropertyTypes210;
        EscherPropertyTypes escherPropertyTypes211 = new EscherPropertyTypes("THREED__EXTRUSIONCOLOR", 210, 647, "3d.extrusioncolor", escherPropertyTypesHolder3);
        THREED__EXTRUSIONCOLOR = escherPropertyTypes211;
        EscherPropertyTypes escherPropertyTypes212 = new EscherPropertyTypes("THREED__CRMOD", 211, 648, "3d.crmod");
        THREED__CRMOD = escherPropertyTypes212;
        EscherPropertyTypes escherPropertyTypes213 = new EscherPropertyTypes("THREED__EXTRUSIONCOLOREXT", 212, 649, "3d.extrusioncolorext");
        THREED__EXTRUSIONCOLOREXT = escherPropertyTypes213;
        EscherPropertyTypes escherPropertyTypes214 = new EscherPropertyTypes("RESERVED650", 213, 650, "reserved650");
        RESERVED650 = escherPropertyTypes214;
        EscherPropertyTypes escherPropertyTypes215 = new EscherPropertyTypes("THREED__EXTRUSIONCOLOREXTMOD", 214, 651, "3d.extrusioncolorextmod");
        THREED__EXTRUSIONCOLOREXTMOD = escherPropertyTypes215;
        EscherPropertyTypes escherPropertyTypes216 = new EscherPropertyTypes("RESERVED652", 215, 652, "reserved652");
        RESERVED652 = escherPropertyTypes216;
        EscherPropertyTypes escherPropertyTypes217 = new EscherPropertyTypes("RESERVED653", 216, 653, "reserved653");
        RESERVED653 = escherPropertyTypes217;
        EscherPropertyTypes escherPropertyTypes218 = new EscherPropertyTypes("THREED__BOOLEAN_PROPERTIES", 217, 655, "3d.booleanproperties");
        THREED__BOOLEAN_PROPERTIES = escherPropertyTypes218;
        EscherPropertyTypes escherPropertyTypes219 = new EscherPropertyTypes("THREED__EXTRUDEPLANE", 218, 666, "3d.extrudeplane");
        THREED__EXTRUDEPLANE = escherPropertyTypes219;
        EscherPropertyTypes escherPropertyTypes220 = new EscherPropertyTypes("THREED__3DEFFECT", 219, 700, "3d.3deffect");
        THREED__3DEFFECT = escherPropertyTypes220;
        EscherPropertyTypes escherPropertyTypes221 = new EscherPropertyTypes("THREED__METALLIC", 220, TypedValues.TransitionType.TYPE_FROM, "3d.metallic");
        THREED__METALLIC = escherPropertyTypes221;
        EscherPropertyTypes escherPropertyTypes222 = new EscherPropertyTypes("THREED__USEEXTRUSIONCOLOR", 221, TypedValues.TransitionType.TYPE_TO, "3d.useextrusioncolor", escherPropertyTypesHolder3);
        THREED__USEEXTRUSIONCOLOR = escherPropertyTypes222;
        EscherPropertyTypes escherPropertyTypes223 = new EscherPropertyTypes("THREED__LIGHTFACE", 222, 703, "3d.lightface");
        THREED__LIGHTFACE = escherPropertyTypes223;
        EscherPropertyTypes escherPropertyTypes224 = new EscherPropertyTypes("THREEDSTYLE__YROTATIONANGLE", 223, TypedValues.TransitionType.TYPE_AUTO_TRANSITION, "3dstyle.yrotationangle");
        THREEDSTYLE__YROTATIONANGLE = escherPropertyTypes224;
        EscherPropertyTypes escherPropertyTypes225 = new EscherPropertyTypes("THREEDSTYLE__XROTATIONANGLE", 224, TypedValues.TransitionType.TYPE_INTERPOLATOR, "3dstyle.xrotationangle");
        THREEDSTYLE__XROTATIONANGLE = escherPropertyTypes225;
        EscherPropertyTypes escherPropertyTypes226 = new EscherPropertyTypes("THREEDSTYLE__ROTATIONAXISX", 225, TypedValues.TransitionType.TYPE_STAGGERED, "3dstyle.rotationaxisx");
        THREEDSTYLE__ROTATIONAXISX = escherPropertyTypes226;
        EscherPropertyTypes escherPropertyTypes227 = new EscherPropertyTypes("THREEDSTYLE__ROTATIONAXISY", 226, TypedValues.TransitionType.TYPE_TRANSITION_FLAGS, "3dstyle.rotationaxisy");
        THREEDSTYLE__ROTATIONAXISY = escherPropertyTypes227;
        EscherPropertyTypes escherPropertyTypes228 = new EscherPropertyTypes("THREEDSTYLE__ROTATIONAXISZ", 227, 708, "3dstyle.rotationaxisz");
        THREEDSTYLE__ROTATIONAXISZ = escherPropertyTypes228;
        EscherPropertyTypes escherPropertyTypes229 = new EscherPropertyTypes("THREEDSTYLE__ROTATIONANGLE", 228, 709, "3dstyle.rotationangle");
        THREEDSTYLE__ROTATIONANGLE = escherPropertyTypes229;
        EscherPropertyTypes escherPropertyTypes230 = new EscherPropertyTypes("THREEDSTYLE__ROTATIONCENTERX", 229, 710, "3dstyle.rotationcenterx");
        THREEDSTYLE__ROTATIONCENTERX = escherPropertyTypes230;
        EscherPropertyTypes escherPropertyTypes231 = new EscherPropertyTypes("THREEDSTYLE__ROTATIONCENTERY", 230, 711, "3dstyle.rotationcentery");
        THREEDSTYLE__ROTATIONCENTERY = escherPropertyTypes231;
        EscherPropertyTypes escherPropertyTypes232 = new EscherPropertyTypes("THREEDSTYLE__ROTATIONCENTERZ", 231, 712, "3dstyle.rotationcenterz");
        THREEDSTYLE__ROTATIONCENTERZ = escherPropertyTypes232;
        EscherPropertyTypes escherPropertyTypes233 = new EscherPropertyTypes("THREEDSTYLE__RENDERMODE", 232, 713, "3dstyle.rendermode");
        THREEDSTYLE__RENDERMODE = escherPropertyTypes233;
        EscherPropertyTypes escherPropertyTypes234 = new EscherPropertyTypes("THREEDSTYLE__TOLERANCE", 233, 714, "3dstyle.tolerance");
        THREEDSTYLE__TOLERANCE = escherPropertyTypes234;
        EscherPropertyTypes escherPropertyTypes235 = new EscherPropertyTypes("THREEDSTYLE__XVIEWPOINT", 234, 715, "3dstyle.xviewpoint");
        THREEDSTYLE__XVIEWPOINT = escherPropertyTypes235;
        EscherPropertyTypes escherPropertyTypes236 = new EscherPropertyTypes("THREEDSTYLE__YVIEWPOINT", 235, 716, "3dstyle.yviewpoint");
        THREEDSTYLE__YVIEWPOINT = escherPropertyTypes236;
        EscherPropertyTypes escherPropertyTypes237 = new EscherPropertyTypes("THREEDSTYLE__ZVIEWPOINT", 236, 717, "3dstyle.zviewpoint");
        THREEDSTYLE__ZVIEWPOINT = escherPropertyTypes237;
        EscherPropertyTypes escherPropertyTypes238 = new EscherPropertyTypes("THREEDSTYLE__ORIGINX", 237, 718, "3dstyle.originx");
        THREEDSTYLE__ORIGINX = escherPropertyTypes238;
        EscherPropertyTypes escherPropertyTypes239 = new EscherPropertyTypes("THREEDSTYLE__ORIGINY", 238, 719, "3dstyle.originy");
        THREEDSTYLE__ORIGINY = escherPropertyTypes239;
        EscherPropertyTypes escherPropertyTypes240 = new EscherPropertyTypes("THREEDSTYLE__SKEWANGLE", 239, 720, "3dstyle.skewangle");
        THREEDSTYLE__SKEWANGLE = escherPropertyTypes240;
        EscherPropertyTypes escherPropertyTypes241 = new EscherPropertyTypes("THREEDSTYLE__SKEWAMOUNT", 240, 721, "3dstyle.skewamount");
        THREEDSTYLE__SKEWAMOUNT = escherPropertyTypes241;
        EscherPropertyTypes escherPropertyTypes242 = new EscherPropertyTypes("THREEDSTYLE__AMBIENTINTENSITY", 241, 722, "3dstyle.ambientintensity");
        THREEDSTYLE__AMBIENTINTENSITY = escherPropertyTypes242;
        EscherPropertyTypes escherPropertyTypes243 = new EscherPropertyTypes("THREEDSTYLE__KEYX", 242, 723, "3dstyle.keyx");
        THREEDSTYLE__KEYX = escherPropertyTypes243;
        EscherPropertyTypes escherPropertyTypes244 = new EscherPropertyTypes("THREEDSTYLE__KEYY", 243, 724, "3dstyle.keyy");
        THREEDSTYLE__KEYY = escherPropertyTypes244;
        EscherPropertyTypes escherPropertyTypes245 = new EscherPropertyTypes("THREEDSTYLE__KEYZ", 244, 725, "3dstyle.keyz");
        THREEDSTYLE__KEYZ = escherPropertyTypes245;
        EscherPropertyTypes escherPropertyTypes246 = new EscherPropertyTypes("THREEDSTYLE__KEYINTENSITY", 245, 726, "3dstyle.keyintensity");
        THREEDSTYLE__KEYINTENSITY = escherPropertyTypes246;
        EscherPropertyTypes escherPropertyTypes247 = new EscherPropertyTypes("THREEDSTYLE__FILLX", 246, 727, "3dstyle.fillx");
        THREEDSTYLE__FILLX = escherPropertyTypes247;
        EscherPropertyTypes escherPropertyTypes248 = new EscherPropertyTypes("THREEDSTYLE__FILLY", 247, 728, "3dstyle.filly");
        THREEDSTYLE__FILLY = escherPropertyTypes248;
        EscherPropertyTypes escherPropertyTypes249 = new EscherPropertyTypes("THREEDSTYLE__FILLZ", 248, 729, "3dstyle.fillz");
        THREEDSTYLE__FILLZ = escherPropertyTypes249;
        EscherPropertyTypes escherPropertyTypes250 = new EscherPropertyTypes("THREEDSTYLE__FILLINTENSITY", 249, 730, "3dstyle.fillintensity");
        THREEDSTYLE__FILLINTENSITY = escherPropertyTypes250;
        EscherPropertyTypes escherPropertyTypes251 = new EscherPropertyTypes("THREEDSTYLE__CONSTRAINROTATION", 250, 763, "3dstyle.constrainrotation");
        THREEDSTYLE__CONSTRAINROTATION = escherPropertyTypes251;
        EscherPropertyTypes escherPropertyTypes252 = new EscherPropertyTypes("THREEDSTYLE__ROTATIONCENTERAUTO", 251, 764, "3dstyle.rotationcenterauto");
        THREEDSTYLE__ROTATIONCENTERAUTO = escherPropertyTypes252;
        EscherPropertyTypes escherPropertyTypes253 = new EscherPropertyTypes("THREEDSTYLE__PARALLEL", 252, 765, "3dstyle.parallel");
        THREEDSTYLE__PARALLEL = escherPropertyTypes253;
        EscherPropertyTypes escherPropertyTypes254 = new EscherPropertyTypes("THREEDSTYLE__KEYHARSH", 253, 766, "3dstyle.keyharsh");
        THREEDSTYLE__KEYHARSH = escherPropertyTypes254;
        EscherPropertyTypes escherPropertyTypes255 = new EscherPropertyTypes("THREEDSTYLE__FILLHARSH", 254, 767, "3dstyle.fillharsh");
        THREEDSTYLE__FILLHARSH = escherPropertyTypes255;
        EscherPropertyTypes escherPropertyTypes256 = new EscherPropertyTypes("SHAPE__MASTER", 255, 769, "shape.master");
        SHAPE__MASTER = escherPropertyTypes256;
        EscherPropertyTypes escherPropertyTypes257 = new EscherPropertyTypes("SHAPE__CONNECTORSTYLE", 256, 771, "shape.connectorstyle");
        SHAPE__CONNECTORSTYLE = escherPropertyTypes257;
        EscherPropertyTypes escherPropertyTypes258 = new EscherPropertyTypes("SHAPE__BLACKANDWHITESETTINGS", 257, 772, "shape.blackandwhitesettings");
        SHAPE__BLACKANDWHITESETTINGS = escherPropertyTypes258;
        EscherPropertyTypes escherPropertyTypes259 = new EscherPropertyTypes("SHAPE__WMODEPUREBW", 258, 773, "shape.wmodepurebw");
        SHAPE__WMODEPUREBW = escherPropertyTypes259;
        EscherPropertyTypes escherPropertyTypes260 = new EscherPropertyTypes("SHAPE__WMODEBW", 259, 774, "shape.wmodebw");
        SHAPE__WMODEBW = escherPropertyTypes260;
        EscherPropertyTypes escherPropertyTypes261 = new EscherPropertyTypes("SHAPE__OLEICON", 260, 826, "shape.oleicon");
        SHAPE__OLEICON = escherPropertyTypes261;
        EscherPropertyTypes escherPropertyTypes262 = new EscherPropertyTypes("SHAPE__PREFERRELATIVERESIZE", 261, 827, "shape.preferrelativeresize");
        SHAPE__PREFERRELATIVERESIZE = escherPropertyTypes262;
        EscherPropertyTypes escherPropertyTypes263 = new EscherPropertyTypes("SHAPE__LOCKSHAPETYPE", 262, 828, "shape.lockshapetype");
        SHAPE__LOCKSHAPETYPE = escherPropertyTypes263;
        EscherPropertyTypes escherPropertyTypes264 = new EscherPropertyTypes("SHAPE__DELETEATTACHEDOBJECT", 263, 830, "shape.deleteattachedobject");
        SHAPE__DELETEATTACHEDOBJECT = escherPropertyTypes264;
        EscherPropertyTypes escherPropertyTypes265 = new EscherPropertyTypes("SHAPE__BACKGROUNDSHAPE", 264, 831, "shape.backgroundshape");
        SHAPE__BACKGROUNDSHAPE = escherPropertyTypes265;
        EscherPropertyTypes escherPropertyTypes266 = new EscherPropertyTypes("CALLOUT__CALLOUTTYPE", 265, 832, "callout.callouttype");
        CALLOUT__CALLOUTTYPE = escherPropertyTypes266;
        EscherPropertyTypes escherPropertyTypes267 = new EscherPropertyTypes("CALLOUT__XYCALLOUTGAP", 266, 833, "callout.xycalloutgap");
        CALLOUT__XYCALLOUTGAP = escherPropertyTypes267;
        EscherPropertyTypes escherPropertyTypes268 = new EscherPropertyTypes("CALLOUT__CALLOUTANGLE", 267, 834, "callout.calloutangle");
        CALLOUT__CALLOUTANGLE = escherPropertyTypes268;
        EscherPropertyTypes escherPropertyTypes269 = new EscherPropertyTypes("CALLOUT__CALLOUTDROPTYPE", 268, 835, "callout.calloutdroptype");
        CALLOUT__CALLOUTDROPTYPE = escherPropertyTypes269;
        EscherPropertyTypes escherPropertyTypes270 = new EscherPropertyTypes("CALLOUT__CALLOUTDROPSPECIFIED", 269, 836, "callout.calloutdropspecified");
        CALLOUT__CALLOUTDROPSPECIFIED = escherPropertyTypes270;
        EscherPropertyTypes escherPropertyTypes271 = new EscherPropertyTypes("CALLOUT__CALLOUTLENGTHSPECIFIED", 270, 837, "callout.calloutlengthspecified");
        CALLOUT__CALLOUTLENGTHSPECIFIED = escherPropertyTypes271;
        EscherPropertyTypes escherPropertyTypes272 = new EscherPropertyTypes("CALLOUT__ISCALLOUT", 271, 889, "callout.iscallout");
        CALLOUT__ISCALLOUT = escherPropertyTypes272;
        EscherPropertyTypes escherPropertyTypes273 = new EscherPropertyTypes("CALLOUT__CALLOUTACCENTBAR", 272, 890, "callout.calloutaccentbar");
        CALLOUT__CALLOUTACCENTBAR = escherPropertyTypes273;
        EscherPropertyTypes escherPropertyTypes274 = new EscherPropertyTypes("CALLOUT__CALLOUTTEXTBORDER", 273, 891, "callout.callouttextborder");
        CALLOUT__CALLOUTTEXTBORDER = escherPropertyTypes274;
        EscherPropertyTypes escherPropertyTypes275 = new EscherPropertyTypes("CALLOUT__CALLOUTMINUSX", 274, 892, "callout.calloutminusx");
        CALLOUT__CALLOUTMINUSX = escherPropertyTypes275;
        EscherPropertyTypes escherPropertyTypes276 = new EscherPropertyTypes("CALLOUT__CALLOUTMINUSY", 275, 893, "callout.calloutminusy");
        CALLOUT__CALLOUTMINUSY = escherPropertyTypes276;
        EscherPropertyTypes escherPropertyTypes277 = new EscherPropertyTypes("CALLOUT__DROPAUTO", 276, 894, "callout.dropauto");
        CALLOUT__DROPAUTO = escherPropertyTypes277;
        EscherPropertyTypes escherPropertyTypes278 = new EscherPropertyTypes("CALLOUT__LENGTHSPECIFIED", 277, 895, "callout.lengthspecified");
        CALLOUT__LENGTHSPECIFIED = escherPropertyTypes278;
        EscherPropertyTypes escherPropertyTypes279 = new EscherPropertyTypes("GROUPSHAPE__SHAPENAME", 278, 896, "groupshape.shapename");
        GROUPSHAPE__SHAPENAME = escherPropertyTypes279;
        EscherPropertyTypes escherPropertyTypes280 = new EscherPropertyTypes("GROUPSHAPE__DESCRIPTION", 279, 897, "groupshape.description");
        GROUPSHAPE__DESCRIPTION = escherPropertyTypes280;
        EscherPropertyTypes escherPropertyTypes281 = new EscherPropertyTypes("GROUPSHAPE__HYPERLINK", 280, 898, "groupshape.hyperlink");
        GROUPSHAPE__HYPERLINK = escherPropertyTypes281;
        EscherPropertyTypes escherPropertyTypes282 = new EscherPropertyTypes("GROUPSHAPE__WRAPPOLYGONVERTICES", 281, 899, "groupshape.wrappolygonvertices", escherPropertyTypesHolder2);
        GROUPSHAPE__WRAPPOLYGONVERTICES = escherPropertyTypes282;
        EscherPropertyTypes escherPropertyTypes283 = new EscherPropertyTypes("GROUPSHAPE__WRAPDISTLEFT", 282, 900, "groupshape.wrapdistleft");
        GROUPSHAPE__WRAPDISTLEFT = escherPropertyTypes283;
        EscherPropertyTypes escherPropertyTypes284 = new EscherPropertyTypes("GROUPSHAPE__WRAPDISTTOP", 283, TypedValues.Custom.TYPE_FLOAT, "groupshape.wrapdisttop");
        GROUPSHAPE__WRAPDISTTOP = escherPropertyTypes284;
        EscherPropertyTypes escherPropertyTypes285 = new EscherPropertyTypes("GROUPSHAPE__WRAPDISTRIGHT", 284, TypedValues.Custom.TYPE_COLOR, "groupshape.wrapdistright");
        GROUPSHAPE__WRAPDISTRIGHT = escherPropertyTypes285;
        EscherPropertyTypes escherPropertyTypes286 = new EscherPropertyTypes("GROUPSHAPE__WRAPDISTBOTTOM", 285, TypedValues.Custom.TYPE_STRING, "groupshape.wrapdistbottom");
        GROUPSHAPE__WRAPDISTBOTTOM = escherPropertyTypes286;
        EscherPropertyTypes escherPropertyTypes287 = new EscherPropertyTypes("GROUPSHAPE__REGROUPID", 286, TypedValues.Custom.TYPE_BOOLEAN, "groupshape.regroupid");
        GROUPSHAPE__REGROUPID = escherPropertyTypes287;
        EscherPropertyTypes escherPropertyTypes288 = new EscherPropertyTypes("GROUPSHAPE__UNUSED906", 287, TypedValues.Custom.TYPE_REFERENCE, "unused906");
        GROUPSHAPE__UNUSED906 = escherPropertyTypes288;
        EscherPropertyTypes escherPropertyTypes289 = new EscherPropertyTypes("GROUPSHAPE__TOOLTIP", 288, 909, "groupshape.wzTooltip");
        GROUPSHAPE__TOOLTIP = escherPropertyTypes289;
        EscherPropertyTypes escherPropertyTypes290 = new EscherPropertyTypes("GROUPSHAPE__SCRIPT", 289, Videoio.CAP_OPENNI_ASUS, "groupshape.wzScript");
        GROUPSHAPE__SCRIPT = escherPropertyTypes290;
        EscherPropertyTypes escherPropertyTypes291 = new EscherPropertyTypes("GROUPSHAPE__POSH", 290, 911, "groupshape.posh");
        GROUPSHAPE__POSH = escherPropertyTypes291;
        EscherPropertyTypes escherPropertyTypes292 = new EscherPropertyTypes("GROUPSHAPE__POSRELH", 291, 912, "groupshape.posrelh");
        GROUPSHAPE__POSRELH = escherPropertyTypes292;
        EscherPropertyTypes escherPropertyTypes293 = new EscherPropertyTypes("GROUPSHAPE__POSV", 292, 913, "groupshape.posv");
        GROUPSHAPE__POSV = escherPropertyTypes293;
        EscherPropertyTypes escherPropertyTypes294 = new EscherPropertyTypes("GROUPSHAPE__POSRELV", 293, 914, "groupshape.posrelv");
        GROUPSHAPE__POSRELV = escherPropertyTypes294;
        EscherPropertyTypes escherPropertyTypes295 = new EscherPropertyTypes("GROUPSHAPE__HR_PCT", 294, 915, "groupshape.pctHR");
        GROUPSHAPE__HR_PCT = escherPropertyTypes295;
        EscherPropertyTypes escherPropertyTypes296 = new EscherPropertyTypes("GROUPSHAPE__HR_ALIGN", 295, 916, "groupshape.alignHR");
        GROUPSHAPE__HR_ALIGN = escherPropertyTypes296;
        EscherPropertyTypes escherPropertyTypes297 = new EscherPropertyTypes("GROUPSHAPE__HR_HEIGHT", 296, 917, "groupshape.dxHeightHR");
        GROUPSHAPE__HR_HEIGHT = escherPropertyTypes297;
        EscherPropertyTypes escherPropertyTypes298 = new EscherPropertyTypes("GROUPSHAPE__HR_WIDTH", 297, 918, "groupshape.dxWidthHR");
        GROUPSHAPE__HR_WIDTH = escherPropertyTypes298;
        EscherPropertyTypes escherPropertyTypes299 = new EscherPropertyTypes("GROUPSHAPE__SCRIPTEXT", 298, 919, "groupshape.wzScriptExtAttr");
        GROUPSHAPE__SCRIPTEXT = escherPropertyTypes299;
        EscherPropertyTypes escherPropertyTypes300 = new EscherPropertyTypes("GROUPSHAPE__SCRIPTLANG", 299, 920, "groupshape.scriptLang");
        GROUPSHAPE__SCRIPTLANG = escherPropertyTypes300;
        EscherPropertyTypes escherPropertyTypes301 = new EscherPropertyTypes("GROUPSHAPE__BORDERTOPCOLOR", 300, 923, "groupshape.borderTopColor");
        GROUPSHAPE__BORDERTOPCOLOR = escherPropertyTypes301;
        EscherPropertyTypes escherPropertyTypes302 = new EscherPropertyTypes("GROUPSHAPE__BORDERLEFTCOLOR", 301, 924, "groupshape.borderLeftColor");
        GROUPSHAPE__BORDERLEFTCOLOR = escherPropertyTypes302;
        EscherPropertyTypes escherPropertyTypes303 = new EscherPropertyTypes("GROUPSHAPE__BORDERBOTTOMCOLOR", 302, 925, "groupshape.borderBottomColor");
        GROUPSHAPE__BORDERBOTTOMCOLOR = escherPropertyTypes303;
        EscherPropertyTypes escherPropertyTypes304 = new EscherPropertyTypes("GROUPSHAPE__BORDERRIGHTCOLOR", 303, 926, "groupshape.borderRightColor");
        GROUPSHAPE__BORDERRIGHTCOLOR = escherPropertyTypes304;
        EscherPropertyTypes escherPropertyTypes305 = new EscherPropertyTypes("GROUPSHAPE__TABLEPROPERTIES", 304, 927, "groupshape.tableProperties");
        GROUPSHAPE__TABLEPROPERTIES = escherPropertyTypes305;
        EscherPropertyTypes escherPropertyTypes306 = new EscherPropertyTypes("GROUPSHAPE__TABLEROWPROPERTIES", 305, PDF417Common.MAX_CODEWORDS_IN_BARCODE, "groupshape.tableRowProperties", escherPropertyTypesHolder2);
        GROUPSHAPE__TABLEROWPROPERTIES = escherPropertyTypes306;
        EscherPropertyTypes escherPropertyTypes307 = new EscherPropertyTypes("GROUPSHAPE__WEBBOT", 306, 933, "groupshape.wzWebBot");
        GROUPSHAPE__WEBBOT = escherPropertyTypes307;
        EscherPropertyTypes escherPropertyTypes308 = new EscherPropertyTypes("GROUPSHAPE__METROBLOB", 307, 937, "groupshape.metroBlob");
        GROUPSHAPE__METROBLOB = escherPropertyTypes308;
        EscherPropertyTypes escherPropertyTypes309 = new EscherPropertyTypes("GROUPSHAPE__ZORDER", 308, 938, "groupshape.dhgt");
        GROUPSHAPE__ZORDER = escherPropertyTypes309;
        EscherPropertyTypes escherPropertyTypes310 = new EscherPropertyTypes("GROUPSHAPE__EDITEDWRAP", 309, 953, "groupshape.editedwrap");
        GROUPSHAPE__EDITEDWRAP = escherPropertyTypes310;
        EscherPropertyTypes escherPropertyTypes311 = new EscherPropertyTypes("GROUPSHAPE__BEHINDDOCUMENT", 310, 954, "groupshape.behinddocument");
        GROUPSHAPE__BEHINDDOCUMENT = escherPropertyTypes311;
        EscherPropertyTypes escherPropertyTypes312 = new EscherPropertyTypes("GROUPSHAPE__ONDBLCLICKNOTIFY", 311, 955, "groupshape.ondblclicknotify");
        GROUPSHAPE__ONDBLCLICKNOTIFY = escherPropertyTypes312;
        EscherPropertyTypes escherPropertyTypes313 = new EscherPropertyTypes("GROUPSHAPE__ISBUTTON", 312, 956, "groupshape.isbutton");
        GROUPSHAPE__ISBUTTON = escherPropertyTypes313;
        EscherPropertyTypes escherPropertyTypes314 = new EscherPropertyTypes("GROUPSHAPE__1DADJUSTMENT", 313, 957, "groupshape.1dadjustment");
        GROUPSHAPE__1DADJUSTMENT = escherPropertyTypes314;
        EscherPropertyTypes escherPropertyTypes315 = new EscherPropertyTypes("GROUPSHAPE__HIDDEN", 314, 958, "groupshape.hidden");
        GROUPSHAPE__HIDDEN = escherPropertyTypes315;
        EscherPropertyTypes escherPropertyTypes316 = new EscherPropertyTypes("GROUPSHAPE__FLAGS", 315, 959, "groupshape.groupShapeBooleanProperties");
        GROUPSHAPE__FLAGS = escherPropertyTypes316;
        EscherPropertyTypes escherPropertyTypes317 = new EscherPropertyTypes("UNKNOWN", 316, 65535, EnvironmentCompat.MEDIA_UNKNOWN);
        UNKNOWN = escherPropertyTypes317;
        $VALUES = new EscherPropertyTypes[]{escherPropertyTypes, escherPropertyTypes2, escherPropertyTypes3, escherPropertyTypes4, escherPropertyTypes5, escherPropertyTypes6, escherPropertyTypes7, escherPropertyTypes8, escherPropertyTypes9, escherPropertyTypes10, escherPropertyTypes11, escherPropertyTypes12, escherPropertyTypes13, escherPropertyTypes14, escherPropertyTypes15, escherPropertyTypes16, escherPropertyTypes17, escherPropertyTypes18, escherPropertyTypes19, escherPropertyTypes20, escherPropertyTypes21, escherPropertyTypes22, escherPropertyTypes23, escherPropertyTypes24, escherPropertyTypes25, escherPropertyTypes26, escherPropertyTypes27, escherPropertyTypes28, escherPropertyTypes29, escherPropertyTypes30, escherPropertyTypes31, escherPropertyTypes32, escherPropertyTypes33, escherPropertyTypes34, escherPropertyTypes35, escherPropertyTypes36, escherPropertyTypes37, escherPropertyTypes38, escherPropertyTypes39, escherPropertyTypes40, escherPropertyTypes41, escherPropertyTypes42, escherPropertyTypes43, escherPropertyTypes44, escherPropertyTypes45, escherPropertyTypes46, escherPropertyTypes47, escherPropertyTypes48, escherPropertyTypes49, escherPropertyTypes50, escherPropertyTypes51, escherPropertyTypes52, escherPropertyTypes53, escherPropertyTypes54, escherPropertyTypes55, escherPropertyTypes56, escherPropertyTypes57, escherPropertyTypes58, escherPropertyTypes59, escherPropertyTypes60, escherPropertyTypes61, escherPropertyTypes62, escherPropertyTypes63, escherPropertyTypes64, escherPropertyTypes65, escherPropertyTypes66, escherPropertyTypes67, escherPropertyTypes68, escherPropertyTypes69, escherPropertyTypes70, escherPropertyTypes71, escherPropertyTypes72, escherPropertyTypes73, escherPropertyTypes74, escherPropertyTypes75, escherPropertyTypes76, escherPropertyTypes77, escherPropertyTypes78, escherPropertyTypes79, escherPropertyTypes80, escherPropertyTypes81, escherPropertyTypes82, escherPropertyTypes83, escherPropertyTypes84, escherPropertyTypes85, escherPropertyTypes86, escherPropertyTypes87, escherPropertyTypes88, escherPropertyTypes89, escherPropertyTypes90, escherPropertyTypes91, escherPropertyTypes92, escherPropertyTypes93, escherPropertyTypes94, escherPropertyTypes95, escherPropertyTypes96, escherPropertyTypes97, escherPropertyTypes98, escherPropertyTypes99, escherPropertyTypes100, escherPropertyTypes101, escherPropertyTypes102, escherPropertyTypes103, escherPropertyTypes104, escherPropertyTypes105, escherPropertyTypes106, escherPropertyTypes107, escherPropertyTypes108, escherPropertyTypes109, escherPropertyTypes110, escherPropertyTypes111, escherPropertyTypes112, escherPropertyTypes113, escherPropertyTypes114, escherPropertyTypes115, escherPropertyTypes116, escherPropertyTypes117, escherPropertyTypes118, escherPropertyTypes119, escherPropertyTypes120, escherPropertyTypes121, escherPropertyTypes122, escherPropertyTypes123, escherPropertyTypes124, escherPropertyTypes125, escherPropertyTypes126, escherPropertyTypes127, escherPropertyTypes128, escherPropertyTypes129, escherPropertyTypes130, escherPropertyTypes131, escherPropertyTypes132, escherPropertyTypes133, escherPropertyTypes134, escherPropertyTypes135, escherPropertyTypes136, escherPropertyTypes137, escherPropertyTypes138, escherPropertyTypes139, escherPropertyTypes140, escherPropertyTypes141, escherPropertyTypes142, escherPropertyTypes143, escherPropertyTypes144, escherPropertyTypes145, escherPropertyTypes146, escherPropertyTypes147, escherPropertyTypes148, escherPropertyTypes149, escherPropertyTypes150, escherPropertyTypes151, escherPropertyTypes152, escherPropertyTypes153, escherPropertyTypes154, escherPropertyTypes155, escherPropertyTypes156, escherPropertyTypes157, escherPropertyTypes158, escherPropertyTypes159, escherPropertyTypes160, escherPropertyTypes161, escherPropertyTypes162, escherPropertyTypes163, escherPropertyTypes164, escherPropertyTypes165, escherPropertyTypes166, escherPropertyTypes167, escherPropertyTypes168, escherPropertyTypes169, escherPropertyTypes170, escherPropertyTypes171, escherPropertyTypes172, escherPropertyTypes173, escherPropertyTypes174, escherPropertyTypes175, escherPropertyTypes176, escherPropertyTypes177, escherPropertyTypes178, escherPropertyTypes179, escherPropertyTypes180, escherPropertyTypes181, escherPropertyTypes182, escherPropertyTypes183, escherPropertyTypes184, escherPropertyTypes185, escherPropertyTypes186, escherPropertyTypes187, escherPropertyTypes188, escherPropertyTypes189, escherPropertyTypes190, escherPropertyTypes191, escherPropertyTypes192, escherPropertyTypes193, escherPropertyTypes194, escherPropertyTypes195, escherPropertyTypes196, escherPropertyTypes197, escherPropertyTypes198, escherPropertyTypes199, escherPropertyTypes200, escherPropertyTypes201, escherPropertyTypes202, escherPropertyTypes203, escherPropertyTypes204, escherPropertyTypes205, escherPropertyTypes206, escherPropertyTypes207, escherPropertyTypes208, escherPropertyTypes209, escherPropertyTypes210, escherPropertyTypes211, escherPropertyTypes212, escherPropertyTypes213, escherPropertyTypes214, escherPropertyTypes215, escherPropertyTypes216, escherPropertyTypes217, escherPropertyTypes218, escherPropertyTypes219, escherPropertyTypes220, escherPropertyTypes221, escherPropertyTypes222, escherPropertyTypes223, escherPropertyTypes224, escherPropertyTypes225, escherPropertyTypes226, escherPropertyTypes227, escherPropertyTypes228, escherPropertyTypes229, escherPropertyTypes230, escherPropertyTypes231, escherPropertyTypes232, escherPropertyTypes233, escherPropertyTypes234, escherPropertyTypes235, escherPropertyTypes236, escherPropertyTypes237, escherPropertyTypes238, escherPropertyTypes239, escherPropertyTypes240, escherPropertyTypes241, escherPropertyTypes242, escherPropertyTypes243, escherPropertyTypes244, escherPropertyTypes245, escherPropertyTypes246, escherPropertyTypes247, escherPropertyTypes248, escherPropertyTypes249, escherPropertyTypes250, escherPropertyTypes251, escherPropertyTypes252, escherPropertyTypes253, escherPropertyTypes254, escherPropertyTypes255, escherPropertyTypes256, escherPropertyTypes257, escherPropertyTypes258, escherPropertyTypes259, escherPropertyTypes260, escherPropertyTypes261, escherPropertyTypes262, escherPropertyTypes263, escherPropertyTypes264, escherPropertyTypes265, escherPropertyTypes266, escherPropertyTypes267, escherPropertyTypes268, escherPropertyTypes269, escherPropertyTypes270, escherPropertyTypes271, escherPropertyTypes272, escherPropertyTypes273, escherPropertyTypes274, escherPropertyTypes275, escherPropertyTypes276, escherPropertyTypes277, escherPropertyTypes278, escherPropertyTypes279, escherPropertyTypes280, escherPropertyTypes281, escherPropertyTypes282, escherPropertyTypes283, escherPropertyTypes284, escherPropertyTypes285, escherPropertyTypes286, escherPropertyTypes287, escherPropertyTypes288, escherPropertyTypes289, escherPropertyTypes290, escherPropertyTypes291, escherPropertyTypes292, escherPropertyTypes293, escherPropertyTypes294, escherPropertyTypes295, escherPropertyTypes296, escherPropertyTypes297, escherPropertyTypes298, escherPropertyTypes299, escherPropertyTypes300, escherPropertyTypes301, escherPropertyTypes302, escherPropertyTypes303, escherPropertyTypes304, escherPropertyTypes305, escherPropertyTypes306, escherPropertyTypes307, escherPropertyTypes308, escherPropertyTypes309, escherPropertyTypes310, escherPropertyTypes311, escherPropertyTypes312, escherPropertyTypes313, escherPropertyTypes314, escherPropertyTypes315, escherPropertyTypes316, escherPropertyTypes317};
        LOOKUP = (Map) Stream.of((Object[]) values()).collect(Collectors.toMap(new com.google.android.material.color.utilities.g(12), Function.identity()));
    }

    private EscherPropertyTypes(String str, int i5, int i6, String str2) {
        this(str, i5, i6, str2, EscherPropertyTypesHolder.UNKNOWN);
    }

    public static EscherPropertyTypes forPropertyID(int i5) {
        EscherPropertyTypes escherPropertyTypes = LOOKUP.get(Short.valueOf((short) (i5 & 16383)));
        return escherPropertyTypes != null ? escherPropertyTypes : UNKNOWN;
    }

    public static EscherPropertyTypes valueOf(String str) {
        return (EscherPropertyTypes) Enum.valueOf(EscherPropertyTypes.class, str);
    }

    public static EscherPropertyTypes[] values() {
        return (EscherPropertyTypes[]) $VALUES.clone();
    }

    public short getPropertyId() {
        return this.propNumber;
    }

    private EscherPropertyTypes(String str, int i5, int i6, String str2, EscherPropertyTypesHolder escherPropertyTypesHolder) {
        super(str, i5);
        this.propNumber = (short) i6;
        this.propName = str2;
        this.holder = escherPropertyTypesHolder;
    }
}
