package org.apache.poi.xddf.usermodel;

import java.util.HashMap;
import org.openxmlformats.schemas.drawingml.x2006.main.STShapeType;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'DARK_BLUE' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:485)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByRegister(EnumVisitor.java:422)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:351)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:284)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:153)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:102)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes4.dex */
public final class PresetGeometry {
    private static final /* synthetic */ PresetGeometry[] $VALUES;
    public static final PresetGeometry ACCENT_BORDER_CALLOUT_1;
    public static final PresetGeometry ACCENT_BORDER_CALLOUT_2;
    public static final PresetGeometry ACCENT_BORDER_CALLOUT_3;
    public static final PresetGeometry ACCENT_CALLOUT_1;
    public static final PresetGeometry ACCENT_CALLOUT_2;
    public static final PresetGeometry ACCENT_CALLOUT_3;
    public static final PresetGeometry ACTION_BUTTON_BACK_PREVIOUS;
    public static final PresetGeometry ACTION_BUTTON_BEGINNING;
    public static final PresetGeometry ACTION_BUTTON_BLANK;
    public static final PresetGeometry ACTION_BUTTON_DOCUMENT;
    public static final PresetGeometry ACTION_BUTTON_END;
    public static final PresetGeometry ACTION_BUTTON_FORWARD_NEXT;
    public static final PresetGeometry ACTION_BUTTON_HELP;
    public static final PresetGeometry ACTION_BUTTON_HOME;
    public static final PresetGeometry ACTION_BUTTON_INFORMATION;
    public static final PresetGeometry ACTION_BUTTON_MOVIE;
    public static final PresetGeometry ACTION_BUTTON_RETURN;
    public static final PresetGeometry ACTION_BUTTON_SOUND;
    public static final PresetGeometry ARC;
    public static final PresetGeometry BENT_ARROW;
    public static final PresetGeometry BENT_CONNECTOR_2;
    public static final PresetGeometry BENT_CONNECTOR_3;
    public static final PresetGeometry BENT_CONNECTOR_4;
    public static final PresetGeometry BENT_CONNECTOR_5;
    public static final PresetGeometry BENT_UP_ARROW;
    public static final PresetGeometry BEVEL;
    public static final PresetGeometry BLOCK_ARC;
    public static final PresetGeometry BORDER_CALLOUT_1;
    public static final PresetGeometry BORDER_CALLOUT_2;
    public static final PresetGeometry BORDER_CALLOUT_3;
    public static final PresetGeometry BRACE_PAIR;
    public static final PresetGeometry BRACKET_PAIR;
    public static final PresetGeometry CALLOUT_1;
    public static final PresetGeometry CALLOUT_2;
    public static final PresetGeometry CALLOUT_3;
    public static final PresetGeometry CAN;
    public static final PresetGeometry CHART_PLUS;
    public static final PresetGeometry CHART_STAR;
    public static final PresetGeometry CHART_X;
    public static final PresetGeometry CHEVRON;
    public static final PresetGeometry CHORD;
    public static final PresetGeometry CIRCULAR_ARROW;
    public static final PresetGeometry CLOUD;
    public static final PresetGeometry CLOUD_CALLOUT;
    public static final PresetGeometry CORNER;
    public static final PresetGeometry CORNER_TABS;
    public static final PresetGeometry CUBE;
    public static final PresetGeometry CURVED_CONNECTOR_2;
    public static final PresetGeometry CURVED_CONNECTOR_3;
    public static final PresetGeometry CURVED_CONNECTOR_4;
    public static final PresetGeometry CURVED_CONNECTOR_5;
    public static final PresetGeometry CURVED_DOWN_ARROW;
    public static final PresetGeometry CURVED_LEFT_ARROW;
    public static final PresetGeometry CURVED_RIGHT_ARROW;
    public static final PresetGeometry CURVED_UP_ARROW;
    public static final PresetGeometry DARK_BLUE;
    public static final PresetGeometry DECAGON;
    public static final PresetGeometry DIAGONAL_STRIPE;
    public static final PresetGeometry DIAMOND;
    public static final PresetGeometry DODECAGON;
    public static final PresetGeometry DONUT;
    public static final PresetGeometry DOUBLE_WAVE;
    public static final PresetGeometry DOWN_ARROW;
    public static final PresetGeometry DOWN_ARROW_CALLOUT;
    public static final PresetGeometry ELLIPSE;
    public static final PresetGeometry ELLIPSE_RIBBON;
    public static final PresetGeometry ELLIPSE_RIBBON_2;
    public static final PresetGeometry FLOW_CHART_ALTERNATE_PROCESS;
    public static final PresetGeometry FLOW_CHART_COLLATE;
    public static final PresetGeometry FLOW_CHART_CONNECTOR;
    public static final PresetGeometry FLOW_CHART_DECISION;
    public static final PresetGeometry FLOW_CHART_DELAY;
    public static final PresetGeometry FLOW_CHART_DISPLAY;
    public static final PresetGeometry FLOW_CHART_DOCUMENT;
    public static final PresetGeometry FLOW_CHART_EXTRACT;
    public static final PresetGeometry FLOW_CHART_INPUT_OUTPUT;
    public static final PresetGeometry FLOW_CHART_INTERNAL_STORAGE;
    public static final PresetGeometry FLOW_CHART_MAGNETIC_DISK;
    public static final PresetGeometry FLOW_CHART_MAGNETIC_DRUM;
    public static final PresetGeometry FLOW_CHART_MAGNETIC_TAPE;
    public static final PresetGeometry FLOW_CHART_MANUAL_INPUT;
    public static final PresetGeometry FLOW_CHART_MANUAL_OPERATION;
    public static final PresetGeometry FLOW_CHART_MERGE;
    public static final PresetGeometry FLOW_CHART_MULTIDOCUMENT;
    public static final PresetGeometry FLOW_CHART_OFFLINE_STORAGE;
    public static final PresetGeometry FLOW_CHART_OFFPAGE_CONNECTOR;
    public static final PresetGeometry FLOW_CHART_ONLINE_STORAGE;
    public static final PresetGeometry FLOW_CHART_OR;
    public static final PresetGeometry FLOW_CHART_PREDEFINED_PROCESS;
    public static final PresetGeometry FLOW_CHART_PREPARATION;
    public static final PresetGeometry FLOW_CHART_PROCESS;
    public static final PresetGeometry FLOW_CHART_PUNCHED_CARD;
    public static final PresetGeometry FLOW_CHART_PUNCHED_TAPE;
    public static final PresetGeometry FLOW_CHART_SORT;
    public static final PresetGeometry FLOW_CHART_SUMMING_JUNCTION;
    public static final PresetGeometry FLOW_CHART_TERMINATOR;
    public static final PresetGeometry FOLDED_CORNER;
    public static final PresetGeometry FRAME;
    public static final PresetGeometry FUNNEL;
    public static final PresetGeometry GEAR_6;
    public static final PresetGeometry GEAR_9;
    public static final PresetGeometry HALF_FRAME;
    public static final PresetGeometry HEART;
    public static final PresetGeometry HEPTAGON;
    public static final PresetGeometry HEXAGON;
    public static final PresetGeometry HOME_PLATE;
    public static final PresetGeometry HORIZONTAL_SCROLL;
    public static final PresetGeometry IRREGULAR_SEAL_1;
    public static final PresetGeometry IRREGULAR_SEAL_2;
    public static final PresetGeometry LEFT_ARROW;
    public static final PresetGeometry LEFT_ARROW_CALLOUT;
    public static final PresetGeometry LEFT_BRACE;
    public static final PresetGeometry LEFT_BRACKET;
    public static final PresetGeometry LEFT_CIRCULAR_ARROW;
    public static final PresetGeometry LEFT_RIGHT_ARROW;
    public static final PresetGeometry LEFT_RIGHT_ARROW_CALLOUT;
    public static final PresetGeometry LEFT_RIGHT_CIRCULAR_ARROW;
    public static final PresetGeometry LEFT_RIGHT_RIBBON;
    public static final PresetGeometry LEFT_RIGHT_UP_ARROW;
    public static final PresetGeometry LEFT_UP_ARROW;
    public static final PresetGeometry LIGHTNING_BOLT;
    public static final PresetGeometry LINE;
    public static final PresetGeometry LINE_INVERTED;
    public static final PresetGeometry MATH_DIVIDE;
    public static final PresetGeometry MATH_EQUAL;
    public static final PresetGeometry MATH_MINUS;
    public static final PresetGeometry MATH_MULTIPLY;
    public static final PresetGeometry MATH_NOT_EQUAL;
    public static final PresetGeometry MATH_PLUS;
    public static final PresetGeometry MOON;
    public static final PresetGeometry NON_ISOSCELES_TRAPEZOID;
    public static final PresetGeometry NOTCHED_RIGHT_ARROW;
    public static final PresetGeometry NO_SMOKING;
    public static final PresetGeometry OCTAGON;
    public static final PresetGeometry PARALLELOGRAM;
    public static final PresetGeometry PENTAGON;
    public static final PresetGeometry PIE;
    public static final PresetGeometry PIE_WEDGE;
    public static final PresetGeometry PLAQUE;
    public static final PresetGeometry PLAQUE_TABS;
    public static final PresetGeometry PLUS;
    public static final PresetGeometry QUAD_ARROW;
    public static final PresetGeometry QUAD_ARROW_CALLOUT;
    public static final PresetGeometry RECTANGLE;
    public static final PresetGeometry RIBBON;
    public static final PresetGeometry RIBBON_2;
    public static final PresetGeometry RIGHT_ARROW;
    public static final PresetGeometry RIGHT_ARROW_CALLOUT;
    public static final PresetGeometry RIGHT_BRACE;
    public static final PresetGeometry RIGHT_BRACKET;
    public static final PresetGeometry RIGHT_TRIANGLE;
    public static final PresetGeometry ROUND_RECTANGLE;
    public static final PresetGeometry ROUND_RECTANGLE_1_CORNER;
    public static final PresetGeometry ROUND_RECTANGLE_2_DIAGONAL_CORNERS;
    public static final PresetGeometry ROUND_RECTANGLE_2_SAME_SIDE_CORNERS;
    public static final PresetGeometry SMILEY_FACE;
    public static final PresetGeometry SNIP_RECTANGLE_1_CORNER;
    public static final PresetGeometry SNIP_RECTANGLE_2_DIAGONAL_CORNERS;
    public static final PresetGeometry SNIP_RECTANGLE_2_SAME_SIDE_CORNERS;
    public static final PresetGeometry SNIP_ROUND_RECTANGLE;
    public static final PresetGeometry SQUARE_TABS;
    public static final PresetGeometry STAR_10;
    public static final PresetGeometry STAR_12;
    public static final PresetGeometry STAR_16;
    public static final PresetGeometry STAR_24;
    public static final PresetGeometry STAR_32;
    public static final PresetGeometry STAR_4;
    public static final PresetGeometry STAR_5;
    public static final PresetGeometry STAR_6;
    public static final PresetGeometry STAR_7;
    public static final PresetGeometry STAR_8;
    public static final PresetGeometry STRAIGHT_CONNECTOR;
    public static final PresetGeometry STRIPED_RIGHT_ARROW;
    public static final PresetGeometry SUN;
    public static final PresetGeometry SWOOSH_ARROW;
    public static final PresetGeometry TEARDROP;
    public static final PresetGeometry TRAPEZOID;
    public static final PresetGeometry TRIANGLE;
    public static final PresetGeometry UP_ARROW;
    public static final PresetGeometry UP_ARROW_CALLOUT;
    public static final PresetGeometry UP_DOWN_ARROW;
    public static final PresetGeometry UP_DOWN_ARROW_CALLOUT;
    public static final PresetGeometry UTURN_ARROW;
    public static final PresetGeometry VERTICAL_SCROLL;
    public static final PresetGeometry WAVE;
    public static final PresetGeometry WEDGE_ELLIPSE_CALLOUT;
    public static final PresetGeometry WEDGE_RECTANGLE_CALLOUT;
    public static final PresetGeometry WEDGE_ROUND_RECTANGLE_CALLOUT;
    private static final HashMap<STShapeType.Enum, PresetGeometry> reverse;
    final STShapeType.Enum underlying;

    static {
        PresetGeometry presetGeometry = new PresetGeometry("ACCENT_BORDER_CALLOUT_1", 0, STShapeType.ACCENT_BORDER_CALLOUT_1);
        ACCENT_BORDER_CALLOUT_1 = presetGeometry;
        PresetGeometry presetGeometry2 = new PresetGeometry("ACCENT_BORDER_CALLOUT_2", 1, STShapeType.ACCENT_BORDER_CALLOUT_2);
        ACCENT_BORDER_CALLOUT_2 = presetGeometry2;
        PresetGeometry presetGeometry3 = new PresetGeometry("ACCENT_BORDER_CALLOUT_3", 2, STShapeType.ACCENT_BORDER_CALLOUT_3);
        ACCENT_BORDER_CALLOUT_3 = presetGeometry3;
        PresetGeometry presetGeometry4 = new PresetGeometry("ACCENT_CALLOUT_1", 3, STShapeType.ACCENT_CALLOUT_1);
        ACCENT_CALLOUT_1 = presetGeometry4;
        PresetGeometry presetGeometry5 = new PresetGeometry("ACCENT_CALLOUT_2", 4, STShapeType.ACCENT_CALLOUT_2);
        ACCENT_CALLOUT_2 = presetGeometry5;
        PresetGeometry presetGeometry6 = new PresetGeometry("ACCENT_CALLOUT_3", 5, STShapeType.ACCENT_CALLOUT_3);
        ACCENT_CALLOUT_3 = presetGeometry6;
        PresetGeometry presetGeometry7 = new PresetGeometry("ACTION_BUTTON_BACK_PREVIOUS", 6, STShapeType.ACTION_BUTTON_BACK_PREVIOUS);
        ACTION_BUTTON_BACK_PREVIOUS = presetGeometry7;
        PresetGeometry presetGeometry8 = new PresetGeometry("ACTION_BUTTON_BEGINNING", 7, STShapeType.ACTION_BUTTON_BEGINNING);
        ACTION_BUTTON_BEGINNING = presetGeometry8;
        PresetGeometry presetGeometry9 = new PresetGeometry("ACTION_BUTTON_BLANK", 8, STShapeType.ACTION_BUTTON_BLANK);
        ACTION_BUTTON_BLANK = presetGeometry9;
        PresetGeometry presetGeometry10 = new PresetGeometry("ACTION_BUTTON_DOCUMENT", 9, STShapeType.ACTION_BUTTON_DOCUMENT);
        ACTION_BUTTON_DOCUMENT = presetGeometry10;
        PresetGeometry presetGeometry11 = new PresetGeometry("ACTION_BUTTON_END", 10, STShapeType.ACTION_BUTTON_END);
        ACTION_BUTTON_END = presetGeometry11;
        PresetGeometry presetGeometry12 = new PresetGeometry("ACTION_BUTTON_FORWARD_NEXT", 11, STShapeType.ACTION_BUTTON_FORWARD_NEXT);
        ACTION_BUTTON_FORWARD_NEXT = presetGeometry12;
        PresetGeometry presetGeometry13 = new PresetGeometry("ACTION_BUTTON_HELP", 12, STShapeType.ACTION_BUTTON_HELP);
        ACTION_BUTTON_HELP = presetGeometry13;
        PresetGeometry presetGeometry14 = new PresetGeometry("ACTION_BUTTON_HOME", 13, STShapeType.ACTION_BUTTON_HOME);
        ACTION_BUTTON_HOME = presetGeometry14;
        PresetGeometry presetGeometry15 = new PresetGeometry("ACTION_BUTTON_INFORMATION", 14, STShapeType.ACTION_BUTTON_INFORMATION);
        ACTION_BUTTON_INFORMATION = presetGeometry15;
        PresetGeometry presetGeometry16 = new PresetGeometry("ACTION_BUTTON_MOVIE", 15, STShapeType.ACTION_BUTTON_MOVIE);
        ACTION_BUTTON_MOVIE = presetGeometry16;
        PresetGeometry presetGeometry17 = new PresetGeometry("ACTION_BUTTON_RETURN", 16, STShapeType.ACTION_BUTTON_RETURN);
        ACTION_BUTTON_RETURN = presetGeometry17;
        PresetGeometry presetGeometry18 = new PresetGeometry("ACTION_BUTTON_SOUND", 17, STShapeType.ACTION_BUTTON_SOUND);
        ACTION_BUTTON_SOUND = presetGeometry18;
        PresetGeometry presetGeometry19 = new PresetGeometry("ARC", 18, STShapeType.ARC);
        ARC = presetGeometry19;
        PresetGeometry presetGeometry20 = new PresetGeometry("BENT_ARROW", 19, STShapeType.BENT_ARROW);
        BENT_ARROW = presetGeometry20;
        PresetGeometry presetGeometry21 = new PresetGeometry("BENT_CONNECTOR_2", 20, STShapeType.BENT_CONNECTOR_2);
        BENT_CONNECTOR_2 = presetGeometry21;
        PresetGeometry presetGeometry22 = new PresetGeometry("BENT_CONNECTOR_3", 21, STShapeType.BENT_CONNECTOR_3);
        BENT_CONNECTOR_3 = presetGeometry22;
        STShapeType.Enum r6 = STShapeType.BENT_CONNECTOR_4;
        PresetGeometry presetGeometry23 = new PresetGeometry("DARK_BLUE", 22, r6);
        DARK_BLUE = presetGeometry23;
        PresetGeometry presetGeometry24 = new PresetGeometry("BENT_CONNECTOR_4", 23, r6);
        BENT_CONNECTOR_4 = presetGeometry24;
        PresetGeometry presetGeometry25 = new PresetGeometry("BENT_CONNECTOR_5", 24, STShapeType.BENT_CONNECTOR_5);
        BENT_CONNECTOR_5 = presetGeometry25;
        PresetGeometry presetGeometry26 = new PresetGeometry("BENT_UP_ARROW", 25, STShapeType.BENT_UP_ARROW);
        BENT_UP_ARROW = presetGeometry26;
        PresetGeometry presetGeometry27 = new PresetGeometry("BEVEL", 26, STShapeType.BEVEL);
        BEVEL = presetGeometry27;
        PresetGeometry presetGeometry28 = new PresetGeometry("BLOCK_ARC", 27, STShapeType.BLOCK_ARC);
        BLOCK_ARC = presetGeometry28;
        PresetGeometry presetGeometry29 = new PresetGeometry("BORDER_CALLOUT_1", 28, STShapeType.BORDER_CALLOUT_1);
        BORDER_CALLOUT_1 = presetGeometry29;
        PresetGeometry presetGeometry30 = new PresetGeometry("BORDER_CALLOUT_2", 29, STShapeType.BORDER_CALLOUT_2);
        BORDER_CALLOUT_2 = presetGeometry30;
        PresetGeometry presetGeometry31 = new PresetGeometry("BORDER_CALLOUT_3", 30, STShapeType.BORDER_CALLOUT_3);
        BORDER_CALLOUT_3 = presetGeometry31;
        PresetGeometry presetGeometry32 = new PresetGeometry("BRACE_PAIR", 31, STShapeType.BRACE_PAIR);
        BRACE_PAIR = presetGeometry32;
        PresetGeometry presetGeometry33 = new PresetGeometry("BRACKET_PAIR", 32, STShapeType.BRACKET_PAIR);
        BRACKET_PAIR = presetGeometry33;
        PresetGeometry presetGeometry34 = new PresetGeometry("CALLOUT_1", 33, STShapeType.CALLOUT_1);
        CALLOUT_1 = presetGeometry34;
        PresetGeometry presetGeometry35 = new PresetGeometry("CALLOUT_2", 34, STShapeType.CALLOUT_2);
        CALLOUT_2 = presetGeometry35;
        PresetGeometry presetGeometry36 = new PresetGeometry("CALLOUT_3", 35, STShapeType.CALLOUT_3);
        CALLOUT_3 = presetGeometry36;
        PresetGeometry presetGeometry37 = new PresetGeometry("CAN", 36, STShapeType.CAN);
        CAN = presetGeometry37;
        PresetGeometry presetGeometry38 = new PresetGeometry("CHART_PLUS", 37, STShapeType.CHART_PLUS);
        CHART_PLUS = presetGeometry38;
        PresetGeometry presetGeometry39 = new PresetGeometry("CHART_STAR", 38, STShapeType.CHART_STAR);
        CHART_STAR = presetGeometry39;
        PresetGeometry presetGeometry40 = new PresetGeometry("CHART_X", 39, STShapeType.CHART_X);
        CHART_X = presetGeometry40;
        PresetGeometry presetGeometry41 = new PresetGeometry("CHEVRON", 40, STShapeType.CHEVRON);
        CHEVRON = presetGeometry41;
        PresetGeometry presetGeometry42 = new PresetGeometry("CHORD", 41, STShapeType.CHORD);
        CHORD = presetGeometry42;
        PresetGeometry presetGeometry43 = new PresetGeometry("CIRCULAR_ARROW", 42, STShapeType.CIRCULAR_ARROW);
        CIRCULAR_ARROW = presetGeometry43;
        PresetGeometry presetGeometry44 = new PresetGeometry("CLOUD", 43, STShapeType.CLOUD);
        CLOUD = presetGeometry44;
        PresetGeometry presetGeometry45 = new PresetGeometry("CLOUD_CALLOUT", 44, STShapeType.CLOUD_CALLOUT);
        CLOUD_CALLOUT = presetGeometry45;
        PresetGeometry presetGeometry46 = new PresetGeometry("CORNER", 45, STShapeType.CORNER);
        CORNER = presetGeometry46;
        PresetGeometry presetGeometry47 = new PresetGeometry("CORNER_TABS", 46, STShapeType.CORNER_TABS);
        CORNER_TABS = presetGeometry47;
        PresetGeometry presetGeometry48 = new PresetGeometry("CUBE", 47, STShapeType.CUBE);
        CUBE = presetGeometry48;
        PresetGeometry presetGeometry49 = new PresetGeometry("CURVED_CONNECTOR_2", 48, STShapeType.CURVED_CONNECTOR_2);
        CURVED_CONNECTOR_2 = presetGeometry49;
        PresetGeometry presetGeometry50 = new PresetGeometry("CURVED_CONNECTOR_3", 49, STShapeType.CURVED_CONNECTOR_3);
        CURVED_CONNECTOR_3 = presetGeometry50;
        PresetGeometry presetGeometry51 = new PresetGeometry("CURVED_CONNECTOR_4", 50, STShapeType.CURVED_CONNECTOR_4);
        CURVED_CONNECTOR_4 = presetGeometry51;
        PresetGeometry presetGeometry52 = new PresetGeometry("CURVED_CONNECTOR_5", 51, STShapeType.CURVED_CONNECTOR_5);
        CURVED_CONNECTOR_5 = presetGeometry52;
        PresetGeometry presetGeometry53 = new PresetGeometry("CURVED_DOWN_ARROW", 52, STShapeType.CURVED_DOWN_ARROW);
        CURVED_DOWN_ARROW = presetGeometry53;
        PresetGeometry presetGeometry54 = new PresetGeometry("CURVED_LEFT_ARROW", 53, STShapeType.CURVED_LEFT_ARROW);
        CURVED_LEFT_ARROW = presetGeometry54;
        PresetGeometry presetGeometry55 = new PresetGeometry("CURVED_RIGHT_ARROW", 54, STShapeType.CURVED_RIGHT_ARROW);
        CURVED_RIGHT_ARROW = presetGeometry55;
        PresetGeometry presetGeometry56 = new PresetGeometry("CURVED_UP_ARROW", 55, STShapeType.CURVED_UP_ARROW);
        CURVED_UP_ARROW = presetGeometry56;
        PresetGeometry presetGeometry57 = new PresetGeometry("DECAGON", 56, STShapeType.DECAGON);
        DECAGON = presetGeometry57;
        PresetGeometry presetGeometry58 = new PresetGeometry("DIAGONAL_STRIPE", 57, STShapeType.DIAG_STRIPE);
        DIAGONAL_STRIPE = presetGeometry58;
        PresetGeometry presetGeometry59 = new PresetGeometry("DIAMOND", 58, STShapeType.DIAMOND);
        DIAMOND = presetGeometry59;
        PresetGeometry presetGeometry60 = new PresetGeometry("DODECAGON", 59, STShapeType.DODECAGON);
        DODECAGON = presetGeometry60;
        PresetGeometry presetGeometry61 = new PresetGeometry("DONUT", 60, STShapeType.DONUT);
        DONUT = presetGeometry61;
        PresetGeometry presetGeometry62 = new PresetGeometry("DOUBLE_WAVE", 61, STShapeType.DOUBLE_WAVE);
        DOUBLE_WAVE = presetGeometry62;
        PresetGeometry presetGeometry63 = new PresetGeometry("DOWN_ARROW", 62, STShapeType.DOWN_ARROW);
        DOWN_ARROW = presetGeometry63;
        PresetGeometry presetGeometry64 = new PresetGeometry("DOWN_ARROW_CALLOUT", 63, STShapeType.DOWN_ARROW_CALLOUT);
        DOWN_ARROW_CALLOUT = presetGeometry64;
        PresetGeometry presetGeometry65 = new PresetGeometry("ELLIPSE", 64, STShapeType.ELLIPSE);
        ELLIPSE = presetGeometry65;
        PresetGeometry presetGeometry66 = new PresetGeometry("ELLIPSE_RIBBON", 65, STShapeType.ELLIPSE_RIBBON);
        ELLIPSE_RIBBON = presetGeometry66;
        PresetGeometry presetGeometry67 = new PresetGeometry("ELLIPSE_RIBBON_2", 66, STShapeType.ELLIPSE_RIBBON_2);
        ELLIPSE_RIBBON_2 = presetGeometry67;
        PresetGeometry presetGeometry68 = new PresetGeometry("FLOW_CHART_ALTERNATE_PROCESS", 67, STShapeType.FLOW_CHART_ALTERNATE_PROCESS);
        FLOW_CHART_ALTERNATE_PROCESS = presetGeometry68;
        PresetGeometry presetGeometry69 = new PresetGeometry("FLOW_CHART_COLLATE", 68, STShapeType.FLOW_CHART_COLLATE);
        FLOW_CHART_COLLATE = presetGeometry69;
        PresetGeometry presetGeometry70 = new PresetGeometry("FLOW_CHART_CONNECTOR", 69, STShapeType.FLOW_CHART_CONNECTOR);
        FLOW_CHART_CONNECTOR = presetGeometry70;
        PresetGeometry presetGeometry71 = new PresetGeometry("FLOW_CHART_DECISION", 70, STShapeType.FLOW_CHART_DECISION);
        FLOW_CHART_DECISION = presetGeometry71;
        PresetGeometry presetGeometry72 = new PresetGeometry("FLOW_CHART_DELAY", 71, STShapeType.FLOW_CHART_DELAY);
        FLOW_CHART_DELAY = presetGeometry72;
        PresetGeometry presetGeometry73 = new PresetGeometry("FLOW_CHART_DISPLAY", 72, STShapeType.FLOW_CHART_DISPLAY);
        FLOW_CHART_DISPLAY = presetGeometry73;
        PresetGeometry presetGeometry74 = new PresetGeometry("FLOW_CHART_DOCUMENT", 73, STShapeType.FLOW_CHART_DOCUMENT);
        FLOW_CHART_DOCUMENT = presetGeometry74;
        PresetGeometry presetGeometry75 = new PresetGeometry("FLOW_CHART_EXTRACT", 74, STShapeType.FLOW_CHART_EXTRACT);
        FLOW_CHART_EXTRACT = presetGeometry75;
        PresetGeometry presetGeometry76 = new PresetGeometry("FLOW_CHART_INPUT_OUTPUT", 75, STShapeType.FLOW_CHART_INPUT_OUTPUT);
        FLOW_CHART_INPUT_OUTPUT = presetGeometry76;
        PresetGeometry presetGeometry77 = new PresetGeometry("FLOW_CHART_INTERNAL_STORAGE", 76, STShapeType.FLOW_CHART_INTERNAL_STORAGE);
        FLOW_CHART_INTERNAL_STORAGE = presetGeometry77;
        PresetGeometry presetGeometry78 = new PresetGeometry("FLOW_CHART_MAGNETIC_DISK", 77, STShapeType.FLOW_CHART_MAGNETIC_DISK);
        FLOW_CHART_MAGNETIC_DISK = presetGeometry78;
        PresetGeometry presetGeometry79 = new PresetGeometry("FLOW_CHART_MAGNETIC_DRUM", 78, STShapeType.FLOW_CHART_MAGNETIC_DRUM);
        FLOW_CHART_MAGNETIC_DRUM = presetGeometry79;
        PresetGeometry presetGeometry80 = new PresetGeometry("FLOW_CHART_MAGNETIC_TAPE", 79, STShapeType.FLOW_CHART_MAGNETIC_TAPE);
        FLOW_CHART_MAGNETIC_TAPE = presetGeometry80;
        PresetGeometry presetGeometry81 = new PresetGeometry("FLOW_CHART_MANUAL_INPUT", 80, STShapeType.FLOW_CHART_MANUAL_INPUT);
        FLOW_CHART_MANUAL_INPUT = presetGeometry81;
        PresetGeometry presetGeometry82 = new PresetGeometry("FLOW_CHART_MANUAL_OPERATION", 81, STShapeType.FLOW_CHART_MANUAL_OPERATION);
        FLOW_CHART_MANUAL_OPERATION = presetGeometry82;
        PresetGeometry presetGeometry83 = new PresetGeometry("FLOW_CHART_MERGE", 82, STShapeType.FLOW_CHART_MERGE);
        FLOW_CHART_MERGE = presetGeometry83;
        PresetGeometry presetGeometry84 = new PresetGeometry("FLOW_CHART_MULTIDOCUMENT", 83, STShapeType.FLOW_CHART_MULTIDOCUMENT);
        FLOW_CHART_MULTIDOCUMENT = presetGeometry84;
        PresetGeometry presetGeometry85 = new PresetGeometry("FLOW_CHART_OFFLINE_STORAGE", 84, STShapeType.FLOW_CHART_OFFLINE_STORAGE);
        FLOW_CHART_OFFLINE_STORAGE = presetGeometry85;
        PresetGeometry presetGeometry86 = new PresetGeometry("FLOW_CHART_OFFPAGE_CONNECTOR", 85, STShapeType.FLOW_CHART_OFFPAGE_CONNECTOR);
        FLOW_CHART_OFFPAGE_CONNECTOR = presetGeometry86;
        PresetGeometry presetGeometry87 = new PresetGeometry("FLOW_CHART_ONLINE_STORAGE", 86, STShapeType.FLOW_CHART_ONLINE_STORAGE);
        FLOW_CHART_ONLINE_STORAGE = presetGeometry87;
        PresetGeometry presetGeometry88 = new PresetGeometry("FLOW_CHART_OR", 87, STShapeType.FLOW_CHART_OR);
        FLOW_CHART_OR = presetGeometry88;
        PresetGeometry presetGeometry89 = new PresetGeometry("FLOW_CHART_PREDEFINED_PROCESS", 88, STShapeType.FLOW_CHART_PREDEFINED_PROCESS);
        FLOW_CHART_PREDEFINED_PROCESS = presetGeometry89;
        PresetGeometry presetGeometry90 = new PresetGeometry("FLOW_CHART_PREPARATION", 89, STShapeType.FLOW_CHART_PREPARATION);
        FLOW_CHART_PREPARATION = presetGeometry90;
        PresetGeometry presetGeometry91 = new PresetGeometry("FLOW_CHART_PROCESS", 90, STShapeType.FLOW_CHART_PROCESS);
        FLOW_CHART_PROCESS = presetGeometry91;
        PresetGeometry presetGeometry92 = new PresetGeometry("FLOW_CHART_PUNCHED_CARD", 91, STShapeType.FLOW_CHART_PUNCHED_CARD);
        FLOW_CHART_PUNCHED_CARD = presetGeometry92;
        PresetGeometry presetGeometry93 = new PresetGeometry("FLOW_CHART_PUNCHED_TAPE", 92, STShapeType.FLOW_CHART_PUNCHED_TAPE);
        FLOW_CHART_PUNCHED_TAPE = presetGeometry93;
        PresetGeometry presetGeometry94 = new PresetGeometry("FLOW_CHART_SORT", 93, STShapeType.FLOW_CHART_SORT);
        FLOW_CHART_SORT = presetGeometry94;
        PresetGeometry presetGeometry95 = new PresetGeometry("FLOW_CHART_SUMMING_JUNCTION", 94, STShapeType.FLOW_CHART_SUMMING_JUNCTION);
        FLOW_CHART_SUMMING_JUNCTION = presetGeometry95;
        PresetGeometry presetGeometry96 = new PresetGeometry("FLOW_CHART_TERMINATOR", 95, STShapeType.FLOW_CHART_TERMINATOR);
        FLOW_CHART_TERMINATOR = presetGeometry96;
        PresetGeometry presetGeometry97 = new PresetGeometry("FOLDED_CORNER", 96, STShapeType.FOLDED_CORNER);
        FOLDED_CORNER = presetGeometry97;
        PresetGeometry presetGeometry98 = new PresetGeometry("FRAME", 97, STShapeType.FRAME);
        FRAME = presetGeometry98;
        PresetGeometry presetGeometry99 = new PresetGeometry("FUNNEL", 98, STShapeType.FUNNEL);
        FUNNEL = presetGeometry99;
        PresetGeometry presetGeometry100 = new PresetGeometry("GEAR_6", 99, STShapeType.GEAR_6);
        GEAR_6 = presetGeometry100;
        PresetGeometry presetGeometry101 = new PresetGeometry("GEAR_9", 100, STShapeType.GEAR_9);
        GEAR_9 = presetGeometry101;
        PresetGeometry presetGeometry102 = new PresetGeometry("HALF_FRAME", 101, STShapeType.HALF_FRAME);
        HALF_FRAME = presetGeometry102;
        PresetGeometry presetGeometry103 = new PresetGeometry("HEART", 102, STShapeType.HEART);
        HEART = presetGeometry103;
        PresetGeometry presetGeometry104 = new PresetGeometry("HEPTAGON", 103, STShapeType.HEPTAGON);
        HEPTAGON = presetGeometry104;
        PresetGeometry presetGeometry105 = new PresetGeometry("HEXAGON", 104, STShapeType.HEXAGON);
        HEXAGON = presetGeometry105;
        PresetGeometry presetGeometry106 = new PresetGeometry("HOME_PLATE", 105, STShapeType.HOME_PLATE);
        HOME_PLATE = presetGeometry106;
        PresetGeometry presetGeometry107 = new PresetGeometry("HORIZONTAL_SCROLL", 106, STShapeType.HORIZONTAL_SCROLL);
        HORIZONTAL_SCROLL = presetGeometry107;
        PresetGeometry presetGeometry108 = new PresetGeometry("IRREGULAR_SEAL_1", 107, STShapeType.IRREGULAR_SEAL_1);
        IRREGULAR_SEAL_1 = presetGeometry108;
        PresetGeometry presetGeometry109 = new PresetGeometry("IRREGULAR_SEAL_2", 108, STShapeType.IRREGULAR_SEAL_2);
        IRREGULAR_SEAL_2 = presetGeometry109;
        PresetGeometry presetGeometry110 = new PresetGeometry("LEFT_ARROW", 109, STShapeType.LEFT_ARROW);
        LEFT_ARROW = presetGeometry110;
        PresetGeometry presetGeometry111 = new PresetGeometry("LEFT_ARROW_CALLOUT", 110, STShapeType.LEFT_ARROW_CALLOUT);
        LEFT_ARROW_CALLOUT = presetGeometry111;
        PresetGeometry presetGeometry112 = new PresetGeometry("LEFT_BRACE", 111, STShapeType.LEFT_BRACE);
        LEFT_BRACE = presetGeometry112;
        PresetGeometry presetGeometry113 = new PresetGeometry("LEFT_BRACKET", 112, STShapeType.LEFT_BRACKET);
        LEFT_BRACKET = presetGeometry113;
        PresetGeometry presetGeometry114 = new PresetGeometry("LEFT_CIRCULAR_ARROW", 113, STShapeType.LEFT_CIRCULAR_ARROW);
        LEFT_CIRCULAR_ARROW = presetGeometry114;
        PresetGeometry presetGeometry115 = new PresetGeometry("LEFT_RIGHT_ARROW", 114, STShapeType.LEFT_RIGHT_ARROW);
        LEFT_RIGHT_ARROW = presetGeometry115;
        PresetGeometry presetGeometry116 = new PresetGeometry("LEFT_RIGHT_ARROW_CALLOUT", 115, STShapeType.LEFT_RIGHT_ARROW_CALLOUT);
        LEFT_RIGHT_ARROW_CALLOUT = presetGeometry116;
        PresetGeometry presetGeometry117 = new PresetGeometry("LEFT_RIGHT_CIRCULAR_ARROW", 116, STShapeType.LEFT_RIGHT_CIRCULAR_ARROW);
        LEFT_RIGHT_CIRCULAR_ARROW = presetGeometry117;
        PresetGeometry presetGeometry118 = new PresetGeometry("LEFT_RIGHT_RIBBON", 117, STShapeType.LEFT_RIGHT_RIBBON);
        LEFT_RIGHT_RIBBON = presetGeometry118;
        PresetGeometry presetGeometry119 = new PresetGeometry("LEFT_RIGHT_UP_ARROW", 118, STShapeType.LEFT_RIGHT_UP_ARROW);
        LEFT_RIGHT_UP_ARROW = presetGeometry119;
        PresetGeometry presetGeometry120 = new PresetGeometry("LEFT_UP_ARROW", 119, STShapeType.LEFT_UP_ARROW);
        LEFT_UP_ARROW = presetGeometry120;
        PresetGeometry presetGeometry121 = new PresetGeometry("LIGHTNING_BOLT", 120, STShapeType.LIGHTNING_BOLT);
        LIGHTNING_BOLT = presetGeometry121;
        PresetGeometry presetGeometry122 = new PresetGeometry("LINE", 121, STShapeType.LINE);
        LINE = presetGeometry122;
        PresetGeometry presetGeometry123 = new PresetGeometry("LINE_INVERTED", 122, STShapeType.LINE_INV);
        LINE_INVERTED = presetGeometry123;
        PresetGeometry presetGeometry124 = new PresetGeometry("MATH_DIVIDE", 123, STShapeType.MATH_DIVIDE);
        MATH_DIVIDE = presetGeometry124;
        PresetGeometry presetGeometry125 = new PresetGeometry("MATH_EQUAL", 124, STShapeType.MATH_EQUAL);
        MATH_EQUAL = presetGeometry125;
        PresetGeometry presetGeometry126 = new PresetGeometry("MATH_MINUS", 125, STShapeType.MATH_MINUS);
        MATH_MINUS = presetGeometry126;
        PresetGeometry presetGeometry127 = new PresetGeometry("MATH_MULTIPLY", 126, STShapeType.MATH_MULTIPLY);
        MATH_MULTIPLY = presetGeometry127;
        PresetGeometry presetGeometry128 = new PresetGeometry("MATH_NOT_EQUAL", 127, STShapeType.MATH_NOT_EQUAL);
        MATH_NOT_EQUAL = presetGeometry128;
        PresetGeometry presetGeometry129 = new PresetGeometry("MATH_PLUS", 128, STShapeType.MATH_PLUS);
        MATH_PLUS = presetGeometry129;
        PresetGeometry presetGeometry130 = new PresetGeometry("MOON", 129, STShapeType.MOON);
        MOON = presetGeometry130;
        PresetGeometry presetGeometry131 = new PresetGeometry("NO_SMOKING", 130, STShapeType.NO_SMOKING);
        NO_SMOKING = presetGeometry131;
        PresetGeometry presetGeometry132 = new PresetGeometry("NON_ISOSCELES_TRAPEZOID", 131, STShapeType.NON_ISOSCELES_TRAPEZOID);
        NON_ISOSCELES_TRAPEZOID = presetGeometry132;
        PresetGeometry presetGeometry133 = new PresetGeometry("NOTCHED_RIGHT_ARROW", 132, STShapeType.NOTCHED_RIGHT_ARROW);
        NOTCHED_RIGHT_ARROW = presetGeometry133;
        PresetGeometry presetGeometry134 = new PresetGeometry("OCTAGON", 133, STShapeType.OCTAGON);
        OCTAGON = presetGeometry134;
        PresetGeometry presetGeometry135 = new PresetGeometry("PARALLELOGRAM", 134, STShapeType.PARALLELOGRAM);
        PARALLELOGRAM = presetGeometry135;
        PresetGeometry presetGeometry136 = new PresetGeometry("PENTAGON", 135, STShapeType.PENTAGON);
        PENTAGON = presetGeometry136;
        PresetGeometry presetGeometry137 = new PresetGeometry("PIE", 136, STShapeType.PIE);
        PIE = presetGeometry137;
        PresetGeometry presetGeometry138 = new PresetGeometry("PIE_WEDGE", 137, STShapeType.PIE_WEDGE);
        PIE_WEDGE = presetGeometry138;
        PresetGeometry presetGeometry139 = new PresetGeometry("PLAQUE", 138, STShapeType.PLAQUE);
        PLAQUE = presetGeometry139;
        PresetGeometry presetGeometry140 = new PresetGeometry("PLAQUE_TABS", 139, STShapeType.PLAQUE_TABS);
        PLAQUE_TABS = presetGeometry140;
        PresetGeometry presetGeometry141 = new PresetGeometry("PLUS", 140, STShapeType.PLUS);
        PLUS = presetGeometry141;
        PresetGeometry presetGeometry142 = new PresetGeometry("QUAD_ARROW", 141, STShapeType.QUAD_ARROW);
        QUAD_ARROW = presetGeometry142;
        PresetGeometry presetGeometry143 = new PresetGeometry("QUAD_ARROW_CALLOUT", 142, STShapeType.QUAD_ARROW_CALLOUT);
        QUAD_ARROW_CALLOUT = presetGeometry143;
        PresetGeometry presetGeometry144 = new PresetGeometry("RECTANGLE", 143, STShapeType.RECT);
        RECTANGLE = presetGeometry144;
        PresetGeometry presetGeometry145 = new PresetGeometry("RIBBON", 144, STShapeType.RIBBON);
        RIBBON = presetGeometry145;
        PresetGeometry presetGeometry146 = new PresetGeometry("RIBBON_2", 145, STShapeType.RIBBON_2);
        RIBBON_2 = presetGeometry146;
        PresetGeometry presetGeometry147 = new PresetGeometry("RIGHT_ARROW", 146, STShapeType.RIGHT_ARROW);
        RIGHT_ARROW = presetGeometry147;
        PresetGeometry presetGeometry148 = new PresetGeometry("RIGHT_ARROW_CALLOUT", 147, STShapeType.RIGHT_ARROW_CALLOUT);
        RIGHT_ARROW_CALLOUT = presetGeometry148;
        PresetGeometry presetGeometry149 = new PresetGeometry("RIGHT_BRACE", 148, STShapeType.RIGHT_BRACE);
        RIGHT_BRACE = presetGeometry149;
        PresetGeometry presetGeometry150 = new PresetGeometry("RIGHT_BRACKET", 149, STShapeType.RIGHT_BRACKET);
        RIGHT_BRACKET = presetGeometry150;
        PresetGeometry presetGeometry151 = new PresetGeometry("ROUND_RECTANGLE_1_CORNER", 150, STShapeType.ROUND_1_RECT);
        ROUND_RECTANGLE_1_CORNER = presetGeometry151;
        PresetGeometry presetGeometry152 = new PresetGeometry("ROUND_RECTANGLE_2_DIAGONAL_CORNERS", 151, STShapeType.ROUND_2_DIAG_RECT);
        ROUND_RECTANGLE_2_DIAGONAL_CORNERS = presetGeometry152;
        PresetGeometry presetGeometry153 = new PresetGeometry("ROUND_RECTANGLE_2_SAME_SIDE_CORNERS", 152, STShapeType.ROUND_2_SAME_RECT);
        ROUND_RECTANGLE_2_SAME_SIDE_CORNERS = presetGeometry153;
        PresetGeometry presetGeometry154 = new PresetGeometry("ROUND_RECTANGLE", 153, STShapeType.ROUND_RECT);
        ROUND_RECTANGLE = presetGeometry154;
        PresetGeometry presetGeometry155 = new PresetGeometry("RIGHT_TRIANGLE", 154, STShapeType.RT_TRIANGLE);
        RIGHT_TRIANGLE = presetGeometry155;
        PresetGeometry presetGeometry156 = new PresetGeometry("SMILEY_FACE", 155, STShapeType.SMILEY_FACE);
        SMILEY_FACE = presetGeometry156;
        PresetGeometry presetGeometry157 = new PresetGeometry("SNIP_RECTANGLE_1_CORNER", 156, STShapeType.SNIP_1_RECT);
        SNIP_RECTANGLE_1_CORNER = presetGeometry157;
        PresetGeometry presetGeometry158 = new PresetGeometry("SNIP_RECTANGLE_2_DIAGONAL_CORNERS", 157, STShapeType.SNIP_2_DIAG_RECT);
        SNIP_RECTANGLE_2_DIAGONAL_CORNERS = presetGeometry158;
        PresetGeometry presetGeometry159 = new PresetGeometry("SNIP_RECTANGLE_2_SAME_SIDE_CORNERS", 158, STShapeType.SNIP_2_SAME_RECT);
        SNIP_RECTANGLE_2_SAME_SIDE_CORNERS = presetGeometry159;
        PresetGeometry presetGeometry160 = new PresetGeometry("SNIP_ROUND_RECTANGLE", 159, STShapeType.SNIP_ROUND_RECT);
        SNIP_ROUND_RECTANGLE = presetGeometry160;
        PresetGeometry presetGeometry161 = new PresetGeometry("SQUARE_TABS", 160, STShapeType.SQUARE_TABS);
        SQUARE_TABS = presetGeometry161;
        PresetGeometry presetGeometry162 = new PresetGeometry("STAR_10", 161, STShapeType.STAR_10);
        STAR_10 = presetGeometry162;
        PresetGeometry presetGeometry163 = new PresetGeometry("STAR_12", 162, STShapeType.STAR_12);
        STAR_12 = presetGeometry163;
        PresetGeometry presetGeometry164 = new PresetGeometry("STAR_16", 163, STShapeType.STAR_16);
        STAR_16 = presetGeometry164;
        PresetGeometry presetGeometry165 = new PresetGeometry("STAR_24", 164, STShapeType.STAR_24);
        STAR_24 = presetGeometry165;
        PresetGeometry presetGeometry166 = new PresetGeometry("STAR_32", 165, STShapeType.STAR_32);
        STAR_32 = presetGeometry166;
        PresetGeometry presetGeometry167 = new PresetGeometry("STAR_4", 166, STShapeType.STAR_4);
        STAR_4 = presetGeometry167;
        PresetGeometry presetGeometry168 = new PresetGeometry("STAR_5", 167, STShapeType.STAR_5);
        STAR_5 = presetGeometry168;
        PresetGeometry presetGeometry169 = new PresetGeometry("STAR_6", 168, STShapeType.STAR_6);
        STAR_6 = presetGeometry169;
        PresetGeometry presetGeometry170 = new PresetGeometry("STAR_7", 169, STShapeType.STAR_7);
        STAR_7 = presetGeometry170;
        PresetGeometry presetGeometry171 = new PresetGeometry("STAR_8", 170, STShapeType.STAR_8);
        STAR_8 = presetGeometry171;
        PresetGeometry presetGeometry172 = new PresetGeometry("STRAIGHT_CONNECTOR", 171, STShapeType.STRAIGHT_CONNECTOR_1);
        STRAIGHT_CONNECTOR = presetGeometry172;
        PresetGeometry presetGeometry173 = new PresetGeometry("STRIPED_RIGHT_ARROW", 172, STShapeType.STRIPED_RIGHT_ARROW);
        STRIPED_RIGHT_ARROW = presetGeometry173;
        PresetGeometry presetGeometry174 = new PresetGeometry("SUN", 173, STShapeType.SUN);
        SUN = presetGeometry174;
        PresetGeometry presetGeometry175 = new PresetGeometry("SWOOSH_ARROW", 174, STShapeType.SWOOSH_ARROW);
        SWOOSH_ARROW = presetGeometry175;
        PresetGeometry presetGeometry176 = new PresetGeometry("TEARDROP", 175, STShapeType.TEARDROP);
        TEARDROP = presetGeometry176;
        PresetGeometry presetGeometry177 = new PresetGeometry("TRAPEZOID", 176, STShapeType.TRAPEZOID);
        TRAPEZOID = presetGeometry177;
        PresetGeometry presetGeometry178 = new PresetGeometry("TRIANGLE", 177, STShapeType.TRIANGLE);
        TRIANGLE = presetGeometry178;
        PresetGeometry presetGeometry179 = new PresetGeometry("UP_ARROW", 178, STShapeType.UP_ARROW);
        UP_ARROW = presetGeometry179;
        PresetGeometry presetGeometry180 = new PresetGeometry("UP_ARROW_CALLOUT", 179, STShapeType.UP_ARROW_CALLOUT);
        UP_ARROW_CALLOUT = presetGeometry180;
        PresetGeometry presetGeometry181 = new PresetGeometry("UP_DOWN_ARROW", 180, STShapeType.UP_DOWN_ARROW);
        UP_DOWN_ARROW = presetGeometry181;
        PresetGeometry presetGeometry182 = new PresetGeometry("UP_DOWN_ARROW_CALLOUT", 181, STShapeType.UP_DOWN_ARROW_CALLOUT);
        UP_DOWN_ARROW_CALLOUT = presetGeometry182;
        PresetGeometry presetGeometry183 = new PresetGeometry("UTURN_ARROW", 182, STShapeType.UTURN_ARROW);
        UTURN_ARROW = presetGeometry183;
        PresetGeometry presetGeometry184 = new PresetGeometry("VERTICAL_SCROLL", 183, STShapeType.VERTICAL_SCROLL);
        VERTICAL_SCROLL = presetGeometry184;
        PresetGeometry presetGeometry185 = new PresetGeometry("WAVE", 184, STShapeType.WAVE);
        WAVE = presetGeometry185;
        PresetGeometry presetGeometry186 = new PresetGeometry("WEDGE_ELLIPSE_CALLOUT", 185, STShapeType.WEDGE_ELLIPSE_CALLOUT);
        WEDGE_ELLIPSE_CALLOUT = presetGeometry186;
        PresetGeometry presetGeometry187 = new PresetGeometry("WEDGE_RECTANGLE_CALLOUT", 186, STShapeType.WEDGE_RECT_CALLOUT);
        WEDGE_RECTANGLE_CALLOUT = presetGeometry187;
        PresetGeometry presetGeometry188 = new PresetGeometry("WEDGE_ROUND_RECTANGLE_CALLOUT", 187, STShapeType.WEDGE_ROUND_RECT_CALLOUT);
        WEDGE_ROUND_RECTANGLE_CALLOUT = presetGeometry188;
        $VALUES = new PresetGeometry[]{presetGeometry, presetGeometry2, presetGeometry3, presetGeometry4, presetGeometry5, presetGeometry6, presetGeometry7, presetGeometry8, presetGeometry9, presetGeometry10, presetGeometry11, presetGeometry12, presetGeometry13, presetGeometry14, presetGeometry15, presetGeometry16, presetGeometry17, presetGeometry18, presetGeometry19, presetGeometry20, presetGeometry21, presetGeometry22, presetGeometry23, presetGeometry24, presetGeometry25, presetGeometry26, presetGeometry27, presetGeometry28, presetGeometry29, presetGeometry30, presetGeometry31, presetGeometry32, presetGeometry33, presetGeometry34, presetGeometry35, presetGeometry36, presetGeometry37, presetGeometry38, presetGeometry39, presetGeometry40, presetGeometry41, presetGeometry42, presetGeometry43, presetGeometry44, presetGeometry45, presetGeometry46, presetGeometry47, presetGeometry48, presetGeometry49, presetGeometry50, presetGeometry51, presetGeometry52, presetGeometry53, presetGeometry54, presetGeometry55, presetGeometry56, presetGeometry57, presetGeometry58, presetGeometry59, presetGeometry60, presetGeometry61, presetGeometry62, presetGeometry63, presetGeometry64, presetGeometry65, presetGeometry66, presetGeometry67, presetGeometry68, presetGeometry69, presetGeometry70, presetGeometry71, presetGeometry72, presetGeometry73, presetGeometry74, presetGeometry75, presetGeometry76, presetGeometry77, presetGeometry78, presetGeometry79, presetGeometry80, presetGeometry81, presetGeometry82, presetGeometry83, presetGeometry84, presetGeometry85, presetGeometry86, presetGeometry87, presetGeometry88, presetGeometry89, presetGeometry90, presetGeometry91, presetGeometry92, presetGeometry93, presetGeometry94, presetGeometry95, presetGeometry96, presetGeometry97, presetGeometry98, presetGeometry99, presetGeometry100, presetGeometry101, presetGeometry102, presetGeometry103, presetGeometry104, presetGeometry105, presetGeometry106, presetGeometry107, presetGeometry108, presetGeometry109, presetGeometry110, presetGeometry111, presetGeometry112, presetGeometry113, presetGeometry114, presetGeometry115, presetGeometry116, presetGeometry117, presetGeometry118, presetGeometry119, presetGeometry120, presetGeometry121, presetGeometry122, presetGeometry123, presetGeometry124, presetGeometry125, presetGeometry126, presetGeometry127, presetGeometry128, presetGeometry129, presetGeometry130, presetGeometry131, presetGeometry132, presetGeometry133, presetGeometry134, presetGeometry135, presetGeometry136, presetGeometry137, presetGeometry138, presetGeometry139, presetGeometry140, presetGeometry141, presetGeometry142, presetGeometry143, presetGeometry144, presetGeometry145, presetGeometry146, presetGeometry147, presetGeometry148, presetGeometry149, presetGeometry150, presetGeometry151, presetGeometry152, presetGeometry153, presetGeometry154, presetGeometry155, presetGeometry156, presetGeometry157, presetGeometry158, presetGeometry159, presetGeometry160, presetGeometry161, presetGeometry162, presetGeometry163, presetGeometry164, presetGeometry165, presetGeometry166, presetGeometry167, presetGeometry168, presetGeometry169, presetGeometry170, presetGeometry171, presetGeometry172, presetGeometry173, presetGeometry174, presetGeometry175, presetGeometry176, presetGeometry177, presetGeometry178, presetGeometry179, presetGeometry180, presetGeometry181, presetGeometry182, presetGeometry183, presetGeometry184, presetGeometry185, presetGeometry186, presetGeometry187, presetGeometry188};
        reverse = new HashMap<>();
        for (PresetGeometry presetGeometry189 : values()) {
            reverse.put(presetGeometry189.underlying, presetGeometry189);
        }
    }

    private PresetGeometry(String str, int i5, STShapeType.Enum r6) {
        super(str, i5);
        this.underlying = r6;
    }

    public static PresetGeometry valueOf(String str) {
        return (PresetGeometry) Enum.valueOf(PresetGeometry.class, str);
    }

    public static PresetGeometry[] values() {
        return (PresetGeometry[]) $VALUES.clone();
    }

    public static PresetGeometry valueOf(STShapeType.Enum r6) {
        return reverse.get(r6);
    }
}
