package com.google.android.gms.internal.mlkit_vision_common;

import com.google.android.gms.auth.api.accounttransfer.a;
import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import io.flutter.plugins.firebase.analytics.Constants;

/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes2.dex */
final class zzeo implements ObjectEncoder {
    static final zzeo zza = new zzeo();
    private static final FieldDescriptor zzb = a.y(1, FieldDescriptor.builder("systemInfo"));
    private static final FieldDescriptor zzc = a.y(2, FieldDescriptor.builder(Constants.EVENT_NAME));
    private static final FieldDescriptor zzd = a.y(37, FieldDescriptor.builder("isThickClient"));
    private static final FieldDescriptor zze = a.y(61, FieldDescriptor.builder("clientType"));
    private static final FieldDescriptor zzf = a.y(3, FieldDescriptor.builder("modelDownloadLogEvent"));
    private static final FieldDescriptor zzg = a.y(20, FieldDescriptor.builder("customModelLoadLogEvent"));
    private static final FieldDescriptor zzh = a.y(4, FieldDescriptor.builder("customModelInferenceLogEvent"));
    private static final FieldDescriptor zzi = a.y(29, FieldDescriptor.builder("customModelCreateLogEvent"));
    private static final FieldDescriptor zzj = a.y(5, FieldDescriptor.builder("onDeviceFaceDetectionLogEvent"));
    private static final FieldDescriptor zzk = a.y(59, FieldDescriptor.builder("onDeviceFaceLoadLogEvent"));
    private static final FieldDescriptor zzl = a.y(6, FieldDescriptor.builder("onDeviceTextDetectionLogEvent"));
    private static final FieldDescriptor zzm = a.y(79, FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent"));
    private static final FieldDescriptor zzn = a.y(7, FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent"));
    private static final FieldDescriptor zzo = a.y(58, FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent"));
    private static final FieldDescriptor zzp = a.y(48, FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent"));
    private static final FieldDescriptor zzq = a.y(49, FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent"));
    private static final FieldDescriptor zzr = a.y(18, FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzs = a.y(26, FieldDescriptor.builder("onDeviceObjectCreateLogEvent"));
    private static final FieldDescriptor zzt = a.y(27, FieldDescriptor.builder("onDeviceObjectLoadLogEvent"));
    private static final FieldDescriptor zzu = a.y(28, FieldDescriptor.builder("onDeviceObjectInferenceLogEvent"));
    private static final FieldDescriptor zzv = a.y(44, FieldDescriptor.builder("onDevicePoseDetectionLogEvent"));
    private static final FieldDescriptor zzw = a.y(45, FieldDescriptor.builder("onDeviceSegmentationLogEvent"));
    private static final FieldDescriptor zzx = a.y(19, FieldDescriptor.builder("onDeviceSmartReplyLogEvent"));
    private static final FieldDescriptor zzy = a.y(21, FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent"));
    private static final FieldDescriptor zzz = a.y(22, FieldDescriptor.builder("onDeviceTranslationLogEvent"));
    private static final FieldDescriptor zzA = a.y(8, FieldDescriptor.builder("cloudFaceDetectionLogEvent"));
    private static final FieldDescriptor zzB = a.y(9, FieldDescriptor.builder("cloudCropHintDetectionLogEvent"));
    private static final FieldDescriptor zzC = a.y(10, FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent"));
    private static final FieldDescriptor zzD = a.y(11, FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent"));
    private static final FieldDescriptor zzE = a.y(12, FieldDescriptor.builder("cloudImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzF = a.y(13, FieldDescriptor.builder("cloudLandmarkDetectionLogEvent"));
    private static final FieldDescriptor zzG = a.y(14, FieldDescriptor.builder("cloudLogoDetectionLogEvent"));
    private static final FieldDescriptor zzH = a.y(15, FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent"));
    private static final FieldDescriptor zzI = a.y(16, FieldDescriptor.builder("cloudTextDetectionLogEvent"));
    private static final FieldDescriptor zzJ = a.y(17, FieldDescriptor.builder("cloudWebSearchDetectionLogEvent"));
    private static final FieldDescriptor zzK = a.y(23, FieldDescriptor.builder("automlImageLabelingCreateLogEvent"));
    private static final FieldDescriptor zzL = a.y(24, FieldDescriptor.builder("automlImageLabelingLoadLogEvent"));
    private static final FieldDescriptor zzM = a.y(25, FieldDescriptor.builder("automlImageLabelingInferenceLogEvent"));
    private static final FieldDescriptor zzN = a.y(39, FieldDescriptor.builder("isModelDownloadedLogEvent"));
    private static final FieldDescriptor zzO = a.y(40, FieldDescriptor.builder("deleteModelLogEvent"));
    private static final FieldDescriptor zzP = a.y(30, FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent"));
    private static final FieldDescriptor zzQ = a.y(31, FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent"));
    private static final FieldDescriptor zzR = a.y(32, FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent"));
    private static final FieldDescriptor zzS = a.y(33, FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent"));
    private static final FieldDescriptor zzT = a.y(34, FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzU = a.y(35, FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent"));
    private static final FieldDescriptor zzV = a.y(36, FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent"));
    private static final FieldDescriptor zzW = a.y(46, FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent"));
    private static final FieldDescriptor zzX = a.y(47, FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent"));
    private static final FieldDescriptor zzY = a.y(69, FieldDescriptor.builder("pipelineAccelerationInferenceEvents"));
    private static final FieldDescriptor zzZ = a.y(42, FieldDescriptor.builder("remoteConfigLogEvent"));
    private static final FieldDescriptor zzaa = a.y(50, FieldDescriptor.builder("inputImageConstructionLogEvent"));
    private static final FieldDescriptor zzab = a.y(51, FieldDescriptor.builder("leakedHandleEvent"));
    private static final FieldDescriptor zzac = a.y(52, FieldDescriptor.builder("cameraSourceLogEvent"));
    private static final FieldDescriptor zzad = a.y(53, FieldDescriptor.builder("imageLabelOptionalModuleLogEvent"));
    private static final FieldDescriptor zzae = a.y(54, FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaf = a.y(60, FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzag = a.y(85, FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzah = a.y(86, FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent"));
    private static final FieldDescriptor zzai = a.y(87, FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaj = a.y(55, FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent"));
    private static final FieldDescriptor zzak = a.y(56, FieldDescriptor.builder("nlClassifierClientLibraryLogEvent"));
    private static final FieldDescriptor zzal = a.y(57, FieldDescriptor.builder("accelerationAllowlistLogEvent"));
    private static final FieldDescriptor zzam = a.y(62, FieldDescriptor.builder("toxicityDetectionCreateEvent"));
    private static final FieldDescriptor zzan = a.y(63, FieldDescriptor.builder("toxicityDetectionLoadEvent"));
    private static final FieldDescriptor zzao = a.y(64, FieldDescriptor.builder("toxicityDetectionInferenceEvent"));
    private static final FieldDescriptor zzap = a.y(65, FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaq = a.y(66, FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent"));
    private static final FieldDescriptor zzar = a.y(67, FieldDescriptor.builder("codeScannerScanApiEvent"));
    private static final FieldDescriptor zzas = a.y(68, FieldDescriptor.builder("codeScannerOptionalModuleEvent"));
    private static final FieldDescriptor zzat = a.y(70, FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent"));
    private static final FieldDescriptor zzau = a.y(71, FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent"));
    private static final FieldDescriptor zzav = a.y(72, FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent"));
    private static final FieldDescriptor zzaw = a.y(73, FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent"));
    private static final FieldDescriptor zzax = a.y(74, FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent"));
    private static final FieldDescriptor zzay = a.y(75, FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent"));
    private static final FieldDescriptor zzaz = a.y(76, FieldDescriptor.builder("onDeviceFaceMeshLogEvent"));
    private static final FieldDescriptor zzaA = a.y(77, FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent"));
    private static final FieldDescriptor zzaB = a.y(78, FieldDescriptor.builder("smartReplyOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaC = a.y(80, FieldDescriptor.builder("textDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaD = a.y(81, FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent"));
    private static final FieldDescriptor zzaE = a.y(82, FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent"));
    private static final FieldDescriptor zzaF = a.y(83, FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent"));
    private static final FieldDescriptor zzaG = a.y(84, FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent"));
    private static final FieldDescriptor zzaH = a.y(88, FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaI = a.y(89, FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaJ = a.y(90, FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent"));
    private static final FieldDescriptor zzaK = a.y(91, FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent"));
    private static final FieldDescriptor zzaL = a.y(92, FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent"));
    private static final FieldDescriptor zzaM = a.y(93, FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent"));

    private zzeo() {
    }

    @Override // com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) {
        zziy zziyVar = (zziy) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zziyVar.zzc());
        objectEncoderContext2.add(zzc, zziyVar.zzb());
        objectEncoderContext2.add(zzd, (Object) null);
        objectEncoderContext2.add(zze, (Object) null);
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, (Object) null);
        objectEncoderContext2.add(zzl, (Object) null);
        objectEncoderContext2.add(zzm, (Object) null);
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, (Object) null);
        objectEncoderContext2.add(zzt, (Object) null);
        objectEncoderContext2.add(zzu, (Object) null);
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, (Object) null);
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, (Object) null);
        objectEncoderContext2.add(zzV, (Object) null);
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, (Object) null);
        objectEncoderContext2.add(zzaa, zziyVar.zza());
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
        objectEncoderContext2.add(zzag, (Object) null);
        objectEncoderContext2.add(zzah, (Object) null);
        objectEncoderContext2.add(zzai, (Object) null);
        objectEncoderContext2.add(zzaj, (Object) null);
        objectEncoderContext2.add(zzak, (Object) null);
        objectEncoderContext2.add(zzal, (Object) null);
        objectEncoderContext2.add(zzam, (Object) null);
        objectEncoderContext2.add(zzan, (Object) null);
        objectEncoderContext2.add(zzao, (Object) null);
        objectEncoderContext2.add(zzap, (Object) null);
        objectEncoderContext2.add(zzaq, (Object) null);
        objectEncoderContext2.add(zzar, (Object) null);
        objectEncoderContext2.add(zzas, (Object) null);
        objectEncoderContext2.add(zzat, (Object) null);
        objectEncoderContext2.add(zzau, (Object) null);
        objectEncoderContext2.add(zzav, (Object) null);
        objectEncoderContext2.add(zzaw, (Object) null);
        objectEncoderContext2.add(zzax, (Object) null);
        objectEncoderContext2.add(zzay, (Object) null);
        objectEncoderContext2.add(zzaz, (Object) null);
        objectEncoderContext2.add(zzaA, (Object) null);
        objectEncoderContext2.add(zzaB, (Object) null);
        objectEncoderContext2.add(zzaC, (Object) null);
        objectEncoderContext2.add(zzaD, (Object) null);
        objectEncoderContext2.add(zzaE, (Object) null);
        objectEncoderContext2.add(zzaF, (Object) null);
        objectEncoderContext2.add(zzaG, (Object) null);
        objectEncoderContext2.add(zzaH, (Object) null);
        objectEncoderContext2.add(zzaI, (Object) null);
        objectEncoderContext2.add(zzaJ, (Object) null);
        objectEncoderContext2.add(zzaK, (Object) null);
        objectEncoderContext2.add(zzaL, (Object) null);
        objectEncoderContext2.add(zzaM, (Object) null);
    }
}
