package org.apache.poi.sl.usermodel;

import androidx.core.internal.view.SupportMenu;
import androidx.core.view.InputDeviceCompat;
import androidx.core.view.ViewCompat;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'ActiveCaptionText' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:485)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByRegister(EnumVisitor.java:422)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:351)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:284)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:153)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:102)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes4.dex */
public final class PresetColor {
    private static final /* synthetic */ PresetColor[] $VALUES;
    public static final PresetColor ActiveBorder;
    public static final PresetColor ActiveCaption;
    public static final PresetColor ActiveCaptionText;
    public static final PresetColor AliceBlue;
    public static final PresetColor AntiqueWhite;
    public static final PresetColor AppWorkspace;
    public static final PresetColor Aqua;
    public static final PresetColor Aquamarine;
    public static final PresetColor Azure;
    public static final PresetColor Beige;
    public static final PresetColor Bisque;
    public static final PresetColor Black;
    public static final PresetColor BlanchedAlmond;
    public static final PresetColor Blue;
    public static final PresetColor BlueViolet;
    public static final PresetColor Brown;
    public static final PresetColor BurlyWood;
    public static final PresetColor ButtonFace;
    public static final PresetColor ButtonHighlight;
    public static final PresetColor ButtonShadow;
    public static final PresetColor CadetBlue;
    public static final PresetColor Chartreuse;
    public static final PresetColor Chocolate;
    public static final PresetColor Control;
    public static final PresetColor ControlDark;
    public static final PresetColor ControlDarkDark;
    public static final PresetColor ControlLight;
    public static final PresetColor ControlLightLight;
    public static final PresetColor ControlText;
    public static final PresetColor Coral;
    public static final PresetColor CornflowerBlue;
    public static final PresetColor Cornsilk;
    public static final PresetColor Crimson;
    public static final PresetColor Cyan;
    public static final PresetColor DarkBlue;
    public static final PresetColor DarkCyan;
    public static final PresetColor DarkGoldenrod;
    public static final PresetColor DarkGray;
    public static final PresetColor DarkGreen;
    public static final PresetColor DarkKhaki;
    public static final PresetColor DarkMagenta;
    public static final PresetColor DarkOliveGreen;
    public static final PresetColor DarkOrange;
    public static final PresetColor DarkOrchid;
    public static final PresetColor DarkRed;
    public static final PresetColor DarkSalmon;
    public static final PresetColor DarkSeaGreen;
    public static final PresetColor DarkSlateBlue;
    public static final PresetColor DarkSlateGray;
    public static final PresetColor DarkTurquoise;
    public static final PresetColor DarkViolet;
    public static final PresetColor DeepPink;
    public static final PresetColor DeepSkyBlue;
    public static final PresetColor Desktop;
    public static final PresetColor DimGray;
    public static final PresetColor DodgerBlue;
    public static final PresetColor Firebrick;
    public static final PresetColor FloralWhite;
    public static final PresetColor ForestGreen;
    public static final PresetColor Fuchsia;
    public static final PresetColor Gainsboro;
    public static final PresetColor GhostWhite;
    public static final PresetColor Gold;
    public static final PresetColor Goldenrod;
    public static final PresetColor GradientActiveCaption;
    public static final PresetColor GradientInactiveCaption;
    public static final PresetColor Gray;
    public static final PresetColor GrayText;
    public static final PresetColor Green;
    public static final PresetColor GreenYellow;
    public static final PresetColor Highlight;
    public static final PresetColor HighlightText;
    public static final PresetColor Honeydew;
    public static final PresetColor HotPink;
    public static final PresetColor HotTrack;
    public static final PresetColor InactiveBorder;
    public static final PresetColor InactiveCaption;
    public static final PresetColor InactiveCaptionText;
    public static final PresetColor IndianRed;
    public static final PresetColor Indigo;
    public static final PresetColor Info;
    public static final PresetColor InfoText;
    public static final PresetColor Ivory;
    public static final PresetColor Khaki;
    public static final PresetColor Lavender;
    public static final PresetColor LavenderBlush;
    public static final PresetColor LawnGreen;
    public static final PresetColor LemonChiffon;
    public static final PresetColor LightBlue;
    public static final PresetColor LightCoral;
    public static final PresetColor LightCyan;
    public static final PresetColor LightGoldenrodYellow;
    public static final PresetColor LightGray;
    public static final PresetColor LightGreen;
    public static final PresetColor LightPink;
    public static final PresetColor LightSalmon;
    public static final PresetColor LightSeaGreen;
    public static final PresetColor LightSkyBlue;
    public static final PresetColor LightSlateGray;
    public static final PresetColor LightSteelBlue;
    public static final PresetColor LightYellow;
    public static final PresetColor Lime;
    public static final PresetColor LimeGreen;
    public static final PresetColor Linen;
    public static final PresetColor Magenta;
    public static final PresetColor Maroon;
    public static final PresetColor MediumAquamarine;
    public static final PresetColor MediumBlue;
    public static final PresetColor MediumOrchid;
    public static final PresetColor MediumPurple;
    public static final PresetColor MediumSeaGreen;
    public static final PresetColor MediumSlateBlue;
    public static final PresetColor MediumSpringGreen;
    public static final PresetColor MediumTurquoise;
    public static final PresetColor MediumVioletRed;
    public static final PresetColor Menu;
    public static final PresetColor MenuBar;
    public static final PresetColor MenuHighlight;
    public static final PresetColor MenuText;
    public static final PresetColor MidnightBlue;
    public static final PresetColor MintCream;
    public static final PresetColor MistyRose;
    public static final PresetColor Moccasin;
    public static final PresetColor NavajoWhite;
    public static final PresetColor Navy;
    public static final PresetColor OldLace;
    public static final PresetColor Olive;
    public static final PresetColor OliveDrab;
    public static final PresetColor Orange;
    public static final PresetColor OrangeRed;
    public static final PresetColor Orchid;
    public static final PresetColor PaleGoldenrod;
    public static final PresetColor PaleGreen;
    public static final PresetColor PaleTurquoise;
    public static final PresetColor PaleVioletRed;
    public static final PresetColor PapayaWhip;
    public static final PresetColor PeachPuff;
    public static final PresetColor Peru;
    public static final PresetColor Pink;
    public static final PresetColor Plum;
    public static final PresetColor PowderBlue;
    public static final PresetColor Purple;
    public static final PresetColor Red;
    public static final PresetColor RosyBrown;
    public static final PresetColor RoyalBlue;
    public static final PresetColor SaddleBrown;
    public static final PresetColor Salmon;
    public static final PresetColor SandyBrown;
    public static final PresetColor ScrollBar;
    public static final PresetColor SeaGreen;
    public static final PresetColor SeaShell;
    public static final PresetColor Sienna;
    public static final PresetColor Silver;
    public static final PresetColor SkyBlue;
    public static final PresetColor SlateBlue;
    public static final PresetColor SlateGray;
    public static final PresetColor Snow;
    public static final PresetColor SpringGreen;
    public static final PresetColor SteelBlue;
    public static final PresetColor Tan;
    public static final PresetColor Teal;
    public static final PresetColor Thistle;
    public static final PresetColor Tomato;
    public static final PresetColor Transparent;
    public static final PresetColor Turquoise;
    public static final PresetColor Violet;
    public static final PresetColor Wheat;
    public static final PresetColor White;
    public static final PresetColor WhiteSmoke;
    public static final PresetColor Window;
    public static final PresetColor WindowFrame;
    public static final PresetColor WindowText;
    public static final PresetColor Yellow;
    public static final PresetColor YellowGreen;
    private static final Map<String, PresetColor> lookupOoxmlId;
    public final Color color;
    public final int nativeId;
    public final String ooxmlId;

    static {
        PresetColor presetColor = new PresetColor("ActiveBorder", 0, -4934476, 1, "activeBorder");
        ActiveBorder = presetColor;
        PresetColor presetColor2 = new PresetColor("ActiveCaption", 1, -6703919, 2, "activeCaption");
        ActiveCaption = presetColor2;
        Integer numValueOf = Integer.valueOf(ViewCompat.MEASURED_STATE_MASK);
        PresetColor presetColor3 = new PresetColor("ActiveCaptionText", 2, numValueOf, 3, "captionText");
        ActiveCaptionText = presetColor3;
        PresetColor presetColor4 = new PresetColor("AppWorkspace", 3, -5526613, 4, "appWorkspace");
        AppWorkspace = presetColor4;
        PresetColor presetColor5 = new PresetColor("Control", 4, -986896, 5, "btnFace");
        Control = presetColor5;
        PresetColor presetColor6 = new PresetColor("ControlDark", 5, -9868951, 6, "btnShadow");
        ControlDark = presetColor6;
        PresetColor presetColor7 = new PresetColor("ControlDarkDark", 6, numValueOf, 7, "3dDkShadow");
        ControlDarkDark = presetColor7;
        PresetColor presetColor8 = new PresetColor("ControlLight", 7, -1842205, 8, "btnHighlight");
        ControlLight = presetColor8;
        PresetColor presetColor9 = new PresetColor("ControlLightLight", 8, -1842205, 9, "3dLight");
        ControlLightLight = presetColor9;
        PresetColor presetColor10 = new PresetColor("ControlText", 9, numValueOf, 10, "btnText");
        ControlText = presetColor10;
        PresetColor presetColor11 = new PresetColor("Desktop", 10, numValueOf, 11, "background");
        Desktop = presetColor11;
        PresetColor presetColor12 = new PresetColor("GrayText", 11, -9605779, 12, "grayText");
        GrayText = presetColor12;
        PresetColor presetColor13 = new PresetColor("Highlight", 12, -13395457, 13, "highlight");
        Highlight = presetColor13;
        PresetColor presetColor14 = new PresetColor("HighlightText", 13, -1, 14, "highlightText");
        HighlightText = presetColor14;
        PresetColor presetColor15 = new PresetColor("HotTrack", 14, -16750900, 15, "hotLight");
        HotTrack = presetColor15;
        PresetColor presetColor16 = new PresetColor("InactiveBorder", 15, -722948, 16, "inactiveBorder");
        InactiveBorder = presetColor16;
        PresetColor presetColor17 = new PresetColor("InactiveCaption", 16, -4207141, 17, "inactiveCaption");
        InactiveCaption = presetColor17;
        PresetColor presetColor18 = new PresetColor("InactiveCaptionText", 17, numValueOf, 18, "inactiveCaptionText");
        InactiveCaptionText = presetColor18;
        PresetColor presetColor19 = new PresetColor("Info", 18, -31, 19, "infoBk");
        Info = presetColor19;
        PresetColor presetColor20 = new PresetColor("InfoText", 19, numValueOf, 20, "infoText");
        InfoText = presetColor20;
        PresetColor presetColor21 = new PresetColor("Menu", 20, -986896, 21, "menu");
        Menu = presetColor21;
        PresetColor presetColor22 = new PresetColor("MenuText", 21, numValueOf, 22, "menuText");
        MenuText = presetColor22;
        PresetColor presetColor23 = new PresetColor("ScrollBar", 22, -3618616, 23, "scrollBar");
        ScrollBar = presetColor23;
        PresetColor presetColor24 = new PresetColor("Window", 23, -1, 24, "window");
        Window = presetColor24;
        PresetColor presetColor25 = new PresetColor("WindowFrame", 24, -10197916, 25, "windowFrame");
        WindowFrame = presetColor25;
        PresetColor presetColor26 = new PresetColor("WindowText", 25, numValueOf, 26, "windowText");
        WindowText = presetColor26;
        PresetColor presetColor27 = new PresetColor("Transparent", 26, 16777215, 27, null);
        Transparent = presetColor27;
        PresetColor presetColor28 = new PresetColor("AliceBlue", 27, -984833, 28, "aliceBlue");
        AliceBlue = presetColor28;
        PresetColor presetColor29 = new PresetColor("AntiqueWhite", 28, -332841, 29, "antiqueWhite");
        AntiqueWhite = presetColor29;
        PresetColor presetColor30 = new PresetColor("Aqua", 29, -16711681, 30, "aqua");
        Aqua = presetColor30;
        PresetColor presetColor31 = new PresetColor("Aquamarine", 30, -8388652, 31, "aquamarine");
        Aquamarine = presetColor31;
        PresetColor presetColor32 = new PresetColor("Azure", 31, -983041, 32, "azure");
        Azure = presetColor32;
        PresetColor presetColor33 = new PresetColor("Beige", 32, -657956, 33, "beige");
        Beige = presetColor33;
        PresetColor presetColor34 = new PresetColor("Bisque", 33, -6972, 34, "bisque");
        Bisque = presetColor34;
        PresetColor presetColor35 = new PresetColor("Black", 34, numValueOf, 35, "black");
        Black = presetColor35;
        PresetColor presetColor36 = new PresetColor("BlanchedAlmond", 35, -5171, 36, "blanchedAlmond");
        BlanchedAlmond = presetColor36;
        PresetColor presetColor37 = new PresetColor("Blue", 36, -16776961, 37, "blue");
        Blue = presetColor37;
        PresetColor presetColor38 = new PresetColor("BlueViolet", 37, -7722014, 38, "blueViolet");
        BlueViolet = presetColor38;
        PresetColor presetColor39 = new PresetColor("Brown", 38, -5952982, 39, "brown");
        Brown = presetColor39;
        PresetColor presetColor40 = new PresetColor("BurlyWood", 39, -2180985, 40, "burlyWood");
        BurlyWood = presetColor40;
        PresetColor presetColor41 = new PresetColor("CadetBlue", 40, -10510688, 41, "cadetBlue");
        CadetBlue = presetColor41;
        PresetColor presetColor42 = new PresetColor("Chartreuse", 41, -8388864, 42, "chartreuse");
        Chartreuse = presetColor42;
        PresetColor presetColor43 = new PresetColor("Chocolate", 42, -2987746, 43, "chocolate");
        Chocolate = presetColor43;
        PresetColor presetColor44 = new PresetColor("Coral", 43, -32944, 44, "coral");
        Coral = presetColor44;
        PresetColor presetColor45 = new PresetColor("CornflowerBlue", 44, -10185235, 45, "cornflowerBlue");
        CornflowerBlue = presetColor45;
        PresetColor presetColor46 = new PresetColor("Cornsilk", 45, -1828, 46, "cornsilk");
        Cornsilk = presetColor46;
        PresetColor presetColor47 = new PresetColor("Crimson", 46, -2354116, 47, "crimson");
        Crimson = presetColor47;
        PresetColor presetColor48 = new PresetColor("Cyan", 47, -16711681, 48, "cyan");
        Cyan = presetColor48;
        PresetColor presetColor49 = new PresetColor("DarkBlue", 48, -16777077, 49, "dkBlue");
        DarkBlue = presetColor49;
        PresetColor presetColor50 = new PresetColor("DarkCyan", 49, -16741493, 50, "dkCyan");
        DarkCyan = presetColor50;
        PresetColor presetColor51 = new PresetColor("DarkGoldenrod", 50, -4684277, 51, "dkGoldenrod");
        DarkGoldenrod = presetColor51;
        PresetColor presetColor52 = new PresetColor("DarkGray", 51, -5658199, 52, "dkGray");
        DarkGray = presetColor52;
        PresetColor presetColor53 = new PresetColor("DarkGreen", 52, -16751616, 53, "dkGreen");
        DarkGreen = presetColor53;
        PresetColor presetColor54 = new PresetColor("DarkKhaki", 53, -4343957, 54, "dkKhaki");
        DarkKhaki = presetColor54;
        PresetColor presetColor55 = new PresetColor("DarkMagenta", 54, -7667573, 55, "dkMagenta");
        DarkMagenta = presetColor55;
        PresetColor presetColor56 = new PresetColor("DarkOliveGreen", 55, -11179217, 56, "dkOliveGreen");
        DarkOliveGreen = presetColor56;
        PresetColor presetColor57 = new PresetColor("DarkOrange", 56, -29696, 57, "dkOrange");
        DarkOrange = presetColor57;
        PresetColor presetColor58 = new PresetColor("DarkOrchid", 57, -6737204, 58, "dkOrchid");
        DarkOrchid = presetColor58;
        PresetColor presetColor59 = new PresetColor("DarkRed", 58, -7667712, 59, "dkRed");
        DarkRed = presetColor59;
        PresetColor presetColor60 = new PresetColor("DarkSalmon", 59, -1468806, 60, "dkSalmon");
        DarkSalmon = presetColor60;
        PresetColor presetColor61 = new PresetColor("DarkSeaGreen", 60, -7357301, 61, "dkSeaGreen");
        DarkSeaGreen = presetColor61;
        PresetColor presetColor62 = new PresetColor("DarkSlateBlue", 61, -12042869, 62, "dkSlateBlue");
        DarkSlateBlue = presetColor62;
        PresetColor presetColor63 = new PresetColor("DarkSlateGray", 62, -13676721, 63, "dkSlateGray");
        DarkSlateGray = presetColor63;
        PresetColor presetColor64 = new PresetColor("DarkTurquoise", 63, -16724271, 64, "dkTurquoise");
        DarkTurquoise = presetColor64;
        PresetColor presetColor65 = new PresetColor("DarkViolet", 64, -7077677, 65, "dkViolet");
        DarkViolet = presetColor65;
        PresetColor presetColor66 = new PresetColor("DeepPink", 65, -60269, 66, "deepPink");
        DeepPink = presetColor66;
        PresetColor presetColor67 = new PresetColor("DeepSkyBlue", 66, -16728065, 67, "deepSkyBlue");
        DeepSkyBlue = presetColor67;
        PresetColor presetColor68 = new PresetColor("DimGray", 67, -9868951, 68, "dimGray");
        DimGray = presetColor68;
        PresetColor presetColor69 = new PresetColor("DodgerBlue", 68, -14774017, 69, "dodgerBlue");
        DodgerBlue = presetColor69;
        PresetColor presetColor70 = new PresetColor("Firebrick", 69, -5103070, 70, "firebrick");
        Firebrick = presetColor70;
        PresetColor presetColor71 = new PresetColor("FloralWhite", 70, -1296, 71, "floralWhite");
        FloralWhite = presetColor71;
        PresetColor presetColor72 = new PresetColor("ForestGreen", 71, -14513374, 72, "forestGreen");
        ForestGreen = presetColor72;
        PresetColor presetColor73 = new PresetColor("Fuchsia", 72, -65281, 73, "fuchsia");
        Fuchsia = presetColor73;
        PresetColor presetColor74 = new PresetColor("Gainsboro", 73, -2302756, 74, "gainsboro");
        Gainsboro = presetColor74;
        PresetColor presetColor75 = new PresetColor("GhostWhite", 74, -460545, 75, "ghostWhite");
        GhostWhite = presetColor75;
        PresetColor presetColor76 = new PresetColor("Gold", 75, -10496, 76, "gold");
        Gold = presetColor76;
        PresetColor presetColor77 = new PresetColor("Goldenrod", 76, -2448096, 77, "goldenrod");
        Goldenrod = presetColor77;
        PresetColor presetColor78 = new PresetColor("Gray", 77, -8355712, 78, "gray");
        Gray = presetColor78;
        PresetColor presetColor79 = new PresetColor("Green", 78, -16744448, 79, "green");
        Green = presetColor79;
        PresetColor presetColor80 = new PresetColor("GreenYellow", 79, -5374161, 80, "greenYellow");
        GreenYellow = presetColor80;
        PresetColor presetColor81 = new PresetColor("Honeydew", 80, -983056, 81, "honeydew");
        Honeydew = presetColor81;
        PresetColor presetColor82 = new PresetColor("HotPink", 81, -38476, 82, "hotPink");
        HotPink = presetColor82;
        PresetColor presetColor83 = new PresetColor("IndianRed", 82, -3318692, 83, "indianRed");
        IndianRed = presetColor83;
        PresetColor presetColor84 = new PresetColor("Indigo", 83, -11861886, 84, "indigo");
        Indigo = presetColor84;
        PresetColor presetColor85 = new PresetColor("Ivory", 84, -16, 85, "ivory");
        Ivory = presetColor85;
        PresetColor presetColor86 = new PresetColor("Khaki", 85, -989556, 86, "khaki");
        Khaki = presetColor86;
        PresetColor presetColor87 = new PresetColor("Lavender", 86, -1644806, 87, "lavender");
        Lavender = presetColor87;
        PresetColor presetColor88 = new PresetColor("LavenderBlush", 87, -3851, 88, "lavenderBlush");
        LavenderBlush = presetColor88;
        PresetColor presetColor89 = new PresetColor("LawnGreen", 88, -8586240, 89, "lawnGreen");
        LawnGreen = presetColor89;
        PresetColor presetColor90 = new PresetColor("LemonChiffon", 89, -1331, 90, "lemonChiffon");
        LemonChiffon = presetColor90;
        PresetColor presetColor91 = new PresetColor("LightBlue", 90, -5383962, 91, "ltBlue");
        LightBlue = presetColor91;
        PresetColor presetColor92 = new PresetColor("LightCoral", 91, -1015680, 92, "ltCoral");
        LightCoral = presetColor92;
        PresetColor presetColor93 = new PresetColor("LightCyan", 92, -2031617, 93, "ltCyan");
        LightCyan = presetColor93;
        PresetColor presetColor94 = new PresetColor("LightGoldenrodYellow", 93, -329096, 94, "ltGoldenrodYellow");
        LightGoldenrodYellow = presetColor94;
        PresetColor presetColor95 = new PresetColor("LightGray", 94, -2894893, 95, "ltGray");
        LightGray = presetColor95;
        PresetColor presetColor96 = new PresetColor("LightGreen", 95, -7278960, 96, "ltGreen");
        LightGreen = presetColor96;
        PresetColor presetColor97 = new PresetColor("LightPink", 96, -18751, 97, "ltPink");
        LightPink = presetColor97;
        PresetColor presetColor98 = new PresetColor("LightSalmon", 97, -24454, 98, "ltSalmon");
        LightSalmon = presetColor98;
        PresetColor presetColor99 = new PresetColor("LightSeaGreen", 98, -14634326, 99, "ltSeaGreen");
        LightSeaGreen = presetColor99;
        PresetColor presetColor100 = new PresetColor("LightSkyBlue", 99, -7876870, 100, "ltSkyBlue");
        LightSkyBlue = presetColor100;
        PresetColor presetColor101 = new PresetColor("LightSlateGray", 100, -8943463, 101, "ltSlateGray");
        LightSlateGray = presetColor101;
        PresetColor presetColor102 = new PresetColor("LightSteelBlue", 101, -5192482, 102, "ltSteelBlue");
        LightSteelBlue = presetColor102;
        PresetColor presetColor103 = new PresetColor("LightYellow", 102, -32, 103, "ltYellow");
        LightYellow = presetColor103;
        PresetColor presetColor104 = new PresetColor("Lime", 103, -16711936, 104, "lime");
        Lime = presetColor104;
        PresetColor presetColor105 = new PresetColor("LimeGreen", 104, -13447886, 105, "limeGreen");
        LimeGreen = presetColor105;
        PresetColor presetColor106 = new PresetColor("Linen", 105, -331546, 106, "linen");
        Linen = presetColor106;
        PresetColor presetColor107 = new PresetColor("Magenta", 106, -65281, 107, "magenta");
        Magenta = presetColor107;
        PresetColor presetColor108 = new PresetColor("Maroon", 107, -8388608, 108, "maroon");
        Maroon = presetColor108;
        PresetColor presetColor109 = new PresetColor("MediumAquamarine", 108, -10039894, 109, "medAquamarine");
        MediumAquamarine = presetColor109;
        PresetColor presetColor110 = new PresetColor("MediumBlue", 109, -16777011, 110, "medBlue");
        MediumBlue = presetColor110;
        PresetColor presetColor111 = new PresetColor("MediumOrchid", 110, -4565549, 111, "medOrchid");
        MediumOrchid = presetColor111;
        PresetColor presetColor112 = new PresetColor("MediumPurple", 111, -7114533, 112, "medPurple");
        MediumPurple = presetColor112;
        PresetColor presetColor113 = new PresetColor("MediumSeaGreen", 112, -12799119, 113, "medSeaGreen");
        MediumSeaGreen = presetColor113;
        PresetColor presetColor114 = new PresetColor("MediumSlateBlue", 113, -8689426, 114, "medSlateBlue");
        MediumSlateBlue = presetColor114;
        PresetColor presetColor115 = new PresetColor("MediumSpringGreen", 114, -16713062, 115, "medSpringGreen");
        MediumSpringGreen = presetColor115;
        PresetColor presetColor116 = new PresetColor("MediumTurquoise", 115, -12004916, 116, "medTurquoise");
        MediumTurquoise = presetColor116;
        PresetColor presetColor117 = new PresetColor("MediumVioletRed", 116, -3730043, 117, "medVioletRed");
        MediumVioletRed = presetColor117;
        PresetColor presetColor118 = new PresetColor("MidnightBlue", 117, -15132304, 118, "midnightBlue");
        MidnightBlue = presetColor118;
        PresetColor presetColor119 = new PresetColor("MintCream", 118, -655366, 119, "mintCream");
        MintCream = presetColor119;
        PresetColor presetColor120 = new PresetColor("MistyRose", 119, -6943, 120, "mistyRose");
        MistyRose = presetColor120;
        PresetColor presetColor121 = new PresetColor("Moccasin", 120, -6987, 121, "moccasin");
        Moccasin = presetColor121;
        PresetColor presetColor122 = new PresetColor("NavajoWhite", 121, -8531, 122, "navajoWhite");
        NavajoWhite = presetColor122;
        PresetColor presetColor123 = new PresetColor("Navy", 122, -16777088, 123, "navy");
        Navy = presetColor123;
        PresetColor presetColor124 = new PresetColor("OldLace", 123, -133658, 124, "oldLace");
        OldLace = presetColor124;
        PresetColor presetColor125 = new PresetColor("Olive", 124, -8355840, 125, "olive");
        Olive = presetColor125;
        PresetColor presetColor126 = new PresetColor("OliveDrab", 125, -9728477, 126, "oliveDrab");
        OliveDrab = presetColor126;
        PresetColor presetColor127 = new PresetColor("Orange", 126, -23296, 127, "orange");
        Orange = presetColor127;
        PresetColor presetColor128 = new PresetColor("OrangeRed", 127, -47872, 128, "orangeRed");
        OrangeRed = presetColor128;
        PresetColor presetColor129 = new PresetColor("Orchid", 128, -2461482, 129, "orchid");
        Orchid = presetColor129;
        PresetColor presetColor130 = new PresetColor("PaleGoldenrod", 129, -1120086, 130, "paleGoldenrod");
        PaleGoldenrod = presetColor130;
        PresetColor presetColor131 = new PresetColor("PaleGreen", 130, -6751336, 131, "paleGreen");
        PaleGreen = presetColor131;
        PresetColor presetColor132 = new PresetColor("PaleTurquoise", 131, -5247250, 132, "paleTurquoise");
        PaleTurquoise = presetColor132;
        PresetColor presetColor133 = new PresetColor("PaleVioletRed", 132, -2396013, 133, "paleVioletRed");
        PaleVioletRed = presetColor133;
        PresetColor presetColor134 = new PresetColor("PapayaWhip", 133, -4139, 134, "papayaWhip");
        PapayaWhip = presetColor134;
        PresetColor presetColor135 = new PresetColor("PeachPuff", 134, -9543, 135, "peachPuff");
        PeachPuff = presetColor135;
        PresetColor presetColor136 = new PresetColor("Peru", 135, -3308225, 136, "peru");
        Peru = presetColor136;
        PresetColor presetColor137 = new PresetColor("Pink", 136, -16181, 137, "pink");
        Pink = presetColor137;
        PresetColor presetColor138 = new PresetColor("Plum", 137, -2252579, 138, "plum");
        Plum = presetColor138;
        PresetColor presetColor139 = new PresetColor("PowderBlue", 138, -5185306, 139, "powderBlue");
        PowderBlue = presetColor139;
        PresetColor presetColor140 = new PresetColor("Purple", 139, -8388480, 140, "purple");
        Purple = presetColor140;
        PresetColor presetColor141 = new PresetColor("Red", 140, Integer.valueOf(SupportMenu.CATEGORY_MASK), 141, "red");
        Red = presetColor141;
        PresetColor presetColor142 = new PresetColor("RosyBrown", 141, -4419697, 142, "rosyBrown");
        RosyBrown = presetColor142;
        PresetColor presetColor143 = new PresetColor("RoyalBlue", 142, -12490271, 143, "royalBlue");
        RoyalBlue = presetColor143;
        PresetColor presetColor144 = new PresetColor("SaddleBrown", 143, -7650029, 144, "saddleBrown");
        SaddleBrown = presetColor144;
        PresetColor presetColor145 = new PresetColor("Salmon", 144, -360334, 145, "salmon");
        Salmon = presetColor145;
        PresetColor presetColor146 = new PresetColor("SandyBrown", 145, -744352, 146, "sandyBrown");
        SandyBrown = presetColor146;
        PresetColor presetColor147 = new PresetColor("SeaGreen", 146, -13726889, 147, "seaGreen");
        SeaGreen = presetColor147;
        PresetColor presetColor148 = new PresetColor("SeaShell", 147, -2578, 148, "seaShell");
        SeaShell = presetColor148;
        PresetColor presetColor149 = new PresetColor("Sienna", 148, -6270419, 149, "sienna");
        Sienna = presetColor149;
        PresetColor presetColor150 = new PresetColor("Silver", 149, -4144960, 150, "silver");
        Silver = presetColor150;
        PresetColor presetColor151 = new PresetColor("SkyBlue", 150, -7876885, 151, "skyBlue");
        SkyBlue = presetColor151;
        PresetColor presetColor152 = new PresetColor("SlateBlue", 151, -9807155, 152, "slateBlue");
        SlateBlue = presetColor152;
        PresetColor presetColor153 = new PresetColor("SlateGray", 152, -9404272, 153, "slateGray");
        SlateGray = presetColor153;
        PresetColor presetColor154 = new PresetColor("Snow", 153, -1286, 154, "snow");
        Snow = presetColor154;
        PresetColor presetColor155 = new PresetColor("SpringGreen", 154, -16711809, 155, "springGreen");
        SpringGreen = presetColor155;
        PresetColor presetColor156 = new PresetColor("SteelBlue", 155, -12156236, 156, "steelBlue");
        SteelBlue = presetColor156;
        PresetColor presetColor157 = new PresetColor("Tan", 156, -2968436, 157, "tan");
        Tan = presetColor157;
        PresetColor presetColor158 = new PresetColor("Teal", 157, -16744320, 158, "teal");
        Teal = presetColor158;
        PresetColor presetColor159 = new PresetColor("Thistle", 158, -2572328, 159, "thistle");
        Thistle = presetColor159;
        PresetColor presetColor160 = new PresetColor("Tomato", 159, -40121, 160, "tomato");
        Tomato = presetColor160;
        PresetColor presetColor161 = new PresetColor("Turquoise", 160, -12525360, 161, "turquoise");
        Turquoise = presetColor161;
        PresetColor presetColor162 = new PresetColor("Violet", 161, -1146130, 162, "violet");
        Violet = presetColor162;
        PresetColor presetColor163 = new PresetColor("Wheat", 162, -663885, 163, "wheat");
        Wheat = presetColor163;
        PresetColor presetColor164 = new PresetColor("White", 163, -1, 164, "white");
        White = presetColor164;
        PresetColor presetColor165 = new PresetColor("WhiteSmoke", 164, -657931, 165, "whiteSmoke");
        WhiteSmoke = presetColor165;
        PresetColor presetColor166 = new PresetColor("Yellow", 165, Integer.valueOf(InputDeviceCompat.SOURCE_ANY), 166, "yellow");
        Yellow = presetColor166;
        PresetColor presetColor167 = new PresetColor("YellowGreen", 166, -6632142, 167, "yellowGreen");
        YellowGreen = presetColor167;
        PresetColor presetColor168 = new PresetColor("ButtonFace", 167, -986896, 168, null);
        ButtonFace = presetColor168;
        PresetColor presetColor169 = new PresetColor("ButtonHighlight", 168, -1, 169, null);
        ButtonHighlight = presetColor169;
        PresetColor presetColor170 = new PresetColor("ButtonShadow", 169, -6250336, 170, null);
        ButtonShadow = presetColor170;
        PresetColor presetColor171 = new PresetColor("GradientActiveCaption", 170, -4599318, 171, "gradientActiveCaption");
        GradientActiveCaption = presetColor171;
        PresetColor presetColor172 = new PresetColor("GradientInactiveCaption", 171, -2628366, 172, "gradientInactiveCaption");
        GradientInactiveCaption = presetColor172;
        PresetColor presetColor173 = new PresetColor("MenuBar", 172, -986896, 173, "menuBar");
        MenuBar = presetColor173;
        PresetColor presetColor174 = new PresetColor("MenuHighlight", 173, -13395457, 174, "menuHighlight");
        MenuHighlight = presetColor174;
        $VALUES = new PresetColor[]{presetColor, presetColor2, presetColor3, presetColor4, presetColor5, presetColor6, presetColor7, presetColor8, presetColor9, presetColor10, presetColor11, presetColor12, presetColor13, presetColor14, presetColor15, presetColor16, presetColor17, presetColor18, presetColor19, presetColor20, presetColor21, presetColor22, presetColor23, presetColor24, presetColor25, presetColor26, presetColor27, presetColor28, presetColor29, presetColor30, presetColor31, presetColor32, presetColor33, presetColor34, presetColor35, presetColor36, presetColor37, presetColor38, presetColor39, presetColor40, presetColor41, presetColor42, presetColor43, presetColor44, presetColor45, presetColor46, presetColor47, presetColor48, presetColor49, presetColor50, presetColor51, presetColor52, presetColor53, presetColor54, presetColor55, presetColor56, presetColor57, presetColor58, presetColor59, presetColor60, presetColor61, presetColor62, presetColor63, presetColor64, presetColor65, presetColor66, presetColor67, presetColor68, presetColor69, presetColor70, presetColor71, presetColor72, presetColor73, presetColor74, presetColor75, presetColor76, presetColor77, presetColor78, presetColor79, presetColor80, presetColor81, presetColor82, presetColor83, presetColor84, presetColor85, presetColor86, presetColor87, presetColor88, presetColor89, presetColor90, presetColor91, presetColor92, presetColor93, presetColor94, presetColor95, presetColor96, presetColor97, presetColor98, presetColor99, presetColor100, presetColor101, presetColor102, presetColor103, presetColor104, presetColor105, presetColor106, presetColor107, presetColor108, presetColor109, presetColor110, presetColor111, presetColor112, presetColor113, presetColor114, presetColor115, presetColor116, presetColor117, presetColor118, presetColor119, presetColor120, presetColor121, presetColor122, presetColor123, presetColor124, presetColor125, presetColor126, presetColor127, presetColor128, presetColor129, presetColor130, presetColor131, presetColor132, presetColor133, presetColor134, presetColor135, presetColor136, presetColor137, presetColor138, presetColor139, presetColor140, presetColor141, presetColor142, presetColor143, presetColor144, presetColor145, presetColor146, presetColor147, presetColor148, presetColor149, presetColor150, presetColor151, presetColor152, presetColor153, presetColor154, presetColor155, presetColor156, presetColor157, presetColor158, presetColor159, presetColor160, presetColor161, presetColor162, presetColor163, presetColor164, presetColor165, presetColor166, presetColor167, presetColor168, presetColor169, presetColor170, presetColor171, presetColor172, presetColor173, presetColor174};
        lookupOoxmlId = new HashMap();
        for (PresetColor presetColor175 : values()) {
            String str = presetColor175.ooxmlId;
            if (str != null) {
                lookupOoxmlId.put(str, presetColor175);
            }
        }
    }

    private PresetColor(String str, int i5, Integer num, int i6, String str2) {
        super(str, i5);
        this.color = num == null ? null : new Color(num.intValue(), true);
        this.nativeId = i6;
        this.ooxmlId = str2;
    }

    public static PresetColor valueOf(String str) {
        return (PresetColor) Enum.valueOf(PresetColor.class, str);
    }

    public static PresetColor valueOfNativeId(int i5) {
        PresetColor[] presetColorArrValues = values();
        if (i5 <= 0 || i5 > presetColorArrValues.length) {
            return null;
        }
        return presetColorArrValues[i5 - 1];
    }

    public static PresetColor valueOfOoxmlId(String str) {
        return lookupOoxmlId.get(str);
    }

    public static PresetColor[] values() {
        return (PresetColor[]) $VALUES.clone();
    }
}
