package com.google.android.gms.internal.mlkit_vision_text_common;

import com.google.android.gms.auth.api.accounttransfer.a;
import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import io.flutter.plugins.firebase.analytics.Constants;

/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes2.dex */
final class zzio implements ObjectEncoder {
    static final zzio zza = new zzio();
    private static final FieldDescriptor zzb = a.B(1, FieldDescriptor.builder("systemInfo"));
    private static final FieldDescriptor zzc = a.B(2, FieldDescriptor.builder(Constants.EVENT_NAME));
    private static final FieldDescriptor zzd = a.B(37, FieldDescriptor.builder("isThickClient"));
    private static final FieldDescriptor zze = a.B(61, FieldDescriptor.builder("clientType"));
    private static final FieldDescriptor zzf = a.B(3, FieldDescriptor.builder("modelDownloadLogEvent"));
    private static final FieldDescriptor zzg = a.B(20, FieldDescriptor.builder("customModelLoadLogEvent"));
    private static final FieldDescriptor zzh = a.B(4, FieldDescriptor.builder("customModelInferenceLogEvent"));
    private static final FieldDescriptor zzi = a.B(29, FieldDescriptor.builder("customModelCreateLogEvent"));
    private static final FieldDescriptor zzj = a.B(5, FieldDescriptor.builder("onDeviceFaceDetectionLogEvent"));
    private static final FieldDescriptor zzk = a.B(59, FieldDescriptor.builder("onDeviceFaceLoadLogEvent"));
    private static final FieldDescriptor zzl = a.B(6, FieldDescriptor.builder("onDeviceTextDetectionLogEvent"));
    private static final FieldDescriptor zzm = a.B(79, FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent"));
    private static final FieldDescriptor zzn = a.B(7, FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent"));
    private static final FieldDescriptor zzo = a.B(58, FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent"));
    private static final FieldDescriptor zzp = a.B(48, FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent"));
    private static final FieldDescriptor zzq = a.B(49, FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent"));
    private static final FieldDescriptor zzr = a.B(18, FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzs = a.B(26, FieldDescriptor.builder("onDeviceObjectCreateLogEvent"));
    private static final FieldDescriptor zzt = a.B(27, FieldDescriptor.builder("onDeviceObjectLoadLogEvent"));
    private static final FieldDescriptor zzu = a.B(28, FieldDescriptor.builder("onDeviceObjectInferenceLogEvent"));
    private static final FieldDescriptor zzv = a.B(44, FieldDescriptor.builder("onDevicePoseDetectionLogEvent"));
    private static final FieldDescriptor zzw = a.B(45, FieldDescriptor.builder("onDeviceSegmentationLogEvent"));
    private static final FieldDescriptor zzx = a.B(19, FieldDescriptor.builder("onDeviceSmartReplyLogEvent"));
    private static final FieldDescriptor zzy = a.B(21, FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent"));
    private static final FieldDescriptor zzz = a.B(22, FieldDescriptor.builder("onDeviceTranslationLogEvent"));
    private static final FieldDescriptor zzA = a.B(8, FieldDescriptor.builder("cloudFaceDetectionLogEvent"));
    private static final FieldDescriptor zzB = a.B(9, FieldDescriptor.builder("cloudCropHintDetectionLogEvent"));
    private static final FieldDescriptor zzC = a.B(10, FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent"));
    private static final FieldDescriptor zzD = a.B(11, FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent"));
    private static final FieldDescriptor zzE = a.B(12, FieldDescriptor.builder("cloudImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzF = a.B(13, FieldDescriptor.builder("cloudLandmarkDetectionLogEvent"));
    private static final FieldDescriptor zzG = a.B(14, FieldDescriptor.builder("cloudLogoDetectionLogEvent"));
    private static final FieldDescriptor zzH = a.B(15, FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent"));
    private static final FieldDescriptor zzI = a.B(16, FieldDescriptor.builder("cloudTextDetectionLogEvent"));
    private static final FieldDescriptor zzJ = a.B(17, FieldDescriptor.builder("cloudWebSearchDetectionLogEvent"));
    private static final FieldDescriptor zzK = a.B(23, FieldDescriptor.builder("automlImageLabelingCreateLogEvent"));
    private static final FieldDescriptor zzL = a.B(24, FieldDescriptor.builder("automlImageLabelingLoadLogEvent"));
    private static final FieldDescriptor zzM = a.B(25, FieldDescriptor.builder("automlImageLabelingInferenceLogEvent"));
    private static final FieldDescriptor zzN = a.B(39, FieldDescriptor.builder("isModelDownloadedLogEvent"));
    private static final FieldDescriptor zzO = a.B(40, FieldDescriptor.builder("deleteModelLogEvent"));
    private static final FieldDescriptor zzP = a.B(30, FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent"));
    private static final FieldDescriptor zzQ = a.B(31, FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent"));
    private static final FieldDescriptor zzR = a.B(32, FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent"));
    private static final FieldDescriptor zzS = a.B(33, FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent"));
    private static final FieldDescriptor zzT = a.B(34, FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzU = a.B(35, FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent"));
    private static final FieldDescriptor zzV = a.B(36, FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent"));
    private static final FieldDescriptor zzW = a.B(46, FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent"));
    private static final FieldDescriptor zzX = a.B(47, FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent"));
    private static final FieldDescriptor zzY = a.B(69, FieldDescriptor.builder("pipelineAccelerationInferenceEvents"));
    private static final FieldDescriptor zzZ = a.B(42, FieldDescriptor.builder("remoteConfigLogEvent"));
    private static final FieldDescriptor zzaa = a.B(50, FieldDescriptor.builder("inputImageConstructionLogEvent"));
    private static final FieldDescriptor zzab = a.B(51, FieldDescriptor.builder("leakedHandleEvent"));
    private static final FieldDescriptor zzac = a.B(52, FieldDescriptor.builder("cameraSourceLogEvent"));
    private static final FieldDescriptor zzad = a.B(53, FieldDescriptor.builder("imageLabelOptionalModuleLogEvent"));
    private static final FieldDescriptor zzae = a.B(54, FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaf = a.B(60, FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzag = a.B(85, FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzah = a.B(86, FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent"));
    private static final FieldDescriptor zzai = a.B(87, FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaj = a.B(55, FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent"));
    private static final FieldDescriptor zzak = a.B(56, FieldDescriptor.builder("nlClassifierClientLibraryLogEvent"));
    private static final FieldDescriptor zzal = a.B(57, FieldDescriptor.builder("accelerationAllowlistLogEvent"));
    private static final FieldDescriptor zzam = a.B(62, FieldDescriptor.builder("toxicityDetectionCreateEvent"));
    private static final FieldDescriptor zzan = a.B(63, FieldDescriptor.builder("toxicityDetectionLoadEvent"));
    private static final FieldDescriptor zzao = a.B(64, FieldDescriptor.builder("toxicityDetectionInferenceEvent"));
    private static final FieldDescriptor zzap = a.B(65, FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaq = a.B(66, FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent"));
    private static final FieldDescriptor zzar = a.B(67, FieldDescriptor.builder("codeScannerScanApiEvent"));
    private static final FieldDescriptor zzas = a.B(68, FieldDescriptor.builder("codeScannerOptionalModuleEvent"));
    private static final FieldDescriptor zzat = a.B(70, FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent"));
    private static final FieldDescriptor zzau = a.B(71, FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent"));
    private static final FieldDescriptor zzav = a.B(72, FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent"));
    private static final FieldDescriptor zzaw = a.B(73, FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent"));
    private static final FieldDescriptor zzax = a.B(74, FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent"));
    private static final FieldDescriptor zzay = a.B(75, FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent"));
    private static final FieldDescriptor zzaz = a.B(76, FieldDescriptor.builder("onDeviceFaceMeshLogEvent"));
    private static final FieldDescriptor zzaA = a.B(77, FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent"));
    private static final FieldDescriptor zzaB = a.B(78, FieldDescriptor.builder("smartReplyOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaC = a.B(80, FieldDescriptor.builder("textDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaD = a.B(81, FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent"));
    private static final FieldDescriptor zzaE = a.B(82, FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent"));
    private static final FieldDescriptor zzaF = a.B(83, FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent"));
    private static final FieldDescriptor zzaG = a.B(84, FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent"));
    private static final FieldDescriptor zzaH = a.B(88, FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaI = a.B(89, FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaJ = a.B(90, FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent"));
    private static final FieldDescriptor zzaK = a.B(91, FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent"));
    private static final FieldDescriptor zzaL = a.B(92, FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent"));
    private static final FieldDescriptor zzaM = a.B(93, FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent"));
    private static final FieldDescriptor zzaN = a.B(94, FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent"));
    private static final FieldDescriptor zzaO = a.B(95, FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent"));
    private static final FieldDescriptor zzaP = a.B(96, FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent"));
    private static final FieldDescriptor zzaQ = a.B(97, FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent"));
    private static final FieldDescriptor zzaR = a.B(98, FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent"));
    private static final FieldDescriptor zzaS = a.B(99, FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent"));
    private static final FieldDescriptor zzaT = a.B(100, FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent"));
    private static final FieldDescriptor zzaU = a.B(101, FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent"));
    private static final FieldDescriptor zzaV = a.B(102, FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent"));
    private static final FieldDescriptor zzaW = a.B(103, FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent"));
    private static final FieldDescriptor zzaX = a.B(104, FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent"));
    private static final FieldDescriptor zzaY = a.B(105, FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent"));
    private static final FieldDescriptor zzaZ = a.B(106, FieldDescriptor.builder("scannerAutoZoomEvent"));
    private static final FieldDescriptor zzba = a.B(107, FieldDescriptor.builder("lowLightAutoExposureComputationEvent"));
    private static final FieldDescriptor zzbb = a.B(108, FieldDescriptor.builder("lowLightFrameProcessEvent"));
    private static final FieldDescriptor zzbc = a.B(109, FieldDescriptor.builder("lowLightSceneDetectionEvent"));
    private static final FieldDescriptor zzbd = a.B(110, FieldDescriptor.builder("onDeviceStainRemovalLogEvent"));
    private static final FieldDescriptor zzbe = a.B(111, FieldDescriptor.builder("aggregatedOnDeviceStainRemovalLogEvent"));
    private static final FieldDescriptor zzbf = a.B(112, FieldDescriptor.builder("stainRemovalOptionalModuleLogEvent"));
    private static final FieldDescriptor zzbg = a.B(113, FieldDescriptor.builder("onDeviceShadowRemovalLogEvent"));
    private static final FieldDescriptor zzbh = a.B(114, FieldDescriptor.builder("aggregatedOnDeviceShadowRemovalLogEvent"));
    private static final FieldDescriptor zzbi = a.B(115, FieldDescriptor.builder("shadowRemovalOptionalModuleLogEvent"));
    private static final FieldDescriptor zzbj = a.B(116, FieldDescriptor.builder("onDeviceDigitalInkSegmentationLogEvent"));
    private static final FieldDescriptor zzbk = a.B(117, FieldDescriptor.builder("onDeviceDocumentScannerStartLogEvent"));
    private static final FieldDescriptor zzbl = a.B(118, FieldDescriptor.builder("onDeviceDocumentScannerFinishLogEvent"));
    private static final FieldDescriptor zzbm = a.B(119, FieldDescriptor.builder("onDeviceDocumentScannerUiStartLogEvent"));
    private static final FieldDescriptor zzbn = a.B(120, FieldDescriptor.builder("onDeviceDocumentScannerUiFinishLogEvent"));
    private static final FieldDescriptor zzbo = a.B(121, FieldDescriptor.builder("documentScannerUiOptionalModuleSessionStartLogEvent"));
    private static final FieldDescriptor zzbp = a.B(122, FieldDescriptor.builder("documentScannerUiOptionalModuleSessionFinishLogEvent"));
    private static final FieldDescriptor zzbq = a.B(123, FieldDescriptor.builder("onDeviceDocumentScannerUiCreateLogEvent"));
    private static final FieldDescriptor zzbr = a.B(124, FieldDescriptor.builder("onDeviceSubjectSegmentationCreateLogEvent"));
    private static final FieldDescriptor zzbs = a.B(125, FieldDescriptor.builder("onDeviceSubjectSegmentationLoadLogEvent"));
    private static final FieldDescriptor zzbt = a.B(126, FieldDescriptor.builder("onDeviceSubjectSegmentationInferenceLogEvent"));
    private static final FieldDescriptor zzbu = a.B(127, FieldDescriptor.builder("aggregatedOnDeviceSubjectSegmentationLogEvent"));
    private static final FieldDescriptor zzbv = a.B(128, FieldDescriptor.builder("subjectSegmentationOptionalModuleLogEvent"));
    private static final FieldDescriptor zzbw = a.B(129, FieldDescriptor.builder("documentScannerUiModuleScreenViewEvent"));
    private static final FieldDescriptor zzbx = a.B(130, FieldDescriptor.builder("documentScannerUiModuleScreenClickEvent"));
    private static final FieldDescriptor zzby = a.B(131, FieldDescriptor.builder("documentScannerUiModuleScreenErrorEvent"));

    private zzio() {
    }

    @Override // com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) {
        zzoy zzoyVar = (zzoy) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzoyVar.zzf());
        objectEncoderContext2.add(zzc, zzoyVar.zzc());
        objectEncoderContext2.add(zzd, (Object) null);
        objectEncoderContext2.add(zze, zzoyVar.zzb());
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, (Object) null);
        objectEncoderContext2.add(zzl, zzoyVar.zze());
        objectEncoderContext2.add(zzm, zzoyVar.zzd());
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, (Object) null);
        objectEncoderContext2.add(zzt, (Object) null);
        objectEncoderContext2.add(zzu, (Object) null);
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, (Object) null);
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, (Object) null);
        objectEncoderContext2.add(zzV, zzoyVar.zza());
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, (Object) null);
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
        objectEncoderContext2.add(zzag, (Object) null);
        objectEncoderContext2.add(zzah, (Object) null);
        objectEncoderContext2.add(zzai, (Object) null);
        objectEncoderContext2.add(zzaj, (Object) null);
        objectEncoderContext2.add(zzak, (Object) null);
        objectEncoderContext2.add(zzal, (Object) null);
        objectEncoderContext2.add(zzam, (Object) null);
        objectEncoderContext2.add(zzan, (Object) null);
        objectEncoderContext2.add(zzao, (Object) null);
        objectEncoderContext2.add(zzap, (Object) null);
        objectEncoderContext2.add(zzaq, (Object) null);
        objectEncoderContext2.add(zzar, (Object) null);
        objectEncoderContext2.add(zzas, (Object) null);
        objectEncoderContext2.add(zzat, (Object) null);
        objectEncoderContext2.add(zzau, (Object) null);
        objectEncoderContext2.add(zzav, (Object) null);
        objectEncoderContext2.add(zzaw, (Object) null);
        objectEncoderContext2.add(zzax, (Object) null);
        objectEncoderContext2.add(zzay, (Object) null);
        objectEncoderContext2.add(zzaz, (Object) null);
        objectEncoderContext2.add(zzaA, (Object) null);
        objectEncoderContext2.add(zzaB, (Object) null);
        objectEncoderContext2.add(zzaC, (Object) null);
        objectEncoderContext2.add(zzaD, (Object) null);
        objectEncoderContext2.add(zzaE, (Object) null);
        objectEncoderContext2.add(zzaF, (Object) null);
        objectEncoderContext2.add(zzaG, (Object) null);
        objectEncoderContext2.add(zzaH, (Object) null);
        objectEncoderContext2.add(zzaI, (Object) null);
        objectEncoderContext2.add(zzaJ, (Object) null);
        objectEncoderContext2.add(zzaK, (Object) null);
        objectEncoderContext2.add(zzaL, (Object) null);
        objectEncoderContext2.add(zzaM, (Object) null);
        objectEncoderContext2.add(zzaN, (Object) null);
        objectEncoderContext2.add(zzaO, (Object) null);
        objectEncoderContext2.add(zzaP, (Object) null);
        objectEncoderContext2.add(zzaQ, (Object) null);
        objectEncoderContext2.add(zzaR, (Object) null);
        objectEncoderContext2.add(zzaS, (Object) null);
        objectEncoderContext2.add(zzaT, (Object) null);
        objectEncoderContext2.add(zzaU, (Object) null);
        objectEncoderContext2.add(zzaV, (Object) null);
        objectEncoderContext2.add(zzaW, (Object) null);
        objectEncoderContext2.add(zzaX, (Object) null);
        objectEncoderContext2.add(zzaY, (Object) null);
        objectEncoderContext2.add(zzaZ, (Object) null);
        objectEncoderContext2.add(zzba, (Object) null);
        objectEncoderContext2.add(zzbb, (Object) null);
        objectEncoderContext2.add(zzbc, (Object) null);
        objectEncoderContext2.add(zzbd, (Object) null);
        objectEncoderContext2.add(zzbe, (Object) null);
        objectEncoderContext2.add(zzbf, (Object) null);
        objectEncoderContext2.add(zzbg, (Object) null);
        objectEncoderContext2.add(zzbh, (Object) null);
        objectEncoderContext2.add(zzbi, (Object) null);
        objectEncoderContext2.add(zzbj, (Object) null);
        objectEncoderContext2.add(zzbk, (Object) null);
        objectEncoderContext2.add(zzbl, (Object) null);
        objectEncoderContext2.add(zzbm, (Object) null);
        objectEncoderContext2.add(zzbn, (Object) null);
        objectEncoderContext2.add(zzbo, (Object) null);
        objectEncoderContext2.add(zzbp, (Object) null);
        objectEncoderContext2.add(zzbq, (Object) null);
        objectEncoderContext2.add(zzbr, (Object) null);
        objectEncoderContext2.add(zzbs, (Object) null);
        objectEncoderContext2.add(zzbt, (Object) null);
        objectEncoderContext2.add(zzbu, (Object) null);
        objectEncoderContext2.add(zzbv, (Object) null);
        objectEncoderContext2.add(zzbw, (Object) null);
        objectEncoderContext2.add(zzbx, (Object) null);
        objectEncoderContext2.add(zzby, (Object) null);
    }
}
