package org.apache.poi.hssf.record.chart;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Supplier;
import org.apache.poi.hssf.record.HSSFRecordTypes;
import org.apache.poi.hssf.record.RecordInputStream;
import org.apache.poi.hssf.record.StandardRecord;
import org.apache.poi.ss.util.CellUtil;
import org.apache.poi.util.BitField;
import org.apache.poi.util.BitFieldFactory;
import org.apache.poi.util.GenericRecordUtil;
import org.apache.poi.util.LittleEndianOutput;

/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes4.dex */
public final class TextRecord extends StandardRecord {
    public static final short DATA_LABEL_PLACEMENT_ABOVE = 5;
    public static final short DATA_LABEL_PLACEMENT_AUTO = 9;
    public static final short DATA_LABEL_PLACEMENT_AXIS = 4;
    public static final short DATA_LABEL_PLACEMENT_BELOW = 6;
    public static final short DATA_LABEL_PLACEMENT_CENTER = 3;
    public static final short DATA_LABEL_PLACEMENT_CHART_DEPENDENT = 0;
    public static final short DATA_LABEL_PLACEMENT_INSIDE = 2;
    public static final short DATA_LABEL_PLACEMENT_LEFT = 7;
    public static final short DATA_LABEL_PLACEMENT_OUTSIDE = 1;
    public static final short DATA_LABEL_PLACEMENT_RIGHT = 8;
    public static final short DATA_LABEL_PLACEMENT_USER_MOVED = 10;
    public static final short DISPLAY_MODE_OPAQUE = 2;
    public static final short DISPLAY_MODE_TRANSPARENT = 1;
    public static final byte HORIZONTAL_ALIGNMENT_BOTTOM = 3;
    public static final byte HORIZONTAL_ALIGNMENT_CENTER = 2;
    public static final byte HORIZONTAL_ALIGNMENT_JUSTIFY = 4;
    public static final byte HORIZONTAL_ALIGNMENT_LEFT = 1;
    public static final short ROTATION_NONE = 0;
    public static final short ROTATION_ROTATED_90_DEGREES = 2;
    public static final short ROTATION_ROTATED_90_DEGREES_CLOCKWISE = 3;
    public static final short ROTATION_TOP_TO_BOTTOM = 1;
    public static final byte VERTICAL_ALIGNMENT_BOTTOM = 3;
    public static final byte VERTICAL_ALIGNMENT_CENTER = 2;
    public static final byte VERTICAL_ALIGNMENT_JUSTIFY = 4;
    public static final byte VERTICAL_ALIGNMENT_TOP = 1;
    public static final short sid = 4133;
    private short field_10_indexOfColorValue;
    private short field_11_options2;
    private short field_12_textRotation;
    private byte field_1_horizontalAlignment;
    private byte field_2_verticalAlignment;
    private short field_3_displayMode;
    private int field_4_rgbColor;
    private int field_5_x;
    private int field_6_y;
    private int field_7_width;
    private int field_8_height;
    private short field_9_options1;
    private static final BitField dataLabelPlacement = BitFieldFactory.getInstance(15);
    private static final BitField autoColor = BitFieldFactory.getInstance(1);
    private static final BitField showKey = BitFieldFactory.getInstance(2);
    private static final BitField showValue = BitFieldFactory.getInstance(4);
    private static final BitField vertical = BitFieldFactory.getInstance(8);
    private static final BitField autoGeneratedText = BitFieldFactory.getInstance(16);
    private static final BitField generated = BitFieldFactory.getInstance(32);
    private static final BitField autoLabelDeleted = BitFieldFactory.getInstance(64);
    private static final BitField autoBackground = BitFieldFactory.getInstance(128);
    private static final BitField rotation = BitFieldFactory.getInstance(1792);
    private static final BitField showCategoryLabelAsPercentage = BitFieldFactory.getInstance(2048);
    private static final BitField showValueAsPercentage = BitFieldFactory.getInstance(4096);
    private static final BitField showBubbleSizes = BitFieldFactory.getInstance(8192);
    private static final BitField showLabel = BitFieldFactory.getInstance(16384);

    public TextRecord() {
    }

    public short getDataLabelPlacement() {
        return dataLabelPlacement.getShortValue(this.field_11_options2);
    }

    @Override // org.apache.poi.hssf.record.StandardRecord
    public int getDataSize() {
        return 32;
    }

    public short getDisplayMode() {
        return this.field_3_displayMode;
    }

    @Override // org.apache.poi.common.usermodel.GenericRecord
    public Map<String, Supplier<?>> getGenericProperties() {
        LinkedHashMap linkedHashMap = new LinkedHashMap();
        final int i5 = 0;
        final int i6 = 1;
        final int i7 = 2;
        final int i8 = 3;
        final int i9 = 4;
        linkedHashMap.put("horizontalAlignment", GenericRecordUtil.getEnumBitsAsString(new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i5) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        }, new int[]{1, 2, 3, 4}, new String[]{"LEFT", "CENTER", "BOTTOM", "JUSTIFY"}));
        final int i10 = 9;
        linkedHashMap.put(CellUtil.VERTICAL_ALIGNMENT, GenericRecordUtil.getEnumBitsAsString(new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i10) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        }, new int[]{1, 2, 3, 4}, new String[]{"TOP", "CENTER", "BOTTOM", "JUSTIFY"}));
        final int i11 = 10;
        linkedHashMap.put("displayMode", GenericRecordUtil.getEnumBitsAsString(new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i11) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        }, new int[]{1, 2}, new String[]{"TRANSPARENT", "OPAQUE"}));
        final int i12 = 11;
        linkedHashMap.put("rgbColor", new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i12) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        });
        final int i13 = 12;
        linkedHashMap.put("x", new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i13) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        });
        final int i14 = 13;
        linkedHashMap.put("y", new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i14) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        });
        linkedHashMap.put("width", new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i6) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        });
        linkedHashMap.put("height", new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i7) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        });
        linkedHashMap.put("options1", GenericRecordUtil.getBitsAsString((Supplier<Number>) new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i8) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        }, new BitField[]{autoColor, showKey, showValue, vertical, autoGeneratedText, generated, autoLabelDeleted, autoBackground, showCategoryLabelAsPercentage, showValueAsPercentage, showBubbleSizes, showLabel}, new String[]{"AUTO_COLOR", "SHOW_KEY", "SHOW_VALUE", "VERTICAL", "AUTO_GENERATED_TEXT", "GENERATED", "AUTO_LABEL_DELETED", "AUTO_BACKGROUND", "SHOW_CATEGORY_LABEL_AS_PERCENTAGE", "SHOW_VALUE_AS_PERCENTAGE", "SHOW_BUBBLE_SIZES", "SHOW_LABEL"}));
        linkedHashMap.put("rotation", GenericRecordUtil.getEnumBitsAsString(new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i9) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        }, new int[]{0, 1, 2, 3}, new String[]{"NONE", "TOP_TO_BOTTOM", "ROTATED_90_DEGREES", "ROTATED_90_DEGREES_CLOCKWISE"}));
        final int i15 = 5;
        linkedHashMap.put("options2", new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i15) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        });
        final int i16 = 6;
        linkedHashMap.put("dataLabelPlacement", GenericRecordUtil.getEnumBitsAsString(new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i16) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        }, new int[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, new String[]{"CHART_DEPENDENT", "OUTSIDE", "INSIDE", "CENTER", "AXIS", "ABOVE", "BELOW", "LEFT", "RIGHT", "AUTO", "USER_MOVED"}));
        final int i17 = 7;
        linkedHashMap.put("indexOfColorValue", new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i17) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        });
        final int i18 = 8;
        linkedHashMap.put("textRotation", new Supplier(this) { // from class: org.apache.poi.hssf.record.chart.G
            public final /* synthetic */ TextRecord b;

            {
                this.b = this;
            }

            @Override // java.util.function.Supplier
            public final Object get() {
                switch (i18) {
                    case 0:
                        return Byte.valueOf(this.b.getHorizontalAlignment());
                    case 1:
                        return Integer.valueOf(this.b.getWidth());
                    case 2:
                        return Integer.valueOf(this.b.getHeight());
                    case 3:
                        return Short.valueOf(this.b.getOptions1());
                    case 4:
                        return Short.valueOf(this.b.getRotation());
                    case 5:
                        return Short.valueOf(this.b.getOptions2());
                    case 6:
                        return Short.valueOf(this.b.getDataLabelPlacement());
                    case 7:
                        return Short.valueOf(this.b.getIndexOfColorValue());
                    case 8:
                        return Short.valueOf(this.b.getTextRotation());
                    case 9:
                        return Byte.valueOf(this.b.getVerticalAlignment());
                    case 10:
                        return Short.valueOf(this.b.getDisplayMode());
                    case 11:
                        return Integer.valueOf(this.b.getRgbColor());
                    case 12:
                        return Integer.valueOf(this.b.getX());
                    default:
                        return Integer.valueOf(this.b.getY());
                }
            }
        });
        return Collections.unmodifiableMap(linkedHashMap);
    }

    public int getHeight() {
        return this.field_8_height;
    }

    public byte getHorizontalAlignment() {
        return this.field_1_horizontalAlignment;
    }

    public short getIndexOfColorValue() {
        return this.field_10_indexOfColorValue;
    }

    public short getOptions1() {
        return this.field_9_options1;
    }

    public short getOptions2() {
        return this.field_11_options2;
    }

    public int getRgbColor() {
        return this.field_4_rgbColor;
    }

    public short getRotation() {
        return rotation.getShortValue(this.field_9_options1);
    }

    @Override // org.apache.poi.hssf.record.Record
    public short getSid() {
        return sid;
    }

    public short getTextRotation() {
        return this.field_12_textRotation;
    }

    public byte getVerticalAlignment() {
        return this.field_2_verticalAlignment;
    }

    public int getWidth() {
        return this.field_7_width;
    }

    public int getX() {
        return this.field_5_x;
    }

    public int getY() {
        return this.field_6_y;
    }

    public boolean isAutoBackground() {
        return autoBackground.isSet(this.field_9_options1);
    }

    public boolean isAutoColor() {
        return autoColor.isSet(this.field_9_options1);
    }

    public boolean isAutoGeneratedText() {
        return autoGeneratedText.isSet(this.field_9_options1);
    }

    public boolean isAutoLabelDeleted() {
        return autoLabelDeleted.isSet(this.field_9_options1);
    }

    public boolean isGenerated() {
        return generated.isSet(this.field_9_options1);
    }

    public boolean isShowBubbleSizes() {
        return showBubbleSizes.isSet(this.field_9_options1);
    }

    public boolean isShowCategoryLabelAsPercentage() {
        return showCategoryLabelAsPercentage.isSet(this.field_9_options1);
    }

    public boolean isShowKey() {
        return showKey.isSet(this.field_9_options1);
    }

    public boolean isShowLabel() {
        return showLabel.isSet(this.field_9_options1);
    }

    public boolean isShowValue() {
        return showValue.isSet(this.field_9_options1);
    }

    public boolean isShowValueAsPercentage() {
        return showValueAsPercentage.isSet(this.field_9_options1);
    }

    public boolean isVertical() {
        return vertical.isSet(this.field_9_options1);
    }

    @Override // org.apache.poi.hssf.record.StandardRecord
    public void serialize(LittleEndianOutput littleEndianOutput) {
        littleEndianOutput.writeByte(this.field_1_horizontalAlignment);
        littleEndianOutput.writeByte(this.field_2_verticalAlignment);
        littleEndianOutput.writeShort(this.field_3_displayMode);
        littleEndianOutput.writeInt(this.field_4_rgbColor);
        littleEndianOutput.writeInt(this.field_5_x);
        littleEndianOutput.writeInt(this.field_6_y);
        littleEndianOutput.writeInt(this.field_7_width);
        littleEndianOutput.writeInt(this.field_8_height);
        littleEndianOutput.writeShort(this.field_9_options1);
        littleEndianOutput.writeShort(this.field_10_indexOfColorValue);
        littleEndianOutput.writeShort(this.field_11_options2);
        littleEndianOutput.writeShort(this.field_12_textRotation);
    }

    public void setAutoBackground(boolean z6) {
        this.field_9_options1 = autoBackground.setShortBoolean(this.field_9_options1, z6);
    }

    public void setAutoColor(boolean z6) {
        this.field_9_options1 = autoColor.setShortBoolean(this.field_9_options1, z6);
    }

    public void setAutoGeneratedText(boolean z6) {
        this.field_9_options1 = autoGeneratedText.setShortBoolean(this.field_9_options1, z6);
    }

    public void setAutoLabelDeleted(boolean z6) {
        this.field_9_options1 = autoLabelDeleted.setShortBoolean(this.field_9_options1, z6);
    }

    public void setDataLabelPlacement(short s6) {
        this.field_11_options2 = dataLabelPlacement.setShortValue(this.field_11_options2, s6);
    }

    public void setDisplayMode(short s6) {
        this.field_3_displayMode = s6;
    }

    public void setGenerated(boolean z6) {
        this.field_9_options1 = generated.setShortBoolean(this.field_9_options1, z6);
    }

    public void setHeight(int i5) {
        this.field_8_height = i5;
    }

    public void setHorizontalAlignment(byte b) {
        this.field_1_horizontalAlignment = b;
    }

    public void setIndexOfColorValue(short s6) {
        this.field_10_indexOfColorValue = s6;
    }

    public void setOptions1(short s6) {
        this.field_9_options1 = s6;
    }

    public void setOptions2(short s6) {
        this.field_11_options2 = s6;
    }

    public void setRgbColor(int i5) {
        this.field_4_rgbColor = i5;
    }

    public void setRotation(short s6) {
        this.field_9_options1 = rotation.setShortValue(this.field_9_options1, s6);
    }

    public void setShowBubbleSizes(boolean z6) {
        this.field_9_options1 = showBubbleSizes.setShortBoolean(this.field_9_options1, z6);
    }

    public void setShowCategoryLabelAsPercentage(boolean z6) {
        this.field_9_options1 = showCategoryLabelAsPercentage.setShortBoolean(this.field_9_options1, z6);
    }

    public void setShowKey(boolean z6) {
        this.field_9_options1 = showKey.setShortBoolean(this.field_9_options1, z6);
    }

    public void setShowLabel(boolean z6) {
        this.field_9_options1 = showLabel.setShortBoolean(this.field_9_options1, z6);
    }

    public void setShowValue(boolean z6) {
        this.field_9_options1 = showValue.setShortBoolean(this.field_9_options1, z6);
    }

    public void setShowValueAsPercentage(boolean z6) {
        this.field_9_options1 = showValueAsPercentage.setShortBoolean(this.field_9_options1, z6);
    }

    public void setTextRotation(short s6) {
        this.field_12_textRotation = s6;
    }

    public void setVertical(boolean z6) {
        this.field_9_options1 = vertical.setShortBoolean(this.field_9_options1, z6);
    }

    public void setVerticalAlignment(byte b) {
        this.field_2_verticalAlignment = b;
    }

    public void setWidth(int i5) {
        this.field_7_width = i5;
    }

    public void setX(int i5) {
        this.field_5_x = i5;
    }

    public void setY(int i5) {
        this.field_6_y = i5;
    }

    public TextRecord(TextRecord textRecord) {
        super(textRecord);
        this.field_1_horizontalAlignment = textRecord.field_1_horizontalAlignment;
        this.field_2_verticalAlignment = textRecord.field_2_verticalAlignment;
        this.field_3_displayMode = textRecord.field_3_displayMode;
        this.field_4_rgbColor = textRecord.field_4_rgbColor;
        this.field_5_x = textRecord.field_5_x;
        this.field_6_y = textRecord.field_6_y;
        this.field_7_width = textRecord.field_7_width;
        this.field_8_height = textRecord.field_8_height;
        this.field_9_options1 = textRecord.field_9_options1;
        this.field_10_indexOfColorValue = textRecord.field_10_indexOfColorValue;
        this.field_11_options2 = textRecord.field_11_options2;
        this.field_12_textRotation = textRecord.field_12_textRotation;
    }

    @Override // org.apache.poi.hssf.record.Record, org.apache.poi.common.usermodel.GenericRecord
    public HSSFRecordTypes getGenericRecordType() {
        return HSSFRecordTypes.TEXT;
    }

    @Override // org.apache.poi.hssf.record.StandardRecord, org.apache.poi.hssf.record.Record, org.apache.poi.common.Duplicatable
    public TextRecord copy() {
        return new TextRecord(this);
    }

    public TextRecord(RecordInputStream recordInputStream) {
        this.field_1_horizontalAlignment = recordInputStream.readByte();
        this.field_2_verticalAlignment = recordInputStream.readByte();
        this.field_3_displayMode = recordInputStream.readShort();
        this.field_4_rgbColor = recordInputStream.readInt();
        this.field_5_x = recordInputStream.readInt();
        this.field_6_y = recordInputStream.readInt();
        this.field_7_width = recordInputStream.readInt();
        this.field_8_height = recordInputStream.readInt();
        this.field_9_options1 = recordInputStream.readShort();
        this.field_10_indexOfColorValue = recordInputStream.readShort();
        this.field_11_options2 = recordInputStream.readShort();
        this.field_12_textRotation = recordInputStream.readShort();
    }
}
