package org.apache.poi.xssf.usermodel;

/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes4.dex */
public enum ListAutoNumber {
    ALPHA_LC_PARENT_BOTH,
    ALPHA_UC_PARENT_BOTH,
    ALPHA_LC_PARENT_R,
    ALPHA_UC_PARENT_R,
    ALPHA_LC_PERIOD,
    ALPHA_UC_PERIOD,
    ARABIC_PARENT_BOTH,
    ARABIC_PARENT_R,
    ARABIC_PERIOD,
    ARABIC_PLAIN,
    ROMAN_LC_PARENT_BOTH,
    ROMAN_UC_PARENT_BOTH,
    ROMAN_LC_PARENT_R,
    ROMAN_UC_PARENT_R,
    ROMAN_LC_PERIOD,
    ROMAN_UC_PERIOD,
    CIRCLE_NUM_DB_PLAIN,
    CIRCLE_NUM_WD_BLACK_PLAIN,
    CIRCLE_NUM_WD_WHITE_PLAIN
}
