package org.openxmlformats.schemas.wordprocessingml.x2006.main;

import org.apache.poi.schemas.ooxml.system.ooxml.TypeSystemHolder;
import org.apache.xmlbeans.SchemaType;
import org.apache.xmlbeans.StringEnumAbstractBase;
import org.apache.xmlbeans.XmlErrorCodes;
import org.apache.xmlbeans.XmlString;
import org.apache.xmlbeans.impl.schema.SimpleTypeFactory;

/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes6.dex */
public interface STNumberFormat extends XmlString {
    public static final Enum AIUEO;
    public static final Enum AIUEO_FULL_WIDTH;
    public static final Enum ARABIC_ABJAD;
    public static final Enum ARABIC_ALPHA;
    public static final Enum BAHT_TEXT;
    public static final Enum BULLET;
    public static final Enum CARDINAL_TEXT;
    public static final Enum CHICAGO;
    public static final Enum CHINESE_COUNTING;
    public static final Enum CHINESE_COUNTING_THOUSAND;
    public static final Enum CHINESE_LEGAL_SIMPLIFIED;
    public static final Enum CHOSUNG;
    public static final Enum CUSTOM;
    public static final Enum DECIMAL;
    public static final Enum DECIMAL_ENCLOSED_CIRCLE;
    public static final Enum DECIMAL_ENCLOSED_CIRCLE_CHINESE;
    public static final Enum DECIMAL_ENCLOSED_FULLSTOP;
    public static final Enum DECIMAL_ENCLOSED_PAREN;
    public static final Enum DECIMAL_FULL_WIDTH;
    public static final Enum DECIMAL_FULL_WIDTH_2;
    public static final Enum DECIMAL_HALF_WIDTH;
    public static final Enum DECIMAL_ZERO;
    public static final Enum DOLLAR_TEXT;
    public static final SimpleTypeFactory<STNumberFormat> Factory;
    public static final Enum GANADA;
    public static final Enum HEBREW_1;
    public static final Enum HEBREW_2;
    public static final Enum HEX;
    public static final Enum HINDI_CONSONANTS;
    public static final Enum HINDI_COUNTING;
    public static final Enum HINDI_NUMBERS;
    public static final Enum HINDI_VOWELS;
    public static final Enum IDEOGRAPH_DIGITAL;
    public static final Enum IDEOGRAPH_ENCLOSED_CIRCLE;
    public static final Enum IDEOGRAPH_LEGAL_TRADITIONAL;
    public static final Enum IDEOGRAPH_TRADITIONAL;
    public static final Enum IDEOGRAPH_ZODIAC;
    public static final Enum IDEOGRAPH_ZODIAC_TRADITIONAL;
    public static final int INT_AIUEO = 13;
    public static final int INT_AIUEO_FULL_WIDTH = 21;
    public static final int INT_ARABIC_ABJAD = 53;
    public static final int INT_ARABIC_ALPHA = 52;
    public static final int INT_BAHT_TEXT = 61;
    public static final int INT_BULLET = 24;
    public static final int INT_CARDINAL_TEXT = 7;
    public static final int INT_CHICAGO = 10;
    public static final int INT_CHINESE_COUNTING = 38;
    public static final int INT_CHINESE_COUNTING_THOUSAND = 40;
    public static final int INT_CHINESE_LEGAL_SIMPLIFIED = 39;
    public static final int INT_CHOSUNG = 26;
    public static final int INT_CUSTOM = 63;
    public static final int INT_DECIMAL = 1;
    public static final int INT_DECIMAL_ENCLOSED_CIRCLE = 19;
    public static final int INT_DECIMAL_ENCLOSED_CIRCLE_CHINESE = 29;
    public static final int INT_DECIMAL_ENCLOSED_FULLSTOP = 27;
    public static final int INT_DECIMAL_ENCLOSED_PAREN = 28;
    public static final int INT_DECIMAL_FULL_WIDTH = 15;
    public static final int INT_DECIMAL_FULL_WIDTH_2 = 20;
    public static final int INT_DECIMAL_HALF_WIDTH = 16;
    public static final int INT_DECIMAL_ZERO = 23;
    public static final int INT_DOLLAR_TEXT = 62;
    public static final int INT_GANADA = 25;
    public static final int INT_HEBREW_1 = 50;
    public static final int INT_HEBREW_2 = 51;
    public static final int INT_HEX = 9;
    public static final int INT_HINDI_CONSONANTS = 55;
    public static final int INT_HINDI_COUNTING = 57;
    public static final int INT_HINDI_NUMBERS = 56;
    public static final int INT_HINDI_VOWELS = 54;
    public static final int INT_IDEOGRAPH_DIGITAL = 11;
    public static final int INT_IDEOGRAPH_ENCLOSED_CIRCLE = 30;
    public static final int INT_IDEOGRAPH_LEGAL_TRADITIONAL = 35;
    public static final int INT_IDEOGRAPH_TRADITIONAL = 31;
    public static final int INT_IDEOGRAPH_ZODIAC = 32;
    public static final int INT_IDEOGRAPH_ZODIAC_TRADITIONAL = 33;
    public static final int INT_IROHA = 14;
    public static final int INT_IROHA_FULL_WIDTH = 22;
    public static final int INT_JAPANESE_COUNTING = 12;
    public static final int INT_JAPANESE_DIGITAL_TEN_THOUSAND = 18;
    public static final int INT_JAPANESE_LEGAL = 17;
    public static final int INT_KOREAN_COUNTING = 42;
    public static final int INT_KOREAN_DIGITAL = 41;
    public static final int INT_KOREAN_DIGITAL_2 = 44;
    public static final int INT_KOREAN_LEGAL = 43;
    public static final int INT_LOWER_LETTER = 5;
    public static final int INT_LOWER_ROMAN = 3;
    public static final int INT_NONE = 48;
    public static final int INT_NUMBER_IN_DASH = 49;
    public static final int INT_ORDINAL = 6;
    public static final int INT_ORDINAL_TEXT = 8;
    public static final int INT_RUSSIAN_LOWER = 46;
    public static final int INT_RUSSIAN_UPPER = 47;
    public static final int INT_TAIWANESE_COUNTING = 34;
    public static final int INT_TAIWANESE_COUNTING_THOUSAND = 36;
    public static final int INT_TAIWANESE_DIGITAL = 37;
    public static final int INT_THAI_COUNTING = 60;
    public static final int INT_THAI_LETTERS = 58;
    public static final int INT_THAI_NUMBERS = 59;
    public static final int INT_UPPER_LETTER = 4;
    public static final int INT_UPPER_ROMAN = 2;
    public static final int INT_VIETNAMESE_COUNTING = 45;
    public static final Enum IROHA;
    public static final Enum IROHA_FULL_WIDTH;
    public static final Enum JAPANESE_COUNTING;
    public static final Enum JAPANESE_DIGITAL_TEN_THOUSAND;
    public static final Enum JAPANESE_LEGAL;
    public static final Enum KOREAN_COUNTING;
    public static final Enum KOREAN_DIGITAL;
    public static final Enum KOREAN_DIGITAL_2;
    public static final Enum KOREAN_LEGAL;
    public static final Enum LOWER_LETTER;
    public static final Enum LOWER_ROMAN;
    public static final Enum NONE;
    public static final Enum NUMBER_IN_DASH;
    public static final Enum ORDINAL;
    public static final Enum ORDINAL_TEXT;
    public static final Enum RUSSIAN_LOWER;
    public static final Enum RUSSIAN_UPPER;
    public static final Enum TAIWANESE_COUNTING;
    public static final Enum TAIWANESE_COUNTING_THOUSAND;
    public static final Enum TAIWANESE_DIGITAL;
    public static final Enum THAI_COUNTING;
    public static final Enum THAI_LETTERS;
    public static final Enum THAI_NUMBERS;
    public static final Enum UPPER_LETTER;
    public static final Enum UPPER_ROMAN;
    public static final Enum VIETNAMESE_COUNTING;
    public static final SchemaType type;

    /* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
    public static final class Enum extends StringEnumAbstractBase {
        static final int INT_AIUEO = 13;
        static final int INT_AIUEO_FULL_WIDTH = 21;
        static final int INT_ARABIC_ABJAD = 53;
        static final int INT_ARABIC_ALPHA = 52;
        static final int INT_BAHT_TEXT = 61;
        static final int INT_BULLET = 24;
        static final int INT_CARDINAL_TEXT = 7;
        static final int INT_CHICAGO = 10;
        static final int INT_CHINESE_COUNTING = 38;
        static final int INT_CHINESE_COUNTING_THOUSAND = 40;
        static final int INT_CHINESE_LEGAL_SIMPLIFIED = 39;
        static final int INT_CHOSUNG = 26;
        static final int INT_CUSTOM = 63;
        static final int INT_DECIMAL = 1;
        static final int INT_DECIMAL_ENCLOSED_CIRCLE = 19;
        static final int INT_DECIMAL_ENCLOSED_CIRCLE_CHINESE = 29;
        static final int INT_DECIMAL_ENCLOSED_FULLSTOP = 27;
        static final int INT_DECIMAL_ENCLOSED_PAREN = 28;
        static final int INT_DECIMAL_FULL_WIDTH = 15;
        static final int INT_DECIMAL_FULL_WIDTH_2 = 20;
        static final int INT_DECIMAL_HALF_WIDTH = 16;
        static final int INT_DECIMAL_ZERO = 23;
        static final int INT_DOLLAR_TEXT = 62;
        static final int INT_GANADA = 25;
        static final int INT_HEBREW_1 = 50;
        static final int INT_HEBREW_2 = 51;
        static final int INT_HEX = 9;
        static final int INT_HINDI_CONSONANTS = 55;
        static final int INT_HINDI_COUNTING = 57;
        static final int INT_HINDI_NUMBERS = 56;
        static final int INT_HINDI_VOWELS = 54;
        static final int INT_IDEOGRAPH_DIGITAL = 11;
        static final int INT_IDEOGRAPH_ENCLOSED_CIRCLE = 30;
        static final int INT_IDEOGRAPH_LEGAL_TRADITIONAL = 35;
        static final int INT_IDEOGRAPH_TRADITIONAL = 31;
        static final int INT_IDEOGRAPH_ZODIAC = 32;
        static final int INT_IDEOGRAPH_ZODIAC_TRADITIONAL = 33;
        static final int INT_IROHA = 14;
        static final int INT_IROHA_FULL_WIDTH = 22;
        static final int INT_JAPANESE_COUNTING = 12;
        static final int INT_JAPANESE_DIGITAL_TEN_THOUSAND = 18;
        static final int INT_JAPANESE_LEGAL = 17;
        static final int INT_KOREAN_COUNTING = 42;
        static final int INT_KOREAN_DIGITAL = 41;
        static final int INT_KOREAN_DIGITAL_2 = 44;
        static final int INT_KOREAN_LEGAL = 43;
        static final int INT_LOWER_LETTER = 5;
        static final int INT_LOWER_ROMAN = 3;
        static final int INT_NONE = 48;
        static final int INT_NUMBER_IN_DASH = 49;
        static final int INT_ORDINAL = 6;
        static final int INT_ORDINAL_TEXT = 8;
        static final int INT_RUSSIAN_LOWER = 46;
        static final int INT_RUSSIAN_UPPER = 47;
        static final int INT_TAIWANESE_COUNTING = 34;
        static final int INT_TAIWANESE_COUNTING_THOUSAND = 36;
        static final int INT_TAIWANESE_DIGITAL = 37;
        static final int INT_THAI_COUNTING = 60;
        static final int INT_THAI_LETTERS = 58;
        static final int INT_THAI_NUMBERS = 59;
        static final int INT_UPPER_LETTER = 4;
        static final int INT_UPPER_ROMAN = 2;
        static final int INT_VIETNAMESE_COUNTING = 45;
        private static final long serialVersionUID = 1;
        public static final StringEnumAbstractBase.Table table = new StringEnumAbstractBase.Table(new Enum[]{new Enum(XmlErrorCodes.DECIMAL, 1), new Enum("upperRoman", 2), new Enum("lowerRoman", 3), new Enum("upperLetter", 4), new Enum("lowerLetter", 5), new Enum("ordinal", 6), new Enum("cardinalText", 7), new Enum("ordinalText", 8), new Enum("hex", 9), new Enum("chicago", 10), new Enum("ideographDigital", 11), new Enum("japaneseCounting", 12), new Enum("aiueo", 13), new Enum("iroha", 14), new Enum("decimalFullWidth", 15), new Enum("decimalHalfWidth", 16), new Enum("japaneseLegal", 17), new Enum("japaneseDigitalTenThousand", 18), new Enum("decimalEnclosedCircle", 19), new Enum("decimalFullWidth2", 20), new Enum("aiueoFullWidth", 21), new Enum("irohaFullWidth", 22), new Enum("decimalZero", 23), new Enum("bullet", 24), new Enum("ganada", 25), new Enum("chosung", 26), new Enum("decimalEnclosedFullstop", 27), new Enum("decimalEnclosedParen", 28), new Enum("decimalEnclosedCircleChinese", 29), new Enum("ideographEnclosedCircle", 30), new Enum("ideographTraditional", 31), new Enum("ideographZodiac", 32), new Enum("ideographZodiacTraditional", 33), new Enum("taiwaneseCounting", 34), new Enum("ideographLegalTraditional", 35), new Enum("taiwaneseCountingThousand", 36), new Enum("taiwaneseDigital", 37), new Enum("chineseCounting", 38), new Enum("chineseLegalSimplified", 39), new Enum("chineseCountingThousand", 40), new Enum("koreanDigital", 41), new Enum("koreanCounting", 42), new Enum("koreanLegal", 43), new Enum("koreanDigital2", 44), new Enum("vietnameseCounting", 45), new Enum("russianLower", 46), new Enum("russianUpper", 47), new Enum("none", 48), new Enum("numberInDash", 49), new Enum("hebrew1", 50), new Enum("hebrew2", 51), new Enum("arabicAlpha", 52), new Enum("arabicAbjad", 53), new Enum("hindiVowels", 54), new Enum("hindiConsonants", 55), new Enum("hindiNumbers", 56), new Enum("hindiCounting", 57), new Enum("thaiLetters", 58), new Enum("thaiNumbers", 59), new Enum("thaiCounting", 60), new Enum("bahtText", 61), new Enum("dollarText", 62), new Enum("custom", 63)});

        private Enum(String str, int i5) {
            super(str, i5);
        }

        public static Enum forInt(int i5) {
            return (Enum) table.forInt(i5);
        }

        public static Enum forString(String str) {
            return (Enum) table.forString(str);
        }

        private Object readResolve() {
            return forInt(intValue());
        }
    }

    static {
        SimpleTypeFactory<STNumberFormat> simpleTypeFactory = new SimpleTypeFactory<>(TypeSystemHolder.typeSystem, "stnumberformat0fb8type");
        Factory = simpleTypeFactory;
        type = simpleTypeFactory.getType();
        DECIMAL = Enum.forString(XmlErrorCodes.DECIMAL);
        UPPER_ROMAN = Enum.forString("upperRoman");
        LOWER_ROMAN = Enum.forString("lowerRoman");
        UPPER_LETTER = Enum.forString("upperLetter");
        LOWER_LETTER = Enum.forString("lowerLetter");
        ORDINAL = Enum.forString("ordinal");
        CARDINAL_TEXT = Enum.forString("cardinalText");
        ORDINAL_TEXT = Enum.forString("ordinalText");
        HEX = Enum.forString("hex");
        CHICAGO = Enum.forString("chicago");
        IDEOGRAPH_DIGITAL = Enum.forString("ideographDigital");
        JAPANESE_COUNTING = Enum.forString("japaneseCounting");
        AIUEO = Enum.forString("aiueo");
        IROHA = Enum.forString("iroha");
        DECIMAL_FULL_WIDTH = Enum.forString("decimalFullWidth");
        DECIMAL_HALF_WIDTH = Enum.forString("decimalHalfWidth");
        JAPANESE_LEGAL = Enum.forString("japaneseLegal");
        JAPANESE_DIGITAL_TEN_THOUSAND = Enum.forString("japaneseDigitalTenThousand");
        DECIMAL_ENCLOSED_CIRCLE = Enum.forString("decimalEnclosedCircle");
        DECIMAL_FULL_WIDTH_2 = Enum.forString("decimalFullWidth2");
        AIUEO_FULL_WIDTH = Enum.forString("aiueoFullWidth");
        IROHA_FULL_WIDTH = Enum.forString("irohaFullWidth");
        DECIMAL_ZERO = Enum.forString("decimalZero");
        BULLET = Enum.forString("bullet");
        GANADA = Enum.forString("ganada");
        CHOSUNG = Enum.forString("chosung");
        DECIMAL_ENCLOSED_FULLSTOP = Enum.forString("decimalEnclosedFullstop");
        DECIMAL_ENCLOSED_PAREN = Enum.forString("decimalEnclosedParen");
        DECIMAL_ENCLOSED_CIRCLE_CHINESE = Enum.forString("decimalEnclosedCircleChinese");
        IDEOGRAPH_ENCLOSED_CIRCLE = Enum.forString("ideographEnclosedCircle");
        IDEOGRAPH_TRADITIONAL = Enum.forString("ideographTraditional");
        IDEOGRAPH_ZODIAC = Enum.forString("ideographZodiac");
        IDEOGRAPH_ZODIAC_TRADITIONAL = Enum.forString("ideographZodiacTraditional");
        TAIWANESE_COUNTING = Enum.forString("taiwaneseCounting");
        IDEOGRAPH_LEGAL_TRADITIONAL = Enum.forString("ideographLegalTraditional");
        TAIWANESE_COUNTING_THOUSAND = Enum.forString("taiwaneseCountingThousand");
        TAIWANESE_DIGITAL = Enum.forString("taiwaneseDigital");
        CHINESE_COUNTING = Enum.forString("chineseCounting");
        CHINESE_LEGAL_SIMPLIFIED = Enum.forString("chineseLegalSimplified");
        CHINESE_COUNTING_THOUSAND = Enum.forString("chineseCountingThousand");
        KOREAN_DIGITAL = Enum.forString("koreanDigital");
        KOREAN_COUNTING = Enum.forString("koreanCounting");
        KOREAN_LEGAL = Enum.forString("koreanLegal");
        KOREAN_DIGITAL_2 = Enum.forString("koreanDigital2");
        VIETNAMESE_COUNTING = Enum.forString("vietnameseCounting");
        RUSSIAN_LOWER = Enum.forString("russianLower");
        RUSSIAN_UPPER = Enum.forString("russianUpper");
        NONE = Enum.forString("none");
        NUMBER_IN_DASH = Enum.forString("numberInDash");
        HEBREW_1 = Enum.forString("hebrew1");
        HEBREW_2 = Enum.forString("hebrew2");
        ARABIC_ALPHA = Enum.forString("arabicAlpha");
        ARABIC_ABJAD = Enum.forString("arabicAbjad");
        HINDI_VOWELS = Enum.forString("hindiVowels");
        HINDI_CONSONANTS = Enum.forString("hindiConsonants");
        HINDI_NUMBERS = Enum.forString("hindiNumbers");
        HINDI_COUNTING = Enum.forString("hindiCounting");
        THAI_LETTERS = Enum.forString("thaiLetters");
        THAI_NUMBERS = Enum.forString("thaiNumbers");
        THAI_COUNTING = Enum.forString("thaiCounting");
        BAHT_TEXT = Enum.forString("bahtText");
        DOLLAR_TEXT = Enum.forString("dollarText");
        CUSTOM = Enum.forString("custom");
    }

    StringEnumAbstractBase getEnumValue();

    void setEnumValue(StringEnumAbstractBase stringEnumAbstractBase);
}
