package com.alibaba.android.arouter.routes;

import com.alibaba.android.arouter.facade.enums.RouteType;
import com.alibaba.android.arouter.facade.model.RouteMeta;
import com.alibaba.android.arouter.facade.template.IRouteGroup;
import com.appdev.constant.DefaultRouteConstant;
import com.appdev.standard.page.BootActivity;
import com.appdev.standard.page.GuideActivity;
import com.appdev.standard.page.LoadFileActivity;
import com.appdev.standard.page.MainActivity;
import com.appdev.standard.page.auth.AgreementActivity;
import com.appdev.standard.page.auth.ForgetSettingPasswordActivity;
import com.appdev.standard.page.auth.LoginActivity;
import com.appdev.standard.page.auth.RegisterActivity;
import com.appdev.standard.page.auth.ResetPasswordActivity;
import com.appdev.standard.page.auth.SettingPasswordActivity;
import com.appdev.standard.page.bluetooth.BluetoothDeviceListActivity;
import com.appdev.standard.page.bluetooth.ConnectPrintDevicesActivity;
import com.appdev.standard.page.bluetooth.PrintDeviceInfoActivity;
import com.appdev.standard.page.mine.ArticleViewActivity;
import com.appdev.standard.page.mine.ChangePasswordActivity;
import com.appdev.standard.page.mine.ChangeUserNameEmailActivity;
import com.appdev.standard.page.mine.ChangeUserNamePhoneActivity;
import com.appdev.standard.page.mine.FeedbackActivity;
import com.appdev.standard.page.mine.FeedbackListActivity;
import com.appdev.standard.page.mine.HelpCenterActivity;
import com.appdev.standard.page.mine.LanguageManagementActivity;
import com.appdev.standard.page.mine.MemberBuyActivity;
import com.appdev.standard.page.mine.MemberCenterActivity;
import com.appdev.standard.page.mine.MineQRCodeActivity;
import com.appdev.standard.page.mine.ModifyNicknameActivity;
import com.appdev.standard.page.mine.PDFViewActivity;
import com.appdev.standard.page.mine.PayResultActivity;
import com.appdev.standard.page.mine.PersonalInfomationActivity;
import com.appdev.standard.page.mine.ServerAgreementActivity;
import com.appdev.standard.page.mine.VideoViewActivity;
import com.appdev.standard.page.printerlabel.CreateLabelActivity;
import com.appdev.standard.page.printerlabel.EditLabelActivity;
import com.appdev.standard.page.printerlabel.MaterialLibraryActivity;
import com.appdev.standard.page.printerlabel.MaterialLibraryPageActivity;
import com.appdev.standard.page.printerlabel.PDFFileListActivity;
import com.appdev.standard.page.printerlabel.PDFPrintActivity;
import com.appdev.standard.page.printerlabel.PhotoPrintActivity;
import com.appdev.standard.page.printerlabel.PicturePrintActivity;
import com.appdev.standard.page.printerlabel.PrintPageActivity;
import com.appdev.standard.page.quickprinting.QuickPrintingActivity;
import com.appdev.standard.page.receipt.CreateReceiptActivity;
import com.appdev.standard.page.receipt.EditReceiptActivity;
import com.appdev.standard.page.receipt.ReceiptEditActivity;
import com.appdev.standard.page.receipt.ReceiptPrintPageActivity;
import com.appdev.standard.page.scene.CloudSpaceCloudLabelManageActivity;
import java.util.Map;
import p036g.a;

/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes.dex */
public class ARouter$$Group$$standard implements IRouteGroup {
    @Override // com.alibaba.android.arouter.facade.template.IRouteGroup
    public void loadInto(Map<String, RouteMeta> map) {
        RouteType routeType = RouteType.ACTIVITY;
        a aVar = new a();
        aVar.put("type", 3);
        map.put(DefaultRouteConstant.ACTIVITY_AGREEMENT, RouteMeta.build(routeType, AgreementActivity.class, "/standard/agreementactivity", "standard", aVar, -1, Integer.MIN_VALUE));
        a aVar2 = new a();
        aVar2.put("title", 8);
        aVar2.put("url", 8);
        map.put(DefaultRouteConstant.ACTIVITY_ARTICLE_VIEW, RouteMeta.build(routeType, ArticleViewActivity.class, "/standard/articleviewactivity", "standard", aVar2, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_BLUETOOTH_DEVICE_LIST, RouteMeta.build(routeType, BluetoothDeviceListActivity.class, "/standard/bluetoothdevicelistactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_BOOT, RouteMeta.build(routeType, BootActivity.class, "/standard/bootactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_CHANGEPASSWORD, RouteMeta.build(routeType, ChangePasswordActivity.class, "/standard/changepasswordactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_CHANGE_USERNAME_EMAIL, RouteMeta.build(routeType, ChangeUserNameEmailActivity.class, "/standard/changeusernameemailactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_CHANGE_USERNAME_PHONE, RouteMeta.build(routeType, ChangeUserNamePhoneActivity.class, "/standard/changeusernamephoneactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_CLOUD_SPACE_CLOUD_LABEL_MANAGE, RouteMeta.build(routeType, CloudSpaceCloudLabelManageActivity.class, "/standard/cloudspacecloudlabelmanageactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_CONNECT_PRINT_DEVICES, RouteMeta.build(routeType, ConnectPrintDevicesActivity.class, "/standard/connectprintdevicesactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_CREATE_LABEL, RouteMeta.build(routeType, CreateLabelActivity.class, "/standard/createlabelactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_CREATE_RECEIPT, RouteMeta.build(routeType, CreateReceiptActivity.class, "/standard/createreceiptactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_EDIT_LABEL, RouteMeta.build(routeType, EditLabelActivity.class, "/standard/editlabelactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_EDIT_RECEIPT, RouteMeta.build(routeType, EditReceiptActivity.class, "/standard/editreceiptactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_FEEDBACK, RouteMeta.build(routeType, FeedbackActivity.class, "/standard/feedbackactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_FEEDBACK_LIST, RouteMeta.build(routeType, FeedbackListActivity.class, "/standard/feedbacklistactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_FORGET_SETTING_PASSWORD, RouteMeta.build(routeType, ForgetSettingPasswordActivity.class, "/standard/forgetsettingpasswordactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_GUIDE, RouteMeta.build(routeType, GuideActivity.class, "/standard/guideactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_HELP_CENTER, RouteMeta.build(routeType, HelpCenterActivity.class, "/standard/helpcenteractivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_LANGUAGE_MANAGEMENT, RouteMeta.build(routeType, LanguageManagementActivity.class, "/standard/languagemanagementactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_LOAD_FILE, RouteMeta.build(routeType, LoadFileActivity.class, "/standard/loadfileactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_LOGIN, RouteMeta.build(routeType, LoginActivity.class, "/standard/loginactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_MAIN, RouteMeta.build(routeType, MainActivity.class, "/standard/mainactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_MATERIAL_LIBRARY, RouteMeta.build(routeType, MaterialLibraryActivity.class, "/standard/materiallibraryactivity", "standard", null, -1, Integer.MIN_VALUE));
        a aVar3 = new a();
        aVar3.put("path", 8);
        map.put(DefaultRouteConstant.ACTIVITY_MATERIAL_LIBRARY_PAGE, RouteMeta.build(routeType, MaterialLibraryPageActivity.class, "/standard/materiallibrarypageactivity", "standard", aVar3, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_MEMBER_BUY, RouteMeta.build(routeType, MemberBuyActivity.class, "/standard/memberbuyactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_MEMBER_CENTER, RouteMeta.build(routeType, MemberCenterActivity.class, "/standard/membercenteractivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_MINEQRCODE, RouteMeta.build(routeType, MineQRCodeActivity.class, "/standard/mineqrcodeactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_MODIFYNICKNAME, RouteMeta.build(routeType, ModifyNicknameActivity.class, "/standard/modifynicknameactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_PDF_FILE_LIST, RouteMeta.build(routeType, PDFFileListActivity.class, "/standard/pdffilelistactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_PDF_PRINT, RouteMeta.build(routeType, PDFPrintActivity.class, "/standard/pdfprintactivity", "standard", null, -1, Integer.MIN_VALUE));
        a aVar4 = new a();
        aVar4.put("title", 8);
        aVar4.put("url", 8);
        map.put(DefaultRouteConstant.ACTIVITY_PDF_VIEW, RouteMeta.build(routeType, PDFViewActivity.class, "/standard/pdfviewactivity", "standard", aVar4, -1, Integer.MIN_VALUE));
        a aVar5 = new a();
        aVar5.put("payStatus", 3);
        map.put(DefaultRouteConstant.ACTIVITY_PAY_RESULT, RouteMeta.build(routeType, PayResultActivity.class, "/standard/payresultactivity", "standard", aVar5, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_PERSONALINFOMATION, RouteMeta.build(routeType, PersonalInfomationActivity.class, "/standard/personalinfomationactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_PHOTO_PRINT, RouteMeta.build(routeType, PhotoPrintActivity.class, "/standard/photoprintactivity", "standard", null, -1, Integer.MIN_VALUE));
        a aVar6 = new a();
        aVar6.put("path", 8);
        aVar6.put("rotate", 0);
        map.put(DefaultRouteConstant.ACTIVITY_PICTURE_PRINT, RouteMeta.build(routeType, PicturePrintActivity.class, "/standard/pictureprintactivity", "standard", aVar6, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_PRINT_DEVICE_INFO, RouteMeta.build(routeType, PrintDeviceInfoActivity.class, "/standard/printdeviceinfoactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_PRINT_PAGE, RouteMeta.build(routeType, PrintPageActivity.class, "/standard/printpageactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_QUICK_PRINTING, RouteMeta.build(routeType, QuickPrintingActivity.class, "/standard/quickprintingactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_RECEIPT_EDIT, RouteMeta.build(routeType, ReceiptEditActivity.class, "/standard/receipteditactivity", "standard", null, -1, Integer.MIN_VALUE));
        a aVar7 = new a();
        aVar7.put("ReceiptPrintPageActivityReceiptWidth", 3);
        aVar7.put("ReceiptPrintPageActivityData", 8);
        map.put(DefaultRouteConstant.ACTIVITY_RECEIPT_PRINT_PAGE, RouteMeta.build(routeType, ReceiptPrintPageActivity.class, "/standard/receiptprintpageactivity", "standard", aVar7, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_REGISTER, RouteMeta.build(routeType, RegisterActivity.class, "/standard/registeractivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_RESETPASSWORD, RouteMeta.build(routeType, ResetPasswordActivity.class, "/standard/resetpasswordactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_SERVER_AGREEMENT, RouteMeta.build(routeType, ServerAgreementActivity.class, "/standard/serveragreementactivity", "standard", null, -1, Integer.MIN_VALUE));
        map.put(DefaultRouteConstant.ACTIVITY_SETTING_PASSWORD, RouteMeta.build(routeType, SettingPasswordActivity.class, "/standard/settingpasswordactivity", "standard", null, -1, Integer.MIN_VALUE));
        a aVar8 = new a();
        aVar8.put("fileName", 8);
        aVar8.put("title", 8);
        map.put(DefaultRouteConstant.ACTIVITY_VIDEO_VIEW, RouteMeta.build(routeType, VideoViewActivity.class, "/standard/videoviewactivity", "standard", aVar8, -1, Integer.MIN_VALUE));
    }
}
