package org.apache.poi.openxml4j.opc;

import A3.AbstractC0157z;
import androidx.constraintlayout.core.motion.utils.TypedValues;
import io.flutter.plugins.firebase.crashlytics.Constants;
import java.io.ByteArrayOutputStream;
import java.io.Closeable;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.openxml4j.exceptions.InvalidOperationException;
import org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException;
import org.apache.poi.openxml4j.exceptions.PartAlreadyExistsException;
import org.apache.poi.openxml4j.opc.internal.ContentType;
import org.apache.poi.openxml4j.opc.internal.ContentTypeManager;
import org.apache.poi.openxml4j.opc.internal.PackagePropertiesPart;
import org.apache.poi.openxml4j.opc.internal.PartMarshaller;
import org.apache.poi.openxml4j.opc.internal.PartUnmarshaller;
import org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager;
import org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller;
import org.apache.poi.openxml4j.opc.internal.marshallers.ZipPackagePropertiesMarshaller;
import org.apache.poi.openxml4j.opc.internal.unmarshallers.PackagePropertiesUnmarshaller;
import org.apache.poi.openxml4j.opc.internal.unmarshallers.UnmarshallContext;
import org.apache.poi.openxml4j.util.ZipEntrySource;
import org.apache.poi.util.IOUtils;
import org.apache.poi.util.NotImplemented;
import org.apache.poi.util.StringUtil;

/* JADX INFO: compiled from: r8-map-id-ecf7e14176b8e73200efbc86dd80f717955f363e9b0ac3efdea3eedd88177748 */
/* JADX INFO: loaded from: classes4.dex */
public abstract class OPCPackage implements RelationshipSource, Closeable {
    private static final Logger LOG = LogManager.getLogger((Class<?>) OPCPackage.class);
    protected static final PackageAccess defaultPackageAccess = PackageAccess.READ_WRITE;
    protected ContentTypeManager contentTypeManager;
    protected final PartMarshaller defaultPartMarshaller;
    protected boolean isDirty;
    protected String originalPackagePath;
    protected OutputStream output;
    private final PackageAccess packageAccess;
    protected PackagePropertiesPart packageProperties;
    private PackagePartCollection partList;
    protected final Map<ContentType, PartMarshaller> partMarshallers;
    protected final Map<ContentType, PartUnmarshaller> partUnmarshallers;
    protected PackageRelationshipCollection relationships;

    public OPCPackage(PackageAccess packageAccess) {
        HashMap map = new HashMap(5);
        this.partMarshallers = map;
        this.defaultPartMarshaller = new DefaultMarshaller();
        HashMap map2 = new HashMap(2);
        this.partUnmarshallers = map2;
        if (getClass() != ZipPackage.class) {
            throw new IllegalArgumentException("PackageBase may not be subclassed");
        }
        this.packageAccess = packageAccess;
        ContentType contentTypeNewCorePropertiesPart = newCorePropertiesPart();
        map2.put(contentTypeNewCorePropertiesPart, new PackagePropertiesUnmarshaller());
        map.put(contentTypeNewCorePropertiesPart, new ZipPackagePropertiesMarshaller());
    }

    private static void configurePackage(OPCPackage oPCPackage) {
        try {
            ZipContentTypeManager zipContentTypeManager = new ZipContentTypeManager(null, oPCPackage);
            oPCPackage.contentTypeManager = zipContentTypeManager;
            zipContentTypeManager.addContentType(PackagingURIHelper.createPartName(PackagingURIHelper.PACKAGE_RELATIONSHIPS_ROOT_URI), ContentTypes.RELATIONSHIPS_PART);
            oPCPackage.contentTypeManager.addContentType(PackagingURIHelper.createPartName("/default.xml"), ContentTypes.PLAIN_OLD_XML);
            PackagePropertiesPart packagePropertiesPart = new PackagePropertiesPart(oPCPackage, PackagingURIHelper.CORE_PROPERTIES_PART_NAME);
            oPCPackage.packageProperties = packagePropertiesPart;
            packagePropertiesPart.setCreatorProperty("Generated by Apache POI OpenXML4J");
            oPCPackage.packageProperties.setCreatedProperty(Optional.of(new Date()));
        } catch (InvalidFormatException e) {
            throw new IllegalStateException(e);
        }
    }

    public static OPCPackage create(String str) {
        return create(new File(str));
    }

    private PackageRelationshipCollection getRelationshipsHelper(String str) {
        throwExceptionIfWriteOnly();
        ensureRelationships();
        return this.relationships.getRelationships(str);
    }

    private static ContentType newCorePropertiesPart() {
        try {
            return new ContentType(ContentTypes.CORE_PROPERTIES_PART);
        } catch (InvalidFormatException e) {
            throw new OpenXML4JRuntimeException("Package.init() : this exception should never happen, if you read this message please send a mail to the developers team. : " + e.getMessage(), e);
        }
    }

    public static OPCPackage open(String str) {
        return open(str, defaultPackageAccess);
    }

    public static OPCPackage openOrCreate(File file) {
        return file.exists() ? open(file.getAbsolutePath()) : create(file);
    }

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public PackageRelationship addExternalRelationship(String str, String str2) {
        return addExternalRelationship(str, str2, null);
    }

    public void addMarshaller(String str, PartMarshaller partMarshaller) {
        try {
            this.partMarshallers.put(new ContentType(str), partMarshaller);
        } catch (InvalidFormatException e) {
            LOG.atWarn().log("The specified content type is not valid: '{}'. The marshaller will not be added !", e.getMessage());
        }
    }

    public PackagePart addPackagePart(PackagePart packagePart) {
        throwExceptionIfReadOnly();
        if (packagePart == null) {
            throw new IllegalArgumentException("part");
        }
        if (this.partList.containsKey(packagePart._partName)) {
            if (!this.partList.get(packagePart._partName).isDeleted()) {
                throw new InvalidOperationException("A part with the name '" + packagePart._partName.getName() + "' already exists : Packages shall not contain equivalent part names and package implementers shall neither create nor recognize packages with equivalent part names. [M1.12]");
            }
            packagePart.setDeleted(false);
            this.partList.remove(packagePart._partName);
        }
        this.partList.put(packagePart._partName, packagePart);
        this.isDirty = true;
        return packagePart;
    }

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public PackageRelationship addRelationship(PackagePartName packagePartName, TargetMode targetMode, String str, String str2) {
        if (str.equals(PackageRelationshipTypes.CORE_PROPERTIES) && this.packageProperties != null) {
            throw new InvalidOperationException("OPC Compliance error [M4.1]: can't add another core properties part ! Use the built-in package method instead.");
        }
        if (packagePartName.isRelationshipPartURI()) {
            throw new InvalidOperationException("Rule M1.25: The Relationships part shall not have relationships to any other part.");
        }
        ensureRelationships();
        PackageRelationship packageRelationshipAddRelationship = this.relationships.addRelationship(packagePartName.getURI(), targetMode, str, str2);
        this.isDirty = true;
        return packageRelationshipAddRelationship;
    }

    public void addThumbnail(String str) throws IOException {
        if (str == null || str.isEmpty()) {
            throw new IllegalArgumentException("path");
        }
        String strSubstring = str.substring(str.lastIndexOf(File.separatorChar) + 1);
        FileInputStream fileInputStream = new FileInputStream(str);
        try {
            addThumbnail(strSubstring, fileInputStream);
            fileInputStream.close();
        } catch (Throwable th) {
            try {
                throw th;
            } catch (Throwable th2) {
                try {
                    fileInputStream.close();
                } catch (Throwable th3) {
                    th.addSuppressed(th3);
                }
                throw th2;
            }
        }
    }

    public void addUnmarshaller(String str, PartUnmarshaller partUnmarshaller) {
        try {
            this.partUnmarshallers.put(new ContentType(str), partUnmarshaller);
        } catch (InvalidFormatException e) {
            LOG.atWarn().log("The specified content type is not valid: '{}'. The unmarshaller will not be added !", e.getMessage());
        }
    }

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public void clearRelationships() {
        PackageRelationshipCollection packageRelationshipCollection = this.relationships;
        if (packageRelationshipCollection != null) {
            packageRelationshipCollection.clear();
            this.isDirty = true;
        }
    }

    @Override // java.io.Closeable, java.lang.AutoCloseable
    public void close() throws IOException {
        if (isClosed()) {
            return;
        }
        if (this.packageAccess == PackageAccess.READ) {
            LOG.atDebug().log("The close() method is intended to SAVE a package. This package is open in READ ONLY mode, use the revert() method instead!");
            revert();
            return;
        }
        if (this.contentTypeManager == null) {
            LOG.atWarn().log("Unable to call close() on a package that hasn't been fully opened yet");
            revert();
            return;
        }
        if (StringUtil.isNotBlank(this.originalPackagePath)) {
            File file = new File(this.originalPackagePath);
            if (file.exists() && this.originalPackagePath.equalsIgnoreCase(file.getAbsolutePath())) {
                closeImpl();
            } else {
                save(file);
            }
        } else {
            OutputStream outputStream = this.output;
            if (outputStream != null) {
                try {
                    save(outputStream);
                    this.output.close();
                } catch (Throwable th) {
                    this.output.close();
                    throw th;
                }
            }
        }
        revert();
        this.contentTypeManager.clearAll();
    }

    public abstract void closeImpl();

    public boolean containPart(PackagePartName packagePartName) {
        return getPart(packagePartName) != null;
    }

    public PackagePart createPart(PackagePartName packagePartName, String str) {
        return createPart(packagePartName, str, true);
    }

    public abstract PackagePart createPartImpl(PackagePartName packagePartName, String str, boolean z6);

    public void deletePart(PackagePartName packagePartName) {
        if (packagePartName == null) {
            throw new IllegalArgumentException("partName");
        }
        removePart(packagePartName);
        removePart(PackagingURIHelper.getRelationshipPartName(packagePartName));
    }

    public void deletePartRecursive(PackagePartName packagePartName) {
        if (packagePartName == null || !containPart(packagePartName)) {
            throw new IllegalArgumentException("partName");
        }
        PackagePart part = getPart(packagePartName);
        removePart(packagePartName);
        try {
            Iterator<PackageRelationship> it = part.getRelationships().iterator();
            while (it.hasNext()) {
                deletePartRecursive(PackagingURIHelper.createPartName(PackagingURIHelper.resolvePartUri(packagePartName.getURI(), it.next().getTargetURI())));
            }
            PackagePartName relationshipPartName = PackagingURIHelper.getRelationshipPartName(packagePartName);
            if (relationshipPartName == null || !containPart(relationshipPartName)) {
                return;
            }
            removePart(relationshipPartName);
        } catch (InvalidFormatException e) {
            LOG.atWarn().withThrowable(e).log("An exception occurs while deleting part '{}'. Some parts may remain in the package.", packagePartName.getName());
        }
    }

    public void ensureRelationships() {
        if (this.relationships == null) {
            try {
                this.relationships = new PackageRelationshipCollection(this);
            } catch (InvalidFormatException unused) {
                this.relationships = new PackageRelationshipCollection();
            }
        }
    }

    public void flush() {
        throwExceptionIfReadOnly();
        PackagePropertiesPart packagePropertiesPart = this.packageProperties;
        if (packagePropertiesPart != null) {
            packagePropertiesPart.flush();
        }
        flushImpl();
    }

    public abstract void flushImpl();

    public PackageAccess getPackageAccess() {
        return this.packageAccess;
    }

    public PackageProperties getPackageProperties() {
        throwExceptionIfWriteOnly();
        if (this.packageProperties == null) {
            this.packageProperties = new PackagePropertiesPart(this, PackagingURIHelper.CORE_PROPERTIES_PART_NAME);
        }
        return this.packageProperties;
    }

    public PackagePart getPart(PackagePartName packagePartName) {
        throwExceptionIfWriteOnly();
        if (packagePartName == null) {
            throw new IllegalArgumentException("partName");
        }
        if (this.partList == null) {
            try {
                getParts();
            } catch (InvalidFormatException unused) {
                return null;
            }
        }
        return this.partList.get(packagePartName);
    }

    public ArrayList<PackagePart> getParts() throws InvalidFormatException {
        throwExceptionIfWriteOnly();
        if (this.partList == null) {
            this.partList = getPartsImpl();
            ArrayList arrayList = new ArrayList(this.partList.sortedValues());
            int size = arrayList.size();
            boolean z6 = true;
            boolean z7 = false;
            int i5 = 0;
            while (i5 < size) {
                Object obj = arrayList.get(i5);
                i5++;
                PackagePart packagePart = (PackagePart) obj;
                packagePart.loadRelationships();
                if (ContentTypes.CORE_PROPERTIES_PART.equals(packagePart.getContentType())) {
                    if (z7) {
                        LOG.atWarn().log("OPC Compliance error [M4.1]: there is more than one core properties relationship in the package! POI will use only the first, but other software may reject this file.");
                    } else {
                        z7 = true;
                    }
                }
                PartUnmarshaller partUnmarshaller = this.partUnmarshallers.get(packagePart._contentType);
                if (partUnmarshaller != null) {
                    UnmarshallContext unmarshallContext = new UnmarshallContext(this, packagePart._partName);
                    try {
                        InputStream inputStream = packagePart.getInputStream();
                        try {
                            PackagePart packagePartUnmarshall = partUnmarshaller.unmarshall(unmarshallContext, inputStream);
                            this.partList.remove(packagePart.getPartName());
                            this.partList.put(packagePartUnmarshall._partName, packagePartUnmarshall);
                            if ((packagePartUnmarshall instanceof PackagePropertiesPart) && z7 && z6) {
                                this.packageProperties = (PackagePropertiesPart) packagePartUnmarshall;
                                z6 = false;
                            }
                            if (inputStream != null) {
                                inputStream.close();
                            }
                        } catch (Throwable th) {
                            try {
                                throw th;
                            } catch (Throwable th2) {
                                if (inputStream != null) {
                                    try {
                                        inputStream.close();
                                    } catch (Throwable th3) {
                                        th.addSuppressed(th3);
                                    }
                                }
                                throw th2;
                            }
                        }
                    } catch (IOException unused) {
                        LOG.atWarn().log("Unmarshall operation : IOException for {}", packagePart._partName);
                    } catch (InvalidOperationException e) {
                        throw new InvalidFormatException(e.getMessage(), e);
                    }
                }
            }
        }
        return new ArrayList<>(this.partList.sortedValues());
    }

    public ArrayList<PackagePart> getPartsByContentType(String str) {
        ArrayList<PackagePart> arrayList = new ArrayList<>();
        for (PackagePart packagePart : this.partList.sortedValues()) {
            if (packagePart.getContentType().equals(str)) {
                arrayList.add(packagePart);
            }
        }
        return arrayList;
    }

    public List<PackagePart> getPartsByName(Pattern pattern) {
        if (pattern == null) {
            throw new IllegalArgumentException("name pattern must not be null");
        }
        Matcher matcher = pattern.matcher("");
        ArrayList arrayList = new ArrayList();
        for (PackagePart packagePart : this.partList.sortedValues()) {
            if (matcher.reset(packagePart.getPartName().getName()).matches()) {
                arrayList.add(packagePart);
            }
        }
        return arrayList;
    }

    public ArrayList<PackagePart> getPartsByRelationshipType(String str) {
        if (str == null) {
            throw new IllegalArgumentException("relationshipType");
        }
        ArrayList<PackagePart> arrayList = new ArrayList<>();
        Iterator<PackageRelationship> it = getRelationshipsByType(str).iterator();
        while (it.hasNext()) {
            PackagePart part = getPart(it.next());
            if (part != null) {
                arrayList.add(part);
            }
        }
        Collections.sort(arrayList);
        return arrayList;
    }

    public abstract PackagePartCollection getPartsImpl();

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public PackageRelationship getRelationship(String str) {
        return this.relationships.getRelationshipByID(str);
    }

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public PackageRelationshipCollection getRelationships() {
        return getRelationshipsHelper(null);
    }

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public PackageRelationshipCollection getRelationshipsByType(String str) {
        throwExceptionIfWriteOnly();
        if (str != null) {
            return getRelationshipsHelper(str);
        }
        throw new IllegalArgumentException("relationshipType");
    }

    public int getUnusedPartIndex(String str) {
        return this.partList.getUnusedPartIndex(str);
    }

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public boolean hasRelationships() {
        return !this.relationships.isEmpty();
    }

    public abstract boolean isClosed();

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public boolean isRelationshipExists(PackageRelationship packageRelationship) {
        Iterator<PackageRelationship> it = this.relationships.iterator();
        while (it.hasNext()) {
            if (it.next() == packageRelationship) {
                return true;
            }
        }
        return false;
    }

    public boolean isStrictOoxmlFormat() {
        return !getRelationshipsByType(PackageRelationshipTypes.STRICT_CORE_DOCUMENT).isEmpty();
    }

    public void registerPartAndContentType(PackagePart packagePart) {
        addPackagePart(packagePart);
        this.contentTypeManager.addContentType(packagePart.getPartName(), packagePart.getContentType());
        this.isDirty = true;
    }

    public void removeMarshaller(String str) {
        try {
            this.partMarshallers.remove(new ContentType(str));
        } catch (InvalidFormatException e) {
            throw new RuntimeException(e);
        }
    }

    public void removePart(PackagePart packagePart) {
        if (packagePart != null) {
            removePart(packagePart.getPartName());
        }
    }

    public abstract void removePartImpl(PackagePartName packagePartName);

    public void removePartRecursive(PackagePartName packagePartName) {
        PackagePart packagePart = this.partList.get(PackagingURIHelper.getRelationshipPartName(packagePartName));
        PackagePart packagePart2 = this.partList.get(packagePartName);
        if (packagePart != null) {
            for (PackageRelationship packageRelationship : new PackageRelationshipCollection(packagePart2)) {
                removePart(PackagingURIHelper.createPartName(PackagingURIHelper.resolvePartUri(packageRelationship.getSourceURI(), packageRelationship.getTargetURI())));
            }
            removePart(packagePart._partName);
        }
        removePart(packagePart2._partName);
    }

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public void removeRelationship(String str) {
        PackageRelationshipCollection packageRelationshipCollection = this.relationships;
        if (packageRelationshipCollection != null) {
            packageRelationshipCollection.removeRelationship(str);
            this.isDirty = true;
        }
    }

    public void removeUnmarshaller(String str) {
        try {
            this.partUnmarshallers.remove(new ContentType(str));
        } catch (InvalidFormatException e) {
            throw new RuntimeException(e);
        }
    }

    public boolean replaceContentType(String str, String str2) {
        ArrayList<PackagePart> partsByContentType = getPartsByContentType(str);
        int size = partsByContentType.size();
        boolean z6 = false;
        int i5 = 0;
        while (i5 < size) {
            PackagePart packagePart = partsByContentType.get(i5);
            i5++;
            PackagePart packagePart2 = packagePart;
            if (packagePart2.getContentType().equals(str)) {
                this.contentTypeManager.addContentType(packagePart2.getPartName(), str2);
                try {
                    packagePart2.setContentType(str2);
                    z6 = true;
                    this.isDirty = true;
                } catch (InvalidFormatException e) {
                    throw new OpenXML4JRuntimeException(AbstractC0157z.n("invalid content type - ", str2), e);
                }
            }
        }
        return z6;
    }

    public void revert() {
        revertImpl();
    }

    public abstract void revertImpl();

    public void save(File file) throws IOException {
        if (file == null) {
            throw new IllegalArgumentException("targetFile");
        }
        throwExceptionIfReadOnly();
        if (file.exists() && file.getAbsolutePath().equals(this.originalPackagePath)) {
            throw new InvalidOperationException("You can't call save(File) to save to the currently open file. To save to the current file, please just call close()");
        }
        FileOutputStream fileOutputStream = new FileOutputStream(file);
        try {
            save(fileOutputStream);
            fileOutputStream.close();
        } catch (Throwable th) {
            try {
                throw th;
            } catch (Throwable th2) {
                try {
                    fileOutputStream.close();
                } catch (Throwable th3) {
                    th.addSuppressed(th3);
                }
                throw th2;
            }
        }
    }

    public abstract void saveImpl(OutputStream outputStream);

    public void throwExceptionIfReadOnly() {
        if (this.packageAccess == PackageAccess.READ) {
            throw new InvalidOperationException("Operation not allowed, document open in read only mode!");
        }
    }

    public void throwExceptionIfWriteOnly() {
        if (this.packageAccess == PackageAccess.WRITE) {
            throw new InvalidOperationException("Operation not allowed, document open in write only mode!");
        }
    }

    public String toString() {
        return "OPCPackage{packageAccess=" + this.packageAccess + ", relationships=" + this.relationships + ", packageProperties=" + this.packageProperties + ", isDirty=" + this.isDirty + '}';
    }

    public void unregisterPartAndContentType(PackagePartName packagePartName) {
        removePart(packagePartName);
        this.contentTypeManager.removeContentType(packagePartName);
        this.isDirty = true;
    }

    @NotImplemented
    public boolean validatePackage(OPCPackage oPCPackage) {
        throw new InvalidOperationException("Not implemented yet !!!");
    }

    public static OPCPackage create(File file) {
        if (file == null || (file.exists() && file.isDirectory())) {
            throw new IllegalArgumentException(Constants.FILE);
        }
        if (file.exists()) {
            throw new InvalidOperationException("This package (or file) already exists : use the open() method or delete the file.");
        }
        ZipPackage zipPackage = new ZipPackage();
        zipPackage.originalPackagePath = file.getAbsolutePath();
        configurePackage(zipPackage);
        return zipPackage;
    }

    public static OPCPackage open(File file) {
        return open(file, defaultPackageAccess);
    }

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public PackageRelationship addExternalRelationship(String str, String str2, String str3) {
        if (str == null) {
            throw new IllegalArgumentException(TypedValues.AttributesType.S_TARGET);
        }
        if (str2 == null) {
            throw new IllegalArgumentException("relationshipType");
        }
        try {
            URI uri = new URI(str);
            ensureRelationships();
            PackageRelationship packageRelationshipAddRelationship = this.relationships.addRelationship(uri, TargetMode.EXTERNAL, str2, str3);
            this.isDirty = true;
            return packageRelationshipAddRelationship;
        } catch (URISyntaxException e) {
            throw new IllegalArgumentException("Invalid target - " + e);
        }
    }

    public PackagePart createPart(PackagePartName packagePartName, String str, boolean z6) {
        throwExceptionIfReadOnly();
        if (packagePartName == null) {
            throw new IllegalArgumentException("partName");
        }
        if (str == null || str.isEmpty()) {
            throw new IllegalArgumentException("contentType");
        }
        if (this.partList.containsKey(packagePartName) && !this.partList.get(packagePartName).isDeleted()) {
            throw new PartAlreadyExistsException("A part with the name '" + packagePartName.getName() + "' already exists : Packages shall not contain equivalent part names and package implementers shall neither create nor recognize packages with equivalent part names. [M1.12]");
        }
        if (str.equals(ContentTypes.CORE_PROPERTIES_PART) && this.packageProperties != null) {
            throw new InvalidOperationException("OPC Compliance error [M4.1]: you try to add more than one core properties relationship in the package !");
        }
        PackagePart packagePartCreatePartImpl = createPartImpl(packagePartName, str, z6);
        try {
            this.contentTypeManager.addContentType(PackagingURIHelper.createPartName("/.xml"), ContentTypes.PLAIN_OLD_XML);
            this.contentTypeManager.addContentType(PackagingURIHelper.createPartName("/.rels"), ContentTypes.RELATIONSHIPS_PART);
            this.contentTypeManager.addContentType(packagePartName, str);
            this.partList.put(packagePartName, packagePartCreatePartImpl);
            this.isDirty = true;
            return packagePartCreatePartImpl;
        } catch (InvalidFormatException e) {
            throw new InvalidOperationException("unable to create default content-type entries.", e);
        }
    }

    public void removePart(PackagePartName packagePartName) {
        PackagePart part;
        throwExceptionIfReadOnly();
        if (packagePartName == null || !containPart(packagePartName)) {
            throw new IllegalArgumentException("partName");
        }
        if (this.partList.containsKey(packagePartName)) {
            this.partList.get(packagePartName).setDeleted(true);
            removePartImpl(packagePartName);
            this.partList.remove(packagePartName);
        } else {
            removePartImpl(packagePartName);
        }
        this.contentTypeManager.removeContentType(packagePartName);
        if (packagePartName.isRelationshipPartURI()) {
            URI sourcePartUriFromRelationshipPartUri = PackagingURIHelper.getSourcePartUriFromRelationshipPartUri(packagePartName.getURI());
            try {
                PackagePartName packagePartNameCreatePartName = PackagingURIHelper.createPartName(sourcePartUriFromRelationshipPartUri);
                if (packagePartNameCreatePartName.getURI().equals(PackagingURIHelper.PACKAGE_ROOT_URI)) {
                    clearRelationships();
                } else if (containPart(packagePartNameCreatePartName) && (part = getPart(packagePartNameCreatePartName)) != null) {
                    part.clearRelationships();
                }
            } catch (InvalidFormatException unused) {
                LOG.atError().log("Part name URI '{}' is not valid! This message is not intended to be displayed!", sourcePartUriFromRelationshipPartUri);
                return;
            }
        }
        this.isDirty = true;
    }

    public static OPCPackage open(ZipEntrySource zipEntrySource) {
        ZipPackage zipPackage = new ZipPackage(zipEntrySource, PackageAccess.READ);
        try {
            if (((OPCPackage) zipPackage).partList != null) {
                return zipPackage;
            }
            zipPackage.getParts();
            return zipPackage;
        } catch (RuntimeException | InvalidFormatException e) {
            zipPackage.revert();
            throw e;
        }
    }

    public PackagePart getPart(PackageRelationship packageRelationship) {
        ensureRelationships();
        for (PackageRelationship packageRelationship2 : this.relationships) {
            if (packageRelationship2.getRelationshipType().equals(packageRelationship.getRelationshipType())) {
                try {
                    return getPart(PackagingURIHelper.createPartName(packageRelationship2.getTargetURI()));
                } catch (InvalidFormatException unused) {
                    continue;
                }
            }
        }
        return null;
    }

    public static OPCPackage open(String str, PackageAccess packageAccess) {
        if (!StringUtil.isBlank(str)) {
            File file = new File(str);
            if (file.exists() && file.isDirectory()) {
                throw new IllegalArgumentException("path must not be a directory");
            }
            ZipPackage zipPackage = new ZipPackage(str, packageAccess);
            if (((OPCPackage) zipPackage).partList == null && packageAccess != PackageAccess.WRITE) {
                try {
                    zipPackage.getParts();
                } catch (Throwable th) {
                    IOUtils.closeQuietly(zipPackage);
                    throw th;
                }
            }
            zipPackage.originalPackagePath = new File(str).getAbsolutePath();
            return zipPackage;
        }
        throw new IllegalArgumentException("'path' must be given");
    }

    public static OPCPackage create(OutputStream outputStream) {
        ZipPackage zipPackage = new ZipPackage();
        zipPackage.originalPackagePath = null;
        zipPackage.output = outputStream;
        configurePackage(zipPackage);
        return zipPackage;
    }

    public void addThumbnail(String str, InputStream inputStream) {
        PackagePartName packagePartNameCreatePartName;
        if (str != null && !str.isEmpty()) {
            String contentTypeFromFileExtension = ContentTypes.getContentTypeFromFileExtension(str);
            try {
                packagePartNameCreatePartName = PackagingURIHelper.createPartName("/docProps/".concat(str));
            } catch (InvalidFormatException unused) {
                try {
                    packagePartNameCreatePartName = PackagingURIHelper.createPartName("/docProps/thumbnail" + str.substring(str.lastIndexOf(46) + 1));
                } catch (InvalidFormatException e) {
                    throw new InvalidOperationException(AbstractC0157z.o("Can't add a thumbnail file named '", str, "'"), e);
                }
            }
            if (getPart(packagePartNameCreatePartName) == null) {
                PackagePart packagePartCreatePart = createPart(packagePartNameCreatePartName, contentTypeFromFileExtension, false);
                addRelationship(packagePartNameCreatePartName, TargetMode.INTERNAL, PackageRelationshipTypes.THUMBNAIL);
                StreamHelper.copyStream(inputStream, packagePartCreatePart.getOutputStream());
                return;
            }
            throw new InvalidOperationException(AbstractC0157z.o("You already add a thumbnail named '", str, "'"));
        }
        throw new IllegalArgumentException("filename");
    }

    @Override // org.apache.poi.openxml4j.opc.RelationshipSource
    public PackageRelationship addRelationship(PackagePartName packagePartName, TargetMode targetMode, String str) {
        return addRelationship(packagePartName, targetMode, str, null);
    }

    public void save(OutputStream outputStream) {
        throwExceptionIfReadOnly();
        saveImpl(outputStream);
    }

    /* JADX WARN: Code duplicated, block: B:24:0x0037  */
    /* JADX WARN: Code duplicated, block: B:25:0x003b  */
    public static OPCPackage open(File file, PackageAccess packageAccess) throws Throwable {
        if (file != null) {
            if (file.exists() && file.isDirectory()) {
                throw new IllegalArgumentException("file must not be a directory");
            }
            ZipPackage zipPackage = new ZipPackage(file, packageAccess);
            try {
                if (((OPCPackage) zipPackage).partList == null && packageAccess != PackageAccess.WRITE) {
                    zipPackage.getParts();
                }
                zipPackage.originalPackagePath = file.getAbsolutePath();
                return zipPackage;
            } catch (RuntimeException e) {
                e = e;
                if (packageAccess == PackageAccess.READ) {
                    zipPackage.revert();
                } else {
                    IOUtils.closeQuietly(zipPackage);
                }
                throw e;
            } catch (InvalidFormatException e6) {
                e = e6;
                if (packageAccess == PackageAccess.READ) {
                    zipPackage.revert();
                } else {
                    IOUtils.closeQuietly(zipPackage);
                }
                throw e;
            }
        }
        throw new IllegalArgumentException("'file' must be given");
    }

    public PackagePart createPart(PackagePartName packagePartName, String str, ByteArrayOutputStream byteArrayOutputStream) {
        PackagePart packagePartCreatePart = createPart(packagePartName, str);
        if (packagePartCreatePart != null && byteArrayOutputStream != null) {
            try {
                OutputStream outputStream = packagePartCreatePart.getOutputStream();
                if (outputStream == null) {
                    if (outputStream != null) {
                        outputStream.close();
                    }
                    return null;
                }
                try {
                    byteArrayOutputStream.writeTo(outputStream);
                    outputStream.close();
                    return packagePartCreatePart;
                } catch (Throwable th) {
                    try {
                        throw th;
                    } catch (Throwable th2) {
                        try {
                            outputStream.close();
                        } catch (Throwable th3) {
                            th.addSuppressed(th3);
                        }
                        throw th2;
                    }
                }
            } catch (IOException unused) {
            }
        }
        return null;
    }

    public static OPCPackage open(InputStream inputStream) {
        ZipPackage zipPackage = new ZipPackage(inputStream, PackageAccess.READ_WRITE);
        try {
            if (((OPCPackage) zipPackage).partList != null) {
                return zipPackage;
            }
            zipPackage.getParts();
            return zipPackage;
        } catch (RuntimeException | InvalidFormatException e) {
            IOUtils.closeQuietly(zipPackage);
            throw e;
        }
    }
}
